# Generated by Django 5.2.12 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SesionUsuario",
            fields=[
                ("id_sesion", models.AutoField(primary_key=True, serialize=False)),
                ("fk_id_usuario", models.IntegerField()),
                ("token_sesion", models.CharField(max_length=255, unique=True)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_ultima_actividad", models.DateTimeField(auto_now=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_sesion",
                    models.CharField(
                        choices=[
                            ("Activa", "Activa"),
                            ("Cerrada", "Cerrada"),
                            ("Expirada", "Expirada"),
                        ],
                        default="Activa",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "dispositivo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "sesion_usuario",
                "managed": True,
            },
        ),
    ]
