# Generated by Django 5.2.12 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionusuario',
            name='fk_id_usuario',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='token_sesion',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
