# Generated by Django 5.2.12 on 2026-05-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion", "0005_rename_token_passwordresettoken_token_hash_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
