# Generated by Django 5.2.12 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistorialGanador",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("fk_id_usuario", models.IntegerField()),
                ("fk_id_liga", models.IntegerField()),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_premio", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "historial_ganador",
                "managed": True,
            },
        ),
    ]
