# Generated by Django 5.2.12 on 2026-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialganador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialganador',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historialganador',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historialganador',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialganador',
            name='tipo_premio',
            field=models.CharField(choices=[('Local', 'Premio Local de Liga'), ('Global_Individual', 'Premio Global Individual'), ('Global_Liga', 'Premio Global por Liga'), ('Plataforma', 'Retencion Plataforma')], default='Local', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialganador',
            name='fk_id_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
