# Generated by Django 5.2.12 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("puntos", models.IntegerField(default=0)),
                ("fk_id_usuario", models.IntegerField()),
                ("fk_id_liga", models.IntegerField()),
                ("pj", models.IntegerField(default=0)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ranking",
                "managed": True,
            },
        ),
    ]
