# Generated by Django 5.2.12 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='fk_id_liga',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='fk_id_usuario',
            field=models.IntegerField(db_index=True),
        ),
    ]
