# Generated by Django 5.2.12 on 2026-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0002_alter_ranking_fk_id_liga_alter_ranking_fk_id_usuario'),
    ]

    operations = [
        # La tabla historial_ranking ya existe en la BD. Registramos el modelo
        # en el estado de migraciones sin crear la tabla, y agregamos las
        # columnas nuevas (posicion, jornada) que faltan.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HistorialRanking',
                    fields=[
                        ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                        ('fk_id_usuario', models.IntegerField(db_index=True)),
                        ('fk_id_liga', models.IntegerField(db_index=True)),
                        ('puntos', models.IntegerField(default=0)),
                        ('pj', models.IntegerField(default=0)),
                        ('posicion', models.IntegerField(blank=True, null=True)),
                        ('jornada', models.IntegerField(blank=True, db_index=True, null=True)),
                        ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'historial_ranking',
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- Crear tabla si no existe (BD nueva)
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.tables
                                WHERE table_name='historial_ranking'
                            ) THEN
                                CREATE TABLE historial_ranking (
                                    id_historial SERIAL PRIMARY KEY,
                                    fk_id_usuario INTEGER NOT NULL,
                                    fk_id_liga INTEGER NOT NULL,
                                    puntos INTEGER NOT NULL DEFAULT 0,
                                    pj INTEGER NOT NULL DEFAULT 0,
                                    posicion INTEGER,
                                    jornada INTEGER,
                                    fecha_registro TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
                                );
                                CREATE INDEX historial_ranking_jornada_idx ON historial_ranking(jornada);
                            ELSE
                                -- Tabla existe: agregar columnas nuevas (BD existente)
                                IF NOT EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name='historial_ranking' AND column_name='posicion'
                                ) THEN
                                    ALTER TABLE historial_ranking ADD COLUMN posicion integer;
                                END IF;
                                IF NOT EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name='historial_ranking' AND column_name='jornada'
                                ) THEN
                                    ALTER TABLE historial_ranking ADD COLUMN jornada integer;
                                    CREATE INDEX IF NOT EXISTS historial_ranking_jornada_idx
                                        ON historial_ranking(jornada);
                                END IF;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS historial_ranking;
                    """,
                ),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ranking',
            name='posicion_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
