# Generated by Django 5.2.12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Tabla ya existe en BD, no se crea migración
    ]
