# Generated by Django 5.2.12 on 2026-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jugador",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_jugador", models.AutoField(primary_key=True, serialize=False)),
                (
                    "primer_nombre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primer_apellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("dorsal", models.IntegerField(blank=True, null=True)),
                ("posicion", models.CharField(blank=True, max_length=50, null=True)),
                ("fk_id_seleccion", models.IntegerField()),
            ],
            options={
                "db_table": "jugador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                ("id_partido", models.AutoField(primary_key=True, serialize=False)),
                ("horario", models.DateTimeField()),
                ("equipo_local", models.IntegerField()),
                ("equipo_visitante", models.IntegerField()),
                ("fk_sede", models.IntegerField(blank=True, null=True)),
                ("fk_id_fase", models.IntegerField(blank=True, null=True)),
                ("gol_local", models.IntegerField(default=0)),
                ("gol_visitante", models.IntegerField(default=0)),
                ("ganador_penales", models.IntegerField(blank=True, null=True)),
                ("tipo_partido", models.CharField(default="Regular", max_length=50)),
                ("resultado", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "partido",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Seleccion",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_seleccion", models.AutoField(primary_key=True, serialize=False)),
                ("pais", models.CharField(max_length=100)),
                ("bandera", models.CharField(blank=True, max_length=255, null=True)),
                ("fk_id_fase_inicial", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "seleccion",
                "managed": True,
            },
        ),
    ]
