# Generated by Django 5.2.12 on 2026-05-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fk_id_liga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
