# Generated by Django 5.2.12 on 2026-05-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_partido_fk_id_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
    ]
