# Generated by Django 5.2.12 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_seed_banderas'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='status',
            field=models.BooleanField(db_column='status', default=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fk_id_liga',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
