# Generated by Django 5.2.12 on 2026-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0004_partido_deleted_at_partido_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='codigo_iso',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
