# Generated by Django 5.2.12 on 2026-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0006_seed_codigo_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_juego', 'En juego'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='programado', max_length=20),
        ),
    ]
