# Generated by Django 5.2.12 on 2026-05-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0011_seed_jugadores_panama'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fk_partido_origen_local',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del partido anterior cuyo ganador alimenta el equipo local', null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='fk_partido_origen_visitante',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del partido anterior cuyo ganador alimenta el equipo visitante', null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='slot_bracket',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador del slot en el bracket (ej: O1, C1, S1, F1)', max_length=20, null=True),
        ),
    ]
