# Generated by Django 5.2.12 on 2026-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0012_partido_fk_partido_origen_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='faltas_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='faltas_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='minuto_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='partido_iniciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partido',
            name='partido_pausado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partido',
            name='periodo_actual',
            field=models.CharField(default='1T', max_length=20),
        ),
        migrations.AddField(
            model_name='partido',
            name='tiempo_extra_periodo',
            field=models.IntegerField(default=0),
        ),
    ]
