services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: quiniela
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ../database/init-django-tables.sql:/docker-entrypoint-initdb.d/02-init-django-tables.sql
    networks:
      - quiniela_network

volumes:
  postgres_data:

networks:
  quiniela_network:
    driver: bridge
