# Generated by Django 5.2.12 on 2026-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id_premio', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_liga', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('porcentaje_premio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'premio',
                'managed': True,
            },
        ),
    ]
