# Generated by Django 5.2.12 on 2026-05-20 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='porcentaje_premio',
        ),
        migrations.AddField(
            model_name='premio',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='fecha_premio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='premio',
            name='fk_id_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='monto_premio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premio',
            name='tipo_premio',
            field=models.CharField(choices=[('Local', 'Premio Local de Liga'), ('Global_Individual', 'Premio Global Individual'), ('Global_Liga', 'Premio Global por Liga'), ('Plataforma', 'Retencion Plataforma')], default='Local', max_length=20),
        ),
        migrations.AlterField(
            model_name='premio',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
