# Generated by Django 5.2.12 on 2026-05-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0002_remove_premio_porcentaje_premio_premio_detalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='tipo_premio',
        ),
    ]
