# Generated by Django 5.2.12 on 2026-05-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0003_remove_premio_detalle_remove_premio_posicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='fk_id_usuario',
        ),
    ]
