# Generated by Django 5.2.12 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                (
                    "primer_nombre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primer_apellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("telefono", models.IntegerField(blank=True, null=True)),
                ("contrasena", models.CharField(max_length=255)),
                ("fk_rol", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="RolUsuario",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "rol_usuario",
                "managed": True,
            },
        ),
    ]
