# Generated by Django 5.2.12 on 2026-05-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'db_table': 'usuario', 'managed': False},
        ),
    ]
