# Generated by Django 5.2.12 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_seed_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fk_rol',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
