# Generated by Django 5.2.12 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pronostico",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_pronostico", models.AutoField(primary_key=True, serialize=False)),
                ("fk_id_usuario", models.IntegerField()),
                ("fk_id_partido", models.IntegerField()),
                ("fk_id_liga", models.IntegerField()),
                ("gol_local", models.IntegerField()),
                ("gol_visitante", models.IntegerField()),
            ],
            options={
                "db_table": "pronostico",
                "managed": True,
                "unique_together": {("fk_id_usuario", "fk_id_partido", "fk_id_liga")},
            },
        ),
    ]
