# Generated by Django 5.2.12 on 2026-05-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
    ]
