# Generated by Django 5.2.12 on 2026-05-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticos', '0002_alter_pronostico_fk_id_liga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='puntos_obtenidos',
            field=models.IntegerField(default=0),
        ),
    ]
