# Generated by Django 5.2.12 on 2026-05-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_audit_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=10)),
                ('record_pk', models.TextField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_by', models.TextField(default='CURRENT_USER')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('log', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle_accion', models.TextField()),
                ('fk_id_usuario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_liga', models.IntegerField()),
                ('fk_id_seleccion', models.IntegerField()),
            ],
            options={
                'db_table': 'equipoliga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaseGrupo',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fase', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fase_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id_gol', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_partido', models.IntegerField(blank=True, null=True)),
                ('fk_id_jugador', models.IntegerField(blank=True, null=True)),
                ('minuto_marcado', models.IntegerField()),
            ],
            options={
                'db_table': 'gol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartidoLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_liga', models.IntegerField()),
                ('fk_id_partido', models.IntegerField()),
            ],
            options={
                'db_table': 'partido_liga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosicionesTorneo',
            fields=[
                ('id_posicion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_fase', models.IntegerField(blank=True, null=True)),
                ('fk_id_seleccion', models.IntegerField(blank=True, null=True)),
                ('pj', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('gc', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'posiciones_torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id_premio', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_liga', models.IntegerField(blank=True, null=True)),
                ('posicion', models.IntegerField()),
                ('porcentaje_premio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'premio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('puntos', models.IntegerField(default=0)),
                ('fk_id_usuario', models.IntegerField(blank=True, null=True)),
                ('fk_id_liga', models.IntegerField(blank=True, null=True)),
                ('pj', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_usuario', models.IntegerField()),
                ('token_sesion', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado_sesion', models.CharField(default='Activa', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sesion_usuario',
                'managed': False,
            },
        ),
    ]
