# Generated by Django 5.2.12 on 2026-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audit_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicionestorneo',
            name='dg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicionestorneo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posicionestorneo',
            name='fk_id_liga',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='posicionestorneo',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posicionestorneo',
            name='posicion_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posicionestorneo',
            name='fk_id_seleccion',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='posicionestorneo',
            unique_together={('fk_id_liga', 'fk_id_seleccion')},
        ),
    ]
