# Generated by Django 5.2.12 on 2026-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_standings_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionTorneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_plataforma",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Porcentaje que retiene la plataforma al cerrar una liga.",
                        max_digits=5,
                    ),
                ),
                (
                    "puntos_exacto",
                    models.IntegerField(
                        default=3,
                        help_text="Puntos por pronóstico exacto (marcador correcto).",
                    ),
                ),
                (
                    "puntos_ganador",
                    models.IntegerField(
                        default=1,
                        help_text="Puntos por acertar ganador o empate sin marcador exacto.",
                    ),
                ),
                ("fecha_inicio_torneo", models.DateField(blank=True, null=True)),
                ("fecha_fin_torneo", models.DateField(blank=True, null=True)),
                (
                    "permite_registro_abierto",
                    models.BooleanField(
                        default=True,
                        help_text="Permitir registro público de nuevos usuarios.",
                    ),
                ),
                (
                    "max_ligas_por_usuario",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Máximo de ligas que puede administrar un usuario (null = sin límite).",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "configuracion_torneo",
                "managed": True,
            },
        ),
    ]
