# Generated by Django 5.2.12 on 2026-05-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ensure_audit_triggers_active"),
        ("core", "0006_add_configuracion_torneo"),
    ]

    operations = []
