# Generated by Django 5.2.12 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParticipanteLiga",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                (
                    "id_participante",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fk_id_liga", models.IntegerField()),
                ("fk_id_usuario", models.IntegerField()),
                ("fecha_union", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_participacion",
                    models.CharField(default="Activo", max_length=50),
                ),
            ],
            options={
                "db_table": "participante_liga",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartidoLiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fk_id_liga", models.IntegerField()),
                ("fk_id_partido", models.IntegerField()),
            ],
            options={
                "db_table": "partido_liga",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Invitacion",
            fields=[
                ("id_invitacion", models.AutoField(primary_key=True, serialize=False)),
                ("fk_id_liga", models.IntegerField()),
                ("fk_id_usuario_invitado", models.IntegerField()),
                ("fk_id_usuario_administrador", models.IntegerField()),
                ("fecha_invitacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_invitacion",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Aceptada", "Aceptada"),
                            ("Rechazada", "Rechazada"),
                            ("Expirada", "Expirada"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
                ("mensaje_invitacion", models.TextField(blank=True, null=True)),
                (
                    "email_invitado",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "invitacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Liga",
            fields=[
                ("status", models.BooleanField(db_column="status", default=True)),
                ("id_liga", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_liga", models.CharField(max_length=100)),
                ("fk_administrador", models.IntegerField(blank=True, null=True)),
                (
                    "monto_total_recaudado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("tipo_liga", models.CharField(default="Diversion", max_length=50)),
            ],
            options={
                "db_table": "liga",
                "managed": True,
            },
        ),
    ]
