# Generated by Django 5.2.12 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='tipo_liga',
            field=models.CharField(choices=[('Diversion', 'Diversión'), ('Competitiva', 'Competitiva')], default='Diversion', max_length=50),
        ),
    ]
