# Generated by Django 5.2.12 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0002_alter_liga_tipo_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='fk_administrador',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='participanteliga',
            name='fk_id_liga',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participanteliga',
            name='fk_id_usuario',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='partidoliga',
            name='fk_id_liga',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='partidoliga',
            name='fk_id_partido',
            field=models.IntegerField(db_index=True),
        ),
    ]
