# Generated by Django 5.2.12 on 2026-05-21 04:16

import uuid
from django.db import migrations, models


def asignar_codigo_invitacion(apps, schema_editor):
    Invitacion = apps.get_model('ligas', 'Invitacion')
    for invitacion in Invitacion.objects.filter(codigo_invitacion__isnull=True):
        invitacion.codigo_invitacion = uuid.uuid4()
        invitacion.save(update_fields=['codigo_invitacion'])


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0004_liga_cupo_maximo_liga_descripcion_liga_es_publica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='codigo_invitacion',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(asignar_codigo_invitacion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invitacion',
            name='codigo_invitacion',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fk_id_usuario_invitado',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
