# Generated by Django 5.2.12 on 2026-05-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0005_invitacion_codigo_invitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liga',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='liga',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='liga',
            name='es_publica',
        ),
        migrations.DeleteModel(
            name='SolicitudParticipacion',
        ),
    ]
