# Generated by Django 5.2.12 on 2026-05-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0006_remove_liga_cupo_maximo_remove_liga_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liga',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liga',
            name='es_publica',
            field=models.BooleanField(default=False, help_text='Visible en el buscador público si está activa.'),
        ),
        migrations.AddField(
            model_name='liga',
            name='requiere_aprobacion',
            field=models.BooleanField(default=True, help_text='Si está activo, los administradores deben aprobar cada solicitud.'),
        ),
        migrations.CreateModel(
            name='SolicitudParticipacion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], db_index=True, default='Pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respondido_por', models.IntegerField(blank=True, null=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='ligas.liga')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_participacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud_participacion',
                'ordering': ['-fecha_solicitud'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'Pendiente'), ('usuario__isnull', False)), fields=('liga', 'usuario'), name='unique_solicitud_liga_usuario_pendiente')],
            },
        ),
    ]
