# Generated by Django 5.2.12 on 2026-05-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0009_add_audit_fields_to_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='cuota_entrada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que cada usuario paga al unirse a la liga', max_digits=10),
        ),
    ]
