# Generated file - Jugadores Mundial 2026
JUGADORES_DATA = [
    ('México', 1, 'Luis Malagón', 'Portero'),
    ('México', 2, 'Jorge Sánchez', 'Defensa'),
    ('México', 3, 'César Montes', 'Defensa'),
    ('México', 4, 'Edson Álvarez', 'Centrocampista'),
    ('México', 5, 'Johan Vásquez', 'Defensa'),
    ('México', 6, 'Gerardo Arteaga', 'Defensa'),
    ('México', 7, 'Luis Romo', 'Centrocampista'),
    ('México', 8, 'Carlos Rodríguez', 'Centrocampista'),
    ('México', 9, 'Santiago Giménez', 'Delantero'),
    ('México', 10, 'Alexis Vega', 'Delantero'),
    ('México', 11, 'Santiago Quiñones', 'Delantero'),
    ('México', 12, 'Julio González', 'Portero'),
    ('México', 13, 'Guillermo Ochoa', 'Portero'),
    ('México', 14, 'Erick Sánchez', 'Centrocampista'),
    ('México', 15, 'Uriel Antuna', 'Delantero'),
    ('México', 16, 'Israel Reyes', 'Defensa'),
    ('México', 17, 'Luis Chávez', 'Centrocampista'),
    ('México', 18, 'Hirving Lozano', 'Delantero'),
    ('México', 19, 'Henry Martín', 'Delantero'),
    ('México', 20, 'Roberto Alvarado', 'Delantero'),
    ('México', 21, 'César Huerta', 'Delantero'),
    ('México', 22, 'Jesús Orozco Chiquete', 'Defensa'),
    ('México', 23, 'Alan Mozo', 'Defensa'),
    ('México', 24, 'Marcel Ruiz', 'Centrocampista'),
    ('México', 25, 'Jordi Cortizo', 'Centrocampista'),
    ('México', 26, 'Bryan González', 'Defensa'),
    ('Sudáfrica', 1, 'Ronwen Williams', 'Portero'),
    ('Sudáfrica', 2, 'Nyiko Mobbie', 'Defensa'),
    ('Sudáfrica', 3, 'Rushwin Dortley', 'Defensa'),
    ('Sudáfrica', 4, 'Teboho Mokoena', 'Centrocampista'),
    ('Sudáfrica', 5, 'Siyabonga Ngezana', 'Defensa'),
    ('Sudáfrica', 6, 'Aubrey Modiba', 'Defensa'),
    ('Sudáfrica', 7, 'Oswin Appollis', 'Delantero'),
    ('Sudáfrica', 8, 'Jayden Adams', 'Centrocampista'),
    ('Sudáfrica', 9, 'Evidence Makgopa', 'Delantero'),
    ('Sudáfrica', 10, 'Percy Tau', 'Delantero'),
    ('Sudáfrica', 11, 'Themba Zwane', 'Centrocampista'),
    ('Sudáfrica', 12, 'Thapelo Morena', 'Defensa'),
    ('Sudáfrica', 13, 'Sphephelo Sithole', 'Centrocampista'),
    ('Sudáfrica', 14, 'Mothobi Mvala', 'Defensa'),
    ('Sudáfrica', 15, 'Iqraam Rayners', 'Delantero'),
    ('Sudáfrica', 16, 'Veli Mothwa', 'Portero'),
    ('Sudáfrica', 17, 'Lyle Foster', 'Delantero'),
    ('Sudáfrica', 18, 'Thapelo Xoki', 'Defensa'),
    ('Sudáfrica', 19, 'Thalente Mbatha', 'Centrocampista'),
    ('Sudáfrica', 20, 'Khuliso Mudau', 'Defensa'),
    ('Sudáfrica', 21, 'Elias Mokwana', 'Delantero'),
    ('Sudáfrica', 22, 'Ricardo Goss', 'Portero'),
    ('Sudáfrica', 23, 'Thabang Monare', 'Centrocampista'),
    ('Sudáfrica', 24, 'Grant Kekana', 'Defensa'),
    ('Sudáfrica', 25, 'Relebohile Mofokeng', 'Delantero'),
    ('Sudáfrica', 26, 'Bathusi Aubaas', 'Centrocampista'),
    ('Corea del Sur', 1, 'Kim Seung-gyu', 'Portero'),
    ('Corea del Sur', 2, 'Kim Moon-hwan', 'Defensa'),
    ('Corea del Sur', 3, 'Kim Min-jae', 'Defensa'),
    ('Corea del Sur', 4, 'Park Jin-seob', 'Defensa'),
    ('Corea del Sur', 5, 'Cho Yu-min', 'Defensa'),
    ('Corea del Sur', 6, 'Hwang In-beom', 'Centrocampista'),
    ('Corea del Sur', 7, 'Son Heung-min', 'Delantero'),
    ('Corea del Sur', 8, 'Lee Jae-sung', 'Centrocampista'),
    ('Corea del Sur', 9, 'Cho Gue-sung', 'Delantero'),
    ('Corea del Sur', 10, 'Lee Kang-in', 'Centrocampista'),
    ('Corea del Sur', 11, 'Hwang Hee-chan', 'Centrocampista'),
    ('Corea del Sur', 12, 'Jo Hyeon-woo', 'Portero'),
    ('Corea del Sur', 13, 'Seol Young-woo', 'Defensa'),
    ('Corea del Sur', 14, 'Lee Sam-seok', 'Defensa'),
    ('Corea del Sur', 15, 'Lee Han-beom', 'Defensa'),
    ('Corea del Sur', 16, 'Kim Tae-hyeon', 'Defensa'),
    ('Corea del Sur', 17, 'Jens Castrop', 'Defensa'),
    ('Corea del Sur', 18, 'Lee Ki-hyuk', 'Defensa'),
    ('Corea del Sur', 19, 'Paik Seung-ho', 'Centrocampista'),
    ('Corea del Sur', 20, 'Kim Jin-gyu', 'Centrocampista'),
    ('Corea del Sur', 21, 'Lee Dong-gyeong', 'Centrocampista'),
    ('Corea del Sur', 22, 'Bae Jun-ho', 'Centrocampista'),
    ('Corea del Sur', 23, 'Song Bum-keun', 'Portero'),
    ('Corea del Sur', 24, 'Eom Ji-sung', 'Centrocampista'),
    ('Corea del Sur', 25, 'Yang Hyun-jun', 'Centrocampista'),
    ('Corea del Sur', 26, 'Oh Hyeon-gyu', 'Delantero'),
    ('Canadá', 1, 'Maxime Crépeau', 'Portero'),
    ('Canadá', 2, 'Alistair Johnston', 'Defensa'),
    ('Canadá', 3, 'Kamal Miller', 'Defensa'),
    ('Canadá', 5, 'Derek Cornelius', 'Defensa'),
    ('Canadá', 6, 'Samuel Piette', 'Centrocampista'),
    ('Canadá', 7, 'Stephen Eustáquio', 'Centrocampista'),
    ('Canadá', 8, 'Ismaël Koné', 'Centrocampista'),
    ('Canadá', 9, 'Cyle Larin', 'Delantero'),
    ('Canadá', 10, 'Jonathan David', 'Delantero'),
    ('Canadá', 11, 'Theo Bair', 'Delantero'),
    ('Canadá', 12, 'James Pantemis', 'Portero'),
    ('Canadá', 14, 'Moïse Bombito', 'Defensa'),
    ('Canadá', 15, 'Alphonso Davies', 'Defensa'),
    ('Canadá', 16, 'Richie Laryea', 'Defensa'),
    ('Canadá', 17, 'Tajon Buchanan', 'Delantero'),
    ('Canadá', 18, 'Dayne St. Clair', 'Portero'),
    ('Canadá', 19, 'Liam Millar', 'Delantero'),
    ('Canadá', 20, 'Ali Ahmed', 'Centrocampista'),
    ('Canadá', 21, 'Jonathan Osorio', 'Centrocampista'),
    ('Canadá', 23, 'Jacob Shaffelburg', 'Delantero'),
    ('Canadá', 24, 'Mathieu Choinière', 'Centrocampista'),
    ('Canadá', 25, 'Joel Waterman', 'Defensa'),
    ('Canadá', 26, 'Tani Oluwaseyi', 'Delantero'),
    ('Brasil', 1, 'Alisson Becker', 'Portero'),
    ('Brasil', 2, 'Danilo da Silva', 'Defensa'),
    ('Brasil', 3, 'Marquinhos', 'Defensa'),
    ('Brasil', 4, 'Gabriel Magalhães', 'Defensa'),
    ('Brasil', 5, 'Casemiro', 'Centrocampista'),
    ('Brasil', 6, 'Alex Sandro', 'Defensa'),
    ('Brasil', 7, 'Vinicius Junior', 'Delantero'),
    ('Brasil', 8, 'Bruno Guimarães', 'Centrocampista'),
    ('Brasil', 9, 'Endrick Felipe', 'Delantero'),
    ('Brasil', 10, 'Neymar Jr.', 'Delantero'),
    ('Brasil', 11, 'Raphinha', 'Delantero'),
    ('Brasil', 12, 'Bento Matheus', 'Portero'),
    ('Brasil', 13, 'Roger Ibañez', 'Defensa'),
    ('Brasil', 14, 'Bremer', 'Defensa'),
    ('Brasil', 15, 'Léo Pereira', 'Defensa'),
    ('Brasil', 16, 'Douglas Santos', 'Defensa'),
    ('Brasil', 17, 'Wesley França', 'Defensa'),
    ('Brasil', 18, 'Fabinho', 'Centrocampista'),
    ('Brasil', 19, 'Lucas Paquetá', 'Centrocampista'),
    ('Brasil', 20, 'Danilo Santos', 'Centrocampista'),
    ('Brasil', 21, 'Gabriel Martinelli', 'Delantero'),
    ('Brasil', 22, 'Weverton Silva', 'Portero'),
    ('Brasil', 23, 'Matheus Cunha', 'Delantero'),
    ('Brasil', 24, 'Luiz Henrique', 'Delantero'),
    ('Brasil', 25, 'Igor Thiago', 'Delantero'),
    ('Brasil', 26, 'Rayan Vitor', 'Delantero'),
    ('Estados Unidos', 1, 'Matt Turner', 'Portero'),
    ('Estados Unidos', 2, 'Sergiño Dest', 'Defensa'),
    ('Estados Unidos', 3, 'Chris Richards', 'Defensa'),
    ('Estados Unidos', 4, 'Tyler Adams', 'Centrocampista'),
    ('Estados Unidos', 5, 'Antonee Robinson', 'Defensa'),
    ('Estados Unidos', 6, 'Yunus Musah', 'Centrocampista'),
    ('Estados Unidos', 7, 'Gio Reyna', 'Centrocampista'),
    ('Estados Unidos', 8, 'Weston McKennie', 'Centrocampista'),
    ('Estados Unidos', 9, 'Folarin Balogun', 'Delantero'),
    ('Estados Unidos', 10, 'Christian Pulisic', 'Delantero'),
    ('Estados Unidos', 11, 'Brenden Aaronson', 'Delantero'),
    ('Estados Unidos', 12, 'Miles Robinson', 'Defensa'),
    ('Estados Unidos', 13, 'Tim Ream', 'Defensa'),
    ('Estados Unidos', 14, 'Luca de la Torre', 'Centrocampista'),
    ('Estados Unidos', 15, 'Johnny Cardoso', 'Centrocampista'),
    ('Estados Unidos', 16, 'Mark McKenzie', 'Defensa'),
    ('Estados Unidos', 17, 'Malik Tillman', 'Centrocampista'),
    ('Estados Unidos', 18, 'Ethan Horvath', 'Portero'),
    ('Estados Unidos', 19, 'Ricardo Pepi', 'Delantero'),
    ('Estados Unidos', 20, 'Timothy Weah', 'Delantero'),
    ('Estados Unidos', 21, 'Haji Wright', 'Delantero'),
    ('Estados Unidos', 22, 'Joe Scally', 'Defensa'),
    ('Estados Unidos', 23, 'Patrick Schulte', 'Portero'),
    ('Estados Unidos', 24, 'Cameron Carter-Vickers', 'Defensa'),
    ('Estados Unidos', 25, 'Kristoffer Lund', 'Defensa'),
    ('Estados Unidos', 26, 'Josh Sargent', 'Delantero'),
    ('Argentina', 1, 'Franco Armani', 'Portero'),
    ('Argentina', 2, 'Lucas Martínez Quarta', 'Defensa'),
    ('Argentina', 3, 'Nicolás Tagliafico', 'Defensa'),
    ('Argentina', 4, 'Gonzalo Montiel', 'Defensa'),
    ('Argentina', 5, 'Leandro Paredes', 'Centrocampista'),
    ('Argentina', 6, 'Germán Pezzella', 'Defensa'),
    ('Argentina', 7, 'Rodrigo De Paul', 'Centrocampista'),
    ('Argentina', 8, 'Marcos Acuña', 'Defensa'),
    ('Argentina', 9, 'Julián Álvarez', 'Delantero'),
    ('Argentina', 10, 'Lionel Messi', 'Delantero'),
    ('Argentina', 11, 'Ángel Di María', 'Delantero'),
    ('Argentina', 12, 'Geronimo Rulli', 'Portero'),
    ('Argentina', 13, 'Cristian Romero', 'Defensa'),
    ('Argentina', 14, 'Exequiel Palacios', 'Centrocampista'),
    ('Argentina', 15, 'Nicolás González', 'Delantero'),
    ('Argentina', 16, 'Giovani Lo Celso', 'Centrocampista'),
    ('Argentina', 17, 'Alejandro Garnacho', 'Delantero'),
    ('Argentina', 18, 'Guido Rodríguez', 'Centrocampista'),
    ('Argentina', 19, 'Nicolás Otamendi', 'Defensa'),
    ('Argentina', 20, 'Alexis Mac Allister', 'Centrocampista'),
    ('Argentina', 21, 'Valentin Carboni', 'Centrocampista'),
    ('Argentina', 22, 'Lautaro Martínez', 'Delantero'),
    ('Argentina', 23, 'Emiliano Martínez', 'Portero'),
    ('Argentina', 24, 'Enzo Fernández', 'Centrocampista'),
    ('Argentina', 25, 'Lisandro Martínez', 'Defensa'),
    ('Argentina', 26, 'Nahuel Molina', 'Defensa'),
    ('España', 1, 'David Raya', 'Portero'),
    ('España', 2, 'Dani Carvajal', 'Defensa'),
    ('España', 3, 'Robin Le Normand', 'Defensa'),
    ('España', 4, 'Nacho Fernández', 'Defensa'),
    ('España', 5, 'Daniel Vivian', 'Defensa'),
    ('España', 6, 'Mikel Merino', 'Centrocampista'),
    ('España', 7, 'Álvaro Morata', 'Delantero'),
    ('España', 8, 'Fabian Ruiz', 'Centrocampista'),
    ('España', 9, 'Joselu Mato', 'Delantero'),
    ('España', 10, 'Dani Olmo', 'Centrocampista'),
    ('España', 11, 'Ferran Torres', 'Delantero'),
    ('España', 12, 'Alex Grimaldo', 'Defensa'),
    ('España', 13, 'Álex Remiro', 'Portero'),
    ('España', 14, 'Aymeric Laporte', 'Defensa'),
    ('España', 15, 'Alex Baena', 'Centrocampista'),
    ('España', 16, 'Rodri Hernández', 'Centrocampista'),
    ('España', 17, 'Nico Williams', 'Delantero'),
    ('España', 18, 'Martin Zubimendi', 'Centrocampista'),
    ('España', 19, 'Lamine Yamal', 'Delantero'),
    ('España', 20, 'Pedri González', 'Centrocampista'),
    ('España', 21, 'Mikel Oyarzabal', 'Delantero'),
    ('España', 22, 'Jesus Navas', 'Defensa'),
    ('España', 23, 'Unai Simón', 'Portero'),
    ('España', 24, 'Marc Cucurella', 'Defensa'),
    ('España', 25, 'Fermín López', 'Centrocampista'),
    ('España', 26, 'Ayoze Pérez', 'Delantero'),
    ('Francia', 1, 'Brice Samba', 'Portero'),
    ('Francia', 2, 'Benjamin Pavard', 'Defensa'),
    ('Francia', 3, 'Ferland Mendy', 'Defensa'),
    ('Francia', 4, 'Dayot Upamecano', 'Defensa'),
    ('Francia', 5, 'Jules Koundé', 'Defensa'),
    ('Francia', 6, 'Eduardo Camavinga', 'Centrocampista'),
    ('Francia', 7, 'Antoine Griezmann', 'Delantero'),
    ('Francia', 8, 'Aurélien Tchouaméni', 'Centrocampista'),
    ('Francia', 9, 'Olivier Giroud', 'Delantero'),
    ('Francia', 10, 'Kylian Mbappé', 'Delantero'),
    ('Francia', 11, 'Ousmane Dembélé', 'Delantero'),
    ('Francia', 12, 'Randal Kolo Muani', 'Delantero'),
    ('Francia', 13, 'N\'Golo Kanté', 'Centrocampista'),
    ('Francia', 14, 'Adrien Rabiot', 'Centrocampista'),
    ('Francia', 15, 'Marcus Thuram', 'Delantero'),
    ('Francia', 16, 'Mike Maignan', 'Portero'),
    ('Francia', 17, 'William Saliba', 'Defensa'),
    ('Francia', 18, 'Warren Zaïre-Emery', 'Centrocampista'),
    ('Francia', 19, 'Youssouf Fofana', 'Centrocampista'),
    ('Francia', 20, 'Kingsley Coman', 'Delantero'),
    ('Francia', 21, 'Jonathan Clauss', 'Defensa'),
    ('Francia', 22, 'Théo Hernandez', 'Defensa'),
    ('Francia', 23, 'Alphonse Areola', 'Portero'),
    ('Francia', 24, 'Ibrahima Konaté', 'Defensa'),
    ('Francia', 25, 'Bradley Barcola', 'Delantero'),
    ('Francia', 26, 'Ferland Mendy', 'Defensa'),
    ('Alemania', 1, 'Manuel Neuer', 'Portero'),
    ('Alemania', 2, 'Antonio Rüdiger', 'Defensa'),
    ('Alemania', 3, 'David Raum', 'Defensa'),
    ('Alemania', 4, 'Jonathan Tah', 'Defensa'),
    ('Alemania', 5, 'Pascal Groß', 'Centrocampista'),
    ('Alemania', 6, 'Joshua Kimmich', 'Defensa'),
    ('Alemania', 7, 'Kai Havertz', 'Delantero'),
    ('Alemania', 8, 'Toni Kroos', 'Centrocampista'),
    ('Alemania', 9, 'Niclas Füllkrug', 'Delantero'),
    ('Alemania', 10, 'Jamal Musiala', 'Centrocampista'),
    ('Alemania', 11, 'Chris Führich', 'Delantero'),
    ('Alemania', 12, 'Oliver Baumann', 'Portero'),
    ('Alemania', 13, 'Thomas Müller', 'Delantero'),
    ('Alemania', 14, 'Maximilian Beier', 'Delantero'),
    ('Alemania', 15, 'Nico Schlotterbeck', 'Defensa'),
    ('Alemania', 16, 'Waldemar Anton', 'Defensa'),
    ('Alemania', 17, 'Florian Wirtz', 'Centrocampista'),
    ('Alemania', 18, 'Maximilian Mittelstädt', 'Defensa'),
    ('Alemania', 19, 'Leroy Sané', 'Delantero'),
    ('Alemania', 20, 'Benjamin Henrichs', 'Defensa'),
    ('Alemania', 21, 'Ilkay Gündogan', 'Centrocampista'),
    ('Alemania', 22, 'Marc-André ter Stegen', 'Portero'),
    ('Alemania', 23, 'Robert Andrich', 'Centrocampista'),
    ('Alemania', 24, 'Robin Koch', 'Defensa'),
    ('Alemania', 25, 'Emre Can', 'Centrocampista'),
    ('Alemania', 26, 'Deniz Undav', 'Delantero'),
    ('Portugal', 1, 'Rui Patrício', 'Portero'),
    ('Portugal', 2, 'Nélson Semedo', 'Defensa'),
    ('Portugal', 3, 'Pepe', 'Defensa'),
    ('Portugal', 4, 'Rúben Dias', 'Defensa'),
    ('Portugal', 5, 'Diogo Dalot', 'Defensa'),
    ('Portugal', 6, 'João Palhinha', 'Centrocampista'),
    ('Portugal', 7, 'Cristiano Ronaldo', 'Delantero'),
    ('Portugal', 8, 'Bruno Fernandes', 'Centrocampista'),
    ('Portugal', 9, 'Gonçalo Ramos', 'Delantero'),
    ('Portugal', 10, 'Bernardo Silva', 'Centrocampista'),
    ('Portugal', 11, 'João Félix', 'Delantero'),
    ('Portugal', 12, 'José Sá', 'Portero'),
    ('Portugal', 13, 'Danilo Pereira', 'Defensa'),
    ('Portugal', 14, 'Gonçalo Inácio', 'Defensa'),
    ('Portugal', 15, 'João Neves', 'Centrocampista'),
    ('Portugal', 16, 'Matheus Nunes', 'Centrocampista'),
    ('Portugal', 17, 'Rafael Leão', 'Delantero'),
    ('Portugal', 18, 'Rúben Neves', 'Centrocampista'),
    ('Portugal', 19, 'Nuno Mendes', 'Defensa'),
    ('Portugal', 20, 'João Cancelo', 'Defensa'),
    ('Portugal', 21, 'Diogo Jota', 'Delantero'),
    ('Portugal', 22, 'Diogo Costa', 'Portero'),
    ('Portugal', 23, 'Vitinha', 'Centrocampista'),
    ('Portugal', 24, 'António Silva', 'Defensa'),
    ('Portugal', 25, 'Pedro Neto', 'Delantero'),
    ('Portugal', 26, 'Francisco Conceição', 'Delantero'),
    ('Inglaterra', 1, 'Jordan Pickford', 'Portero'),
    ('Inglaterra', 2, 'Kyle Walker', 'Defensa'),
    ('Inglaterra', 3, 'Luke Shaw', 'Defensa'),
    ('Inglaterra', 4, 'Declan Rice', 'Centrocampista'),
    ('Inglaterra', 5, 'John Stones', 'Defensa'),
    ('Inglaterra', 6, 'Marc Guéhi', 'Defensa'),
    ('Inglaterra', 7, 'Bukayo Saka', 'Delantero'),
    ('Inglaterra', 8, 'Trent Alexander-Arnold', 'Centrocampista'),
    ('Inglaterra', 9, 'Harry Kane', 'Delantero'),
    ('Inglaterra', 10, 'Jude Bellingham', 'Centrocampista'),
    ('Inglaterra', 11, 'Phil Foden', 'Delantero'),
    ('Inglaterra', 12, 'Kieran Trippier', 'Defensa'),
    ('Inglaterra', 13, 'Aaron Ramsdale', 'Portero'),
    ('Inglaterra', 14, 'Ezri Konsa', 'Defensa'),
    ('Inglaterra', 15, 'Lewis Dunk', 'Defensa'),
    ('Inglaterra', 16, 'Conor Gallagher', 'Centrocampista'),
    ('Inglaterra', 17, 'Ivan Toney', 'Delantero'),
    ('Inglaterra', 18, 'Anthony Gordon', 'Delantero'),
    ('Inglaterra', 19, 'Ollie Watkins', 'Delantero'),
    ('Inglaterra', 20, 'Jarrod Bowen', 'Delantero'),
    ('Inglaterra', 21, 'Eberechi Eze', 'Delantero'),
    ('Inglaterra', 22, 'Joe Gomez', 'Defensa'),
    ('Inglaterra', 23, 'Dean Henderson', 'Portero'),
    ('Inglaterra', 24, 'Cole Palmer', 'Centrocampista'),
    ('Inglaterra', 25, 'Adam Wharton', 'Centrocampista'),
    ('Inglaterra', 26, 'Kobbie Mainoo', 'Centrocampista'),
    ('Países Bajos', 1, 'Bart Verbruggen', 'Portero'),
    ('Países Bajos', 2, 'Lutsharear Geertruida', 'Defensa'),
    ('Países Bajos', 3, 'Matthijs de Ligt', 'Defensa'),
    ('Países Bajos', 4, 'Virgil van Dijk', 'Defensa'),
    ('Países Bajos', 5, 'Nathan Aké', 'Defensa'),
    ('Países Bajos', 6, 'Stefan de Vrij', 'Defensa'),
    ('Países Bajos', 7, 'Xavi Simons', 'Centrocampista'),
    ('Países Bajos', 8, 'Georginio Wijnaldum', 'Centrocampista'),
    ('Países Bajos', 9, 'Wout Weghorst', 'Delantero'),
    ('Países Bajos', 10, 'Memphis Depay', 'Delantero'),
    ('Países Bajos', 11, 'Cody Gakpo', 'Delantero'),
    ('Países Bajos', 12, 'Jeremie Frimpong', 'Defensa'),
    ('Países Bajos', 13, 'Justin Bijlow', 'Portero'),
    ('Países Bajos', 14, 'Tijjani Reijnders', 'Centrocampista'),
    ('Países Bajos', 15, 'Micky van de Ven', 'Defensa'),
    ('Países Bajos', 16, 'Joey Veerman', 'Centrocampista'),
    ('Países Bajos', 17, 'Daley Blind', 'Defensa'),
    ('Países Bajos', 18, 'Donyell Malen', 'Delantero'),
    ('Países Bajos', 19, 'Brian Brobbey', 'Delantero'),
    ('Países Bajos', 20, 'Teun Koopmeiners', 'Centrocampista'),
    ('Países Bajos', 21, 'Joshua Zirkzee', 'Delantero'),
    ('Países Bajos', 22, 'Denzel Dumfries', 'Defensa'),
    ('Países Bajos', 23, 'Mark Flekken', 'Portero'),
    ('Países Bajos', 24, 'Jerdy Schouten', 'Centrocampista'),
    ('Países Bajos', 25, 'Ryan Gravenberch', 'Centrocampista'),
    ('Países Bajos', 26, 'Steven Bergwijn', 'Delantero'),
    ('Bélgica', 1, 'Koen Casteels', 'Portero'),
    ('Bélgica', 2, 'Zeno Debast', 'Defensa'),
    ('Bélgica', 3, 'Arthur Theate', 'Defensa'),
    ('Bélgica', 4, 'Wout Faes', 'Defensa'),
    ('Bélgica', 5, 'Jan Vertonghen', 'Defensa'),
    ('Bélgica', 6, 'Axel Witsel', 'Defensa'),
    ('Bélgica', 7, 'Kevin De Bruyne', 'Centrocampista'),
    ('Bélgica', 8, 'Youri Tielemans', 'Centrocampista'),
    ('Bélgica', 9, 'Leandro Trossard', 'Delantero'),
    ('Bélgica', 10, 'Romelu Lukaku', 'Delantero'),
    ('Bélgica', 11, 'Yannick Carrasco', 'Delantero'),
    ('Bélgica', 12, 'Thomas Kaminski', 'Portero'),
    ('Bélgica', 13, 'Matz Sels', 'Portero'),
    ('Bélgica', 14, 'Dodi Lukebakio', 'Delantero'),
    ('Bélgica', 15, 'Thomas Meunier', 'Defensa'),
    ('Bélgica', 16, 'Aster Vranckx', 'Centrocampista'),
    ('Bélgica', 17, 'Charles De Ketelaere', 'Delantero'),
    ('Bélgica', 18, 'Orel Mangala', 'Centrocampista'),
    ('Bélgica', 19, 'Johan Bakayoko', 'Delantero'),
    ('Bélgica', 20, 'Loïs Openda', 'Delantero'),
    ('Bélgica', 21, 'Timothy Castagne', 'Defensa'),
    ('Bélgica', 22, 'Jérémy Doku', 'Delantero'),
    ('Bélgica', 23, 'Arthur Vermeeren', 'Centrocampista'),
    ('Bélgica', 24, 'Amadou Onana', 'Centrocampista'),
    ('Bélgica', 25, 'Maxim De Cuyper', 'Defensa'),
    ('Bélgica', 26, 'Mandela Keita', 'Centrocampista'),
    ('Uruguay', 1, 'Sergio Rochet', 'Portero'),
    ('Uruguay', 2, 'José María Giménez', 'Defensa'),
    ('Uruguay', 3, 'Sebastián Cáceres', 'Defensa'),
    ('Uruguay', 4, 'Ronald Araújo', 'Defensa'),
    ('Uruguay', 5, 'Manuel Ugarte', 'Centrocampista'),
    ('Uruguay', 6, 'Rodrigo Bentancur', 'Centrocampista'),
    ('Uruguay', 7, 'Nicolás de la Cruz', 'Centrocampista'),
    ('Uruguay', 8, 'Nahitan Nández', 'Centrocampista'),
    ('Uruguay', 9, 'Luis Suárez', 'Delantero'),
    ('Uruguay', 10, 'Giorgian de Arrascaeta', 'Centrocampista'),
    ('Uruguay', 11, 'Facundo Pellistri', 'Delantero'),
    ('Uruguay', 12, 'Santiago Mele', 'Portero'),
    ('Uruguay', 13, 'Guillermo Varela', 'Defensa'),
    ('Uruguay', 14, 'Agustín Canobbio', 'Delantero'),
    ('Uruguay', 15, 'Federico Valverde', 'Centrocampista'),
    ('Uruguay', 16, 'Mathías Olivera', 'Defensa'),
    ('Uruguay', 17, 'Matías Viña', 'Defensa'),
    ('Uruguay', 18, 'Brian Rodríguez', 'Delantero'),
    ('Uruguay', 19, 'Darwin Núñez', 'Delantero'),
    ('Uruguay', 20, 'Maximiliano Araújo', 'Delantero'),
    ('Uruguay', 21, 'Emiliano Martínez Toranza', 'Centrocampista'),
    ('Uruguay', 22, 'Nicolás Marichal', 'Defensa'),
    ('Uruguay', 23, 'Franco Israel', 'Portero'),
    ('Uruguay', 24, 'Lucas Olaza', 'Defensa'),
    ('Uruguay', 25, 'Cristian Olivera', 'Delantero'),
    ('Uruguay', 26, 'Brian Ocampo', 'Delantero'),
    ('Colombia', 1, 'David Ospina', 'Portero'),
    ('Colombia', 2, 'Carlos Cuesta', 'Defensa'),
    ('Colombia', 3, 'Jhon Lucumí', 'Defensa'),
    ('Colombia', 4, 'Santiago Arias', 'Defensa'),
    ('Colombia', 5, 'Kevin Castaño', 'Centrocampista'),
    ('Colombia', 6, 'Richard Ríos', 'Centrocampista'),
    ('Colombia', 7, 'Luis Díaz', 'Delantero'),
    ('Colombia', 8, 'Jorge Carrascal', 'Centrocampista'),
    ('Colombia', 9, 'Miguel Borja', 'Delantero'),
    ('Colombia', 10, 'James Rodríguez', 'Centrocampista'),
    ('Colombia', 11, 'Jhon Arias', 'Delantero'),
    ('Colombia', 12, 'Camilo Vargas', 'Portero'),
    ('Colombia', 13, 'Yerry Mina', 'Defensa'),
    ('Colombia', 14, 'Andrés Gómez', 'Delantero'),
    ('Colombia', 15, 'Mateus Uribe', 'Centrocampista'),
    ('Colombia', 16, 'Jefferson Lerma', 'Centrocampista'),
    ('Colombia', 17, 'Johan Mojica', 'Defensa'),
    ('Colombia', 18, 'Luis Sinisterra', 'Delantero'),
    ('Colombia', 19, 'Rafael Santos Borré', 'Delantero'),
    ('Colombia', 20, 'Juan Fernando Quintero', 'Centrocampista'),
    ('Colombia', 21, 'Daniel Muñoz', 'Defensa'),
    ('Colombia', 22, 'Yáser Asprilla', 'Centrocampista'),
    ('Colombia', 23, 'Álvaro Montero', 'Portero'),
    ('Colombia', 24, 'Davinson Sánchez', 'Defensa'),
    ('Colombia', 25, 'Deiver Machado', 'Defensa'),
    ('Colombia', 26, 'Jhon Durán', 'Delantero'),
    ('Croacia', 1, 'Dominik Livaković', 'Portero'),
    ('Croacia', 2, 'Josip Stanišić', 'Defensa'),
    ('Croacia', 3, 'Borna Sosa', 'Defensa'),
    ('Croacia', 4, 'Ivan Perišić', 'Delantero'),
    ('Croacia', 5, 'Martin Erlić', 'Defensa'),
    ('Croacia', 6, 'Josip Šutalo', 'Defensa'),
    ('Croacia', 7, 'Lovro Majer', 'Centrocampista'),
    ('Croacia', 8, 'Mateo Kovačić', 'Centrocampista'),
    ('Croacia', 9, 'Andrej Kramarić', 'Delantero'),
    ('Croacia', 10, 'Luka Modrić', 'Centrocampista'),
    ('Croacia', 11, 'Marcelo Brozović', 'Centrocampista'),
    ('Croacia', 12, 'Nediljko Labrović', 'Portero'),
    ('Croacia', 13, 'Nikola Vlašić', 'Centrocampista'),
    ('Croacia', 15, 'Mario Pašalić', 'Centrocampista'),
    ('Croacia', 16, 'Ivica Ivušić', 'Portero'),
    ('Croacia', 17, 'Bruno Petković', 'Delantero'),
    ('Croacia', 18, 'Luka Ivanušec', 'Centrocampista'),
    ('Croacia', 19, 'Borna Barišić', 'Defensa'),
    ('Croacia', 20, 'Joško Gvardiol', 'Defensa'),
    ('Croacia', 21, 'Domagoj Vida', 'Defensa'),
    ('Croacia', 22, 'Josip Juranović', 'Defensa'),
    ('Croacia', 24, 'Marco Pašalić', 'Delantero'),
    ('Croacia', 25, 'Luka Sučić', 'Centrocampista'),
    ('Croacia', 26, 'Martin Baturina', 'Centrocampista'),
    ('Marruecos', 1, 'Yassine Bounou', 'Portero'),
    ('Marruecos', 2, 'Achraf Hakimi', 'Defensa'),
    ('Marruecos', 3, 'Noussair Mazraoui', 'Defensa'),
    ('Marruecos', 4, 'Sofyan Amrabat', 'Centrocampista'),
    ('Marruecos', 5, 'Nayef Aguerd', 'Defensa'),
    ('Marruecos', 6, 'Romain Saïss', 'Defensa'),
    ('Marruecos', 7, 'Hakim Ziyech', 'Delantero'),
    ('Marruecos', 8, 'Azzedine Ounahi', 'Centrocampista'),
    ('Marruecos', 9, 'Abderrazak Hamdallah', 'Delantero'),
    ('Marruecos', 10, 'Anass Zaroury', 'Delantero'),
    ('Marruecos', 11, 'Abde Ezzalzouli', 'Delantero'),
    ('Marruecos', 12, 'Munir Mohamedi', 'Portero'),
    ('Marruecos', 13, 'Ilias Chair', 'Centrocampista'),
    ('Marruecos', 14, 'Zakaria Aboukhlal', 'Delantero'),
    ('Marruecos', 15, 'Selim Amallah', 'Centrocampista'),
    ('Marruecos', 16, 'Yahia Attiyat Allah', 'Defensa'),
    ('Marruecos', 17, 'Sofiane Boufal', 'Delantero'),
    ('Marruecos', 18, 'Jawad El Yamiq', 'Defensa'),
    ('Marruecos', 19, 'Youssef En-Nesyri', 'Delantero'),
    ('Marruecos', 20, 'Achraf Dari', 'Defensa'),
    ('Marruecos', 21, 'Walid Cheddira', 'Delantero'),
    ('Marruecos', 22, 'Ahmed Reda Tagnaouti', 'Portero'),
    ('Marruecos', 23, 'Bilal El Khannouss', 'Centrocampista'),
    ('Marruecos', 24, 'Badr Benoun', 'Defensa'),
    ('Marruecos', 25, 'Yahya Jabrane', 'Centrocampista'),
    ('Marruecos', 26, 'Brahim Díaz', 'Delantero'),
    ('Ecuador', 1, 'Hernán Galíndez', 'Portero'),
    ('Ecuador', 2, 'Félix Torres', 'Defensa'),
    ('Ecuador', 3, 'Piero Hincapié', 'Defensa'),
    ('Ecuador', 4, 'Joel Ordóñez', 'Defensa'),
    ('Ecuador', 5, 'José Cifuentes', 'Centrocampista'),
    ('Ecuador', 6, 'William Pacho', 'Defensa'),
    ('Ecuador', 7, 'Pervis Estupiñán', 'Defensa'),
    ('Ecuador', 8, 'Carlos Gruezo', 'Centrocampista'),
    ('Ecuador', 9, 'John Yeboah', 'Delantero'),
    ('Ecuador', 10, 'Kendry Páez', 'Centrocampista'),
    ('Ecuador', 11, 'Kevin Rodríguez', 'Delantero'),
    ('Ecuador', 12, 'Moisés Ramírez', 'Portero'),
    ('Ecuador', 13, 'Enner Valencia', 'Delantero'),
    ('Ecuador', 14, 'Alan Minda', 'Delantero'),
    ('Ecuador', 15, 'Ángel Mena', 'Centrocampista'),
    ('Ecuador', 16, 'Jeremy Sarmiento', 'Delantero'),
    ('Ecuador', 17, 'Angelo Preciado', 'Defensa'),
    ('Ecuador', 18, 'Jhojan Julio', 'Delantero'),
    ('Ecuador', 19, 'Jordy Caicedo', 'Delantero'),
    ('Ecuador', 20, 'Alan Franco', 'Centrocampista'),
    ('Ecuador', 21, 'Moisés Caicedo', 'Centrocampista'),
    ('Ecuador', 22, 'Alexander Domínguez', 'Portero'),
    ('Ecuador', 23, 'Jackson Porozo', 'Defensa'),
    ('Ecuador', 24, 'José Hurtado', 'Defensa'),
    ('Ecuador', 25, 'Cristian Ramírez', 'Defensa'),
    ('Ecuador', 26, 'Joao Ortiz', 'Centrocampista'),
    ('Senegal', 1, 'Édouard Mendy', 'Portero'),
    ('Senegal', 2, 'Formose Mendy', 'Defensa'),
    ('Senegal', 3, 'Kalidou Koulibaly', 'Defensa'),
    ('Senegal', 4, 'Abdoulaye Seck', 'Defensa'),
    ('Senegal', 5, 'Idrissa Gueye', 'Centrocampista'),
    ('Senegal', 6, 'Nampalys Mendy', 'Centrocampista'),
    ('Senegal', 7, 'Nicolas Jackson', 'Delantero'),
    ('Senegal', 8, 'Cheikhou Kouyaté', 'Centrocampista'),
    ('Senegal', 9, 'Iliman Ndiaye', 'Delantero'),
    ('Senegal', 10, 'Sadio Mané', 'Delantero'),
    ('Senegal', 11, 'Boulaye Dia', 'Delantero'),
    ('Senegal', 12, 'Fodé Ballo-Touré', 'Defensa'),
    ('Senegal', 13, 'Ismail Jakobs', 'Defensa'),
    ('Senegal', 14, 'Ismaïla Sarr', 'Delantero'),
    ('Senegal', 15, 'Krépin Diatta', 'Centrocampista'),
    ('Senegal', 16, 'Seny Dieng', 'Portero'),
    ('Senegal', 17, 'Pape Matar Sarr', 'Centrocampista'),
    ('Senegal', 18, 'Abdou Diallo', 'Defensa'),
    ('Senegal', 19, 'Moussa Niakhaté', 'Defensa'),
    ('Senegal', 20, 'Habib Diallo', 'Delantero'),
    ('Senegal', 21, 'Lamine Camara', 'Centrocampista'),
    ('Senegal', 22, 'Mory Diaw', 'Portero'),
    ('Senegal', 23, 'Pathé Ciss', 'Centrocampista'),
    ('Senegal', 24, 'Abdallah Sima', 'Delantero'),
    ('Senegal', 25, 'Pape Gueye', 'Centrocampista'),
    ('Senegal', 26, 'Aonadou Diallo', 'Delantero'),
    ('Japón', 1, 'Daiya Maekawa', 'Portero'),
    ('Japón', 2, 'Yukinari Sugawara', 'Defensa'),
    ('Japón', 3, 'Shogo Taniguchi', 'Defensa'),
    ('Japón', 4, 'Ko Itakura', 'Defensa'),
    ('Japón', 5, 'Hidemasa Morita', 'Centrocampista'),
    ('Japón', 6, 'Wataru Endo', 'Centrocampista'),
    ('Japón', 7, 'Kaoru Mitoma', 'Delantero'),
    ('Japón', 8, 'Takumi Minamino', 'Centrocampista'),
    ('Japón', 9, 'Ayase Ueda', 'Delantero'),
    ('Japón', 10, 'Ritsu Doan', 'Delantero'),
    ('Japón', 11, 'Mao Hosoya', 'Delantero'),
    ('Japón', 12, 'Taishi Brandon Nozawa', 'Portero'),
    ('Japón', 13, 'Keito Nakamura', 'Delantero'),
    ('Japón', 14, 'Junya Ito', 'Delantero'),
    ('Japón', 15, 'Koki Machida', 'Defensa'),
    ('Japón', 16, 'Seiya Maikuma', 'Defensa'),
    ('Japón', 17, 'Ao Tanaka', 'Centrocampista'),
    ('Japón', 18, 'Takuma Asano', 'Delantero'),
    ('Japón', 19, 'Yuta Nakayama', 'Defensa'),
    ('Japón', 20, 'Takefusa Kubo', 'Delantero'),
    ('Japón', 21, 'Hiroki Ito', 'Defensa'),
    ('Japón', 22, 'Takehiro Tomiyasu', 'Defensa'),
    ('Japón', 23, 'Zion Suzuki', 'Portero'),
    ('Japón', 24, 'Tsuyoshi Ogashiwa', 'Delantero'),
    ('Japón', 25, 'Daizen Maeda', 'Delantero'),
    ('Japón', 26, 'Reo Hatate', 'Centrocampista'),
    ('Suiza', 1, 'Yann Sommer', 'Portero'),
    ('Suiza', 2, 'Leonidas Stergiou', 'Defensa'),
    ('Suiza', 3, 'Silvan Widmer', 'Defensa'),
    ('Suiza', 4, 'Nico Elvedi', 'Defensa'),
    ('Suiza', 5, 'Manuel Akanji', 'Defensa'),
    ('Suiza', 6, 'Denis Zakaria', 'Centrocampista'),
    ('Suiza', 7, 'Breel Embolo', 'Delantero'),
    ('Suiza', 8, 'Remo Freuler', 'Centrocampista'),
    ('Suiza', 9, 'Noah Okafor', 'Delantero'),
    ('Suiza', 10, 'Granit Xhaka', 'Centrocampista'),
    ('Suiza', 11, 'Renato Steffen', 'Delantero'),
    ('Suiza', 12, 'Yvon Mvogo', 'Portero'),
    ('Suiza', 13, 'Ricardo Rodríguez', 'Defensa'),
    ('Suiza', 14, 'Steven Zuber', 'Centrocampista'),
    ('Suiza', 15, 'Cédric Zesiger', 'Defensa'),
    ('Suiza', 16, 'Vincent Sierro', 'Centrocampista'),
    ('Suiza', 17, 'Ruben Vargas', 'Delantero'),
    ('Suiza', 18, 'Duah Kwadwo', 'Delantero'),
    ('Suiza', 19, 'Dan Ndoye', 'Delantero'),
    ('Suiza', 20, 'Michel Aebischer', 'Centrocampista'),
    ('Suiza', 21, 'Ulysses Garcia', 'Defensa'),
    ('Suiza', 22, 'Fabian Schär', 'Defensa'),
    ('Suiza', 23, 'Xherdan Shaqiri', 'Centrocampista'),
    ('Suiza', 24, 'Gregor Kobel', 'Portero'),
    ('Suiza', 25, 'Zeki Amdouni', 'Delantero'),
    ('Suiza', 26, 'Ardon Jashari', 'Centrocampista'),
    ('Chile', 1, 'Claudio Bravo', 'Portero'),
    ('Chile', 2, 'Gabriel Suazo', 'Defensa'),
    ('Chile', 3, 'Guillermo Maripán', 'Defensa'),
    ('Chile', 4, 'Mauricio Isla', 'Defensa'),
    ('Chile', 5, 'Paulo Díaz', 'Defensa'),
    ('Chile', 6, 'Thomas Galdames', 'Defensa'),
    ('Chile', 7, 'Marcelino Núñez', 'Centrocampista'),
    ('Chile', 8, 'Erick Pulgar', 'Centrocampista'),
    ('Chile', 9, 'Alexis Sánchez', 'Delantero'),
    ('Chile', 10, 'Diego Valdés', 'Centrocampista'),
    ('Chile', 11, 'Eduardo Vargas', 'Delantero'),
    ('Chile', 12, 'Gabriel Arias', 'Portero'),
    ('Chile', 13, 'Igor Lichnovsky', 'Defensa'),
    ('Chile', 14, 'Rodrigo Echeverría', 'Centrocampista'),
    ('Chile', 15, 'Diego Osorio', 'Delantero'),
    ('Chile', 16, 'Benjamin Kuscevic', 'Defensa'),
    ('Chile', 17, 'Ben Brereton Díaz', 'Delantero'),
    ('Chile', 18, 'Victor Dávila', 'Delantero'),
    ('Chile', 19, 'Marcos Bolados', 'Delantero'),
    ('Chile', 20, 'Maximiliano Guerrero', 'Delantero'),
    ('Chile', 21, 'Matías Catalán', 'Defensa'),
    ('Chile', 22, 'Brayan Cortés', 'Portero'),
    ('Chile', 23, 'Cesar Pérez', 'Centrocampista'),
    ('Chile', 24, 'Esteban Pavez', 'Centrocampista'),
    ('Chile', 25, 'Nicolas Fernández', 'Defensa'),
    ('Chile', 26, 'Alexander Aravena', 'Delantero'),
    ('Ucrania', 1, 'Heorhiy Bushchan', 'Portero'),
    ('Ucrania', 2, 'Yukhym Konoplya', 'Defensa'),
    ('Ucrania', 3, 'Oleksandr Svatok', 'Defensa'),
    ('Ucrania', 4, 'Maksym Talovyerov', 'Defensa'),
    ('Ucrania', 5, 'Serhiy Sydorchuk', 'Centrocampista'),
    ('Ucrania', 6, 'Taras Stepanenko', 'Centrocampista'),
    ('Ucrania', 7, 'Andriy Yarmolenko', 'Delantero'),
    ('Ucrania', 8, 'Ruslan Malinovskyi', 'Centrocampista'),
    ('Ucrania', 9, 'Roman Yaremchuk', 'Delantero'),
    ('Ucrania', 10, 'Mykhailo Mudryk', 'Delantero'),
    ('Ucrania', 11, 'Artem Dovbyk', 'Delantero'),
    ('Ucrania', 12, 'Anatoliy Trubin', 'Portero'),
    ('Ucrania', 13, 'Illia Zabarnyi', 'Defensa'),
    ('Ucrania', 14, 'Heorhiy Sudakov', 'Centrocampista'),
    ('Ucrania', 15, 'Viktor Tsyhankov', 'Delantero'),
    ('Ucrania', 16, 'Vitaliy Mykolenko', 'Defensa'),
    ('Ucrania', 17, 'Oleksandr Zinchenko', 'Defensa'),
    ('Ucrania', 18, 'Volodymyr Brazhko', 'Centrocampista'),
    ('Ucrania', 19, 'Mykola Shaparenko', 'Centrocampista'),
    ('Ucrania', 20, 'Oleksandr Zubkov', 'Delantero'),
    ('Ucrania', 21, 'Valeriy Bondar', 'Defensa'),
    ('Ucrania', 22, 'Mykola Matviyenko', 'Defensa'),
    ('Ucrania', 23, 'Andriy Lunin', 'Portero'),
    ('Ucrania', 24, 'Oleksandr Tymchyk', 'Defensa'),
    ('Ucrania', 25, 'Vladyslav Vanat', 'Delantero'),
    ('Ucrania', 26, 'Bogdan Mykhaylichenko', 'Defensa'),
    ('Egipto', 1, 'Mohamed El Shenawy', 'Portero'),
    ('Egipto', 2, 'Ali Gabr', 'Defensa'),
    ('Egipto', 3, 'Mohamed Hany', 'Defensa'),
    ('Egipto', 4, 'Omar Kamal', 'Defensa'),
    ('Egipto', 5, 'Hamdi Fathi', 'Centrocampista'),
    ('Egipto', 6, 'Ahmed Hegazi', 'Defensa'),
    ('Egipto', 7, 'Trézéguet', 'Delantero'),
    ('Egipto', 8, 'Emam Ashour', 'Centrocampista'),
    ('Egipto', 9, 'Mohamed Sherif', 'Delantero'),
    ('Egipto', 10, 'Mohamed Salah', 'Delantero'),
    ('Egipto', 11, 'Mostafa Mohamed', 'Delantero'),
    ('Egipto', 12, 'Mohamed Abou Gabal', 'Portero'),
    ('Egipto', 13, 'Ahmed Abou El Fotouh', 'Defensa'),
    ('Egipto', 14, 'Marwan Attia', 'Centrocampista'),
    ('Egipto', 15, 'Yasser Ibrahim', 'Defensa'),
    ('Egipto', 16, 'Mostafa Fathi', 'Delantero'),
    ('Egipto', 17, 'Mohamed Elneny', 'Centrocampista'),
    ('Egipto', 18, 'Mohamed Abdelmonem', 'Defensa'),
    ('Egipto', 19, 'Mahmoud Kahraba', 'Delantero'),
    ('Egipto', 20, 'Tarek Hamed', 'Centrocampista'),
    ('Egipto', 21, 'Zizo', 'Centrocampista'),
    ('Egipto', 22, 'Ahmed El Shenawy', 'Portero'),
    ('Egipto', 23, 'Ahmed Hassan Kouka', 'Delantero'),
    ('Egipto', 24, 'Mahmoud Hamdy', 'Defensa'),
    ('Egipto', 25, 'Mohamed Hamdy', 'Defensa'),
    ('Egipto', 26, 'Sam Morsy', 'Centrocampista'),
    ('Arabia Saudita', 1, 'Mohammed Al-Rubaie', 'Portero'),
    ('Arabia Saudita', 2, 'Sultan Al-Ghannam', 'Defensa'),
    ('Arabia Saudita', 3, 'Awn Al-Saluli', 'Defensa'),
    ('Arabia Saudita', 4, 'Ali Lajami', 'Defensa'),
    ('Arabia Saudita', 5, 'Ali Al-Bulaihi', 'Defensa'),
    ('Arabia Saudita', 6, 'Mohammed Al-Breik', 'Defensa'),
    ('Arabia Saudita', 7, 'Mukhtar Ali', 'Centrocampista'),
    ('Arabia Saudita', 8, 'Abdulelah Al-Malki', 'Centrocampista'),
    ('Arabia Saudita', 9, 'Firas Al-Buraikan', 'Delantero'),
    ('Arabia Saudita', 10, 'Salem Al-Dawsari', 'Delantero'),
    ('Arabia Saudita', 11, 'Saleh Al-Shehri', 'Delantero'),
    ('Arabia Saudita', 12, 'Saud Abdulhamid', 'Defensa'),
    ('Arabia Saudita', 13, 'Yasser Al-Shahrani', 'Defensa'),
    ('Arabia Saudita', 14, 'Abdullah Al-Khaibari', 'Centrocampista'),
    ('Arabia Saudita', 15, 'Talal Haji', 'Delantero'),
    ('Arabia Saudita', 16, 'Sami Al-Najei', 'Centrocampista'),
    ('Arabia Saudita', 17, 'Hassan Tambakti', 'Defensa'),
    ('Arabia Saudita', 18, 'Abdulrahman Ghareeb', 'Delantero'),
    ('Arabia Saudita', 19, 'Fahad Al-Muwallad', 'Delantero'),
    ('Arabia Saudita', 20, 'Faisal Al-Ghamdi', 'Centrocampista'),
    ('Arabia Saudita', 21, 'Mohammed Kanno', 'Centrocampista'),
    ('Arabia Saudita', 22, 'Ahmed Al-Kassar', 'Portero'),
    ('Arabia Saudita', 23, 'Mohammed Al-Owais', 'Portero'),
    ('Arabia Saudita', 24, 'Nasser Al-Dawsari', 'Centrocampista'),
    ('Arabia Saudita', 25, 'Hassan Kadesh', 'Defensa'),
    ('Arabia Saudita', 26, 'Abdulelah Al-Amri', 'Defensa'),
    ('Perú', 1, 'Pedro Gallese', 'Portero'),
    ('Perú', 2, 'Luis Advíncula', 'Defensa'),
    ('Perú', 3, 'Aldo Corzo', 'Defensa'),
    ('Perú', 4, 'Alexander Callens', 'Defensa'),
    ('Perú', 5, 'Carlos Zambrano', 'Defensa'),
    ('Perú', 6, 'Marcos López', 'Defensa'),
    ('Perú', 7, 'Andy Polo', 'Centrocampista'),
    ('Perú', 8, 'Sergio Peña', 'Centrocampista'),
    ('Perú', 9, 'Gianluca Lapadula', 'Delantero'),
    ('Perú', 10, 'Christian Cueva', 'Centrocampista'),
    ('Perú', 11, 'Bryan Reyna', 'Delantero'),
    ('Perú', 12, 'Carlos Cáceda', 'Portero'),
    ('Perú', 13, 'Luis Abram', 'Defensa'),
    ('Perú', 14, 'Wilder Cartagena', 'Centrocampista'),
    ('Perú', 15, 'Jesus Castillo', 'Centrocampista'),
    ('Perú', 16, 'Renato Tapia', 'Centrocampista'),
    ('Perú', 17, 'Luis Iberico', 'Delantero'),
    ('Perú', 18, 'André Carrillo', 'Delantero'),
    ('Perú', 19, 'Edison Flores', 'Delantero'),
    ('Perú', 20, 'Oliver Sonne', 'Defensa'),
    ('Perú', 21, 'Diego Romero', 'Portero'),
    ('Perú', 22, 'Alexander Succar', 'Delantero'),
    ('Perú', 23, 'Piero Quispe', 'Centrocampista'),
    ('Perú', 24, 'Miguel Araujo', 'Defensa'),
    ('Perú', 25, 'Anderson Santamaría', 'Defensa'),
    ('Perú', 26, 'Paolo Guerrero', 'Delantero'),
    ('Austria', 1, 'Heinz Lindner', 'Portero'),
    ('Austria', 2, 'Maximilian Wöber', 'Defensa'),
    ('Austria', 3, 'Gernot Trauner', 'Defensa'),
    ('Austria', 4, 'Kevin Danso', 'Defensa'),
    ('Austria', 5, 'Stefan Posch', 'Defensa'),
    ('Austria', 6, 'Nicolas Seiwald', 'Centrocampista'),
    ('Austria', 7, 'Marko Arnautović', 'Delantero'),
    ('Austria', 8, 'Alexander Prass', 'Centrocampista'),
    ('Austria', 9, 'Marcel Sabitzer', 'Centrocampista'),
    ('Austria', 10, 'Andreas Weimann', 'Delantero'),
    ('Austria', 11, 'Michael Gregoritsch', 'Delantero'),
    ('Austria', 12, 'Niklas Hedl', 'Portero'),
    ('Austria', 13, 'Patrick Pentz', 'Portero'),
    ('Austria', 14, 'Leopold Querfeld', 'Defensa'),
    ('Austria', 15, 'Philipp Lienhart', 'Defensa'),
    ('Austria', 16, 'Phillipp Mwene', 'Defensa'),
    ('Austria', 17, 'Florian Kainz', 'Centrocampista'),
    ('Austria', 18, 'Romano Schmid', 'Centrocampista'),
    ('Austria', 19, 'Christoph Baumgartner', 'Centrocampista'),
    ('Austria', 20, 'Konrad Laimer', 'Centrocampista'),
    ('Austria', 21, 'Flavius Daniliuc', 'Defensa'),
    ('Austria', 22, 'Matthias Seidl', 'Centrocampista'),
    ('Austria', 23, 'Patrick Wimmer', 'Delantero'),
    ('Austria', 24, 'Marco Grüll', 'Delantero'),
    ('Austria', 25, 'Maximilian Entrup', 'Delantero'),
    ('Austria', 26, 'Thierno Ballo', 'Centrocampista'),
    ('Turquía', 1, 'Mert Günok', 'Portero'),
    ('Turquía', 2, 'Zeki Çelik', 'Defensa'),
    ('Turquía', 3, 'Merih Demiral', 'Defensa'),
    ('Turquía', 4, 'Samet Akaydin', 'Defensa'),
    ('Turquía', 5, 'Okay Yokuşlu', 'Centrocampista'),
    ('Turquía', 6, 'Orkun Kökçü', 'Centrocampista'),
    ('Turquía', 7, 'Kerem Aktürkoğlu', 'Delantero'),
    ('Turquía', 8, 'Arda Güler', 'Centrocampista'),
    ('Turquía', 9, 'Cenk Tosun', 'Delantero'),
    ('Turquía', 10, 'Hakan Çalhanoğlu', 'Centrocampista'),
    ('Turquía', 11, 'Yusuf Yazıcı', 'Delantero'),
    ('Turquía', 12, 'Altay Bayındır', 'Portero'),
    ('Turquía', 13, 'Ahmetcan Kaplan', 'Defensa'),
    ('Turquía', 14, 'Abdülkerim Bardakcı', 'Defensa'),
    ('Turquía', 15, 'Salih Özcan', 'Centrocampista'),
    ('Turquía', 16, 'Ismail Yüksek', 'Centrocampista'),
    ('Turquía', 17, 'İrfan Can Kahveci', 'Centrocampista'),
    ('Turquía', 18, 'Mert Müldür', 'Defensa'),
    ('Turquía', 19, 'Kenan Yıldız', 'Delantero'),
    ('Turquía', 20, 'Ferdi Kadıoğlu', 'Defensa'),
    ('Turquía', 21, 'Barış Alper Yılmaz', 'Delantero'),
    ('Turquía', 22, 'Kaan Ayhan', 'Defensa'),
    ('Turquía', 23, 'Uğurcan Çakır', 'Portero'),
    ('Turquía', 24, 'Semih Kılıçsoy', 'Delantero'),
    ('Turquía', 25, 'Yunis Akgün', 'Delantero'),
    ('Turquía', 26, 'Bertuğ Yıldırım', 'Delantero'),
    ('Túnez', 1, 'Aymen Dahmen', 'Portero'),
    ('Túnez', 2, 'Ali Abdi', 'Defensa'),
    ('Túnez', 3, 'Montassar Talbi', 'Defensa'),
    ('Túnez', 4, 'Yassine Meriah', 'Defensa'),
    ('Túnez', 5, 'Nader Ghandri', 'Defensa'),
    ('Túnez', 6, 'Houssem Tka', 'Centrocampista'),
    ('Túnez', 7, 'Youssef Msakni', 'Delantero'),
    ('Túnez', 8, 'Hamza Rafia', 'Centrocampista'),
    ('Túnez', 9, 'Haythem Jouini', 'Delantero'),
    ('Túnez', 10, 'Hannibal Mejbri', 'Centrocampista'),
    ('Túnez', 11, 'Taha Yassine Khenissi', 'Delantero'),
    ('Túnez', 12, 'Ali Maâloul', 'Defensa'),
    ('Túnez', 13, 'Hamza Jelassi', 'Defensa'),
    ('Túnez', 14, 'Aissa Laïdouni', 'Centrocampista'),
    ('Túnez', 15, 'Ben Romdhane', 'Centrocampista'),
    ('Túnez', 16, 'Bechir Ben Saïd', 'Portero'),
    ('Túnez', 17, 'Ellyes Skhiri', 'Centrocampista'),
    ('Túnez', 18, 'Sayfallah Ltaief', 'Delantero'),
    ('Túnez', 19, 'Bassem Srarfi', 'Delantero'),
    ('Túnez', 20, 'Yan Valery', 'Defensa'),
    ('Túnez', 21, 'Wajdi Kechrida', 'Defensa'),
    ('Túnez', 22, 'Mouez Hassen', 'Portero'),
    ('Túnez', 23, 'Naïm Sliti', 'Delantero'),
    ('Túnez', 24, 'Seifeddine Jaziri', 'Delantero'),
    ('Túnez', 25, 'Anis Ben Slimane', 'Centrocampista'),
    ('Túnez', 26, 'Elias Achouri', 'Delantero'),
    ('Noruega', 1, 'Ørjan Nyland', 'Portero'),
    ('Noruega', 2, 'Julian Ryerson', 'Defensa'),
    ('Noruega', 3, 'Kristoffer Ajer', 'Defensa'),
    ('Noruega', 4, 'Leo Østigård', 'Defensa'),
    ('Noruega', 5, 'David Møller Wolfe', 'Defensa'),
    ('Noruega', 6, 'Patrick Berg', 'Centrocampista'),
    ('Noruega', 7, 'Alexander Sørloth', 'Delantero'),
    ('Noruega', 8, 'Sander Berge', 'Centrocampista'),
    ('Noruega', 9, 'Erling Haaland', 'Delantero'),
    ('Noruega', 10, 'Martin Ødegaard', 'Centrocampista'),
    ('Noruega', 11, 'Mohamed Elyounoussi', 'Delantero'),
    ('Noruega', 12, 'Matias Dyngeland', 'Portero'),
    ('Noruega', 13, 'Andreas Hanche-Olsen', 'Defensa'),
    ('Noruega', 14, 'Marcus Holmgren Pedersen', 'Defensa'),
    ('Noruega', 15, 'Mortiz Thorsby', 'Centrocampista'),
    ('Noruega', 16, 'Hugo Vetlesen', 'Centrocampista'),
    ('Noruega', 17, 'Kristian Thorstvedt', 'Centrocampista'),
    ('Noruega', 18, 'Fredrik Aursnes', 'Centrocampista'),
    ('Noruega', 19, 'Jørgen Strand Larsen', 'Delantero'),
    ('Noruega', 20, 'Antonio Nusa', 'Delantero'),
    ('Noruega', 21, 'Oscar Bobb', 'Delantero'),
    ('Noruega', 22, 'Egil Selvik', 'Portero'),
    ('Noruega', 23, 'Aron Dønnum', 'Delantero'),
    ('Noruega', 24, 'Jesper Daland', 'Defensa'),
    ('Noruega', 25, 'Osame Sahraoui', 'Delantero'),
    ('Noruega', 26, 'Kristoffer Velde', 'Centrocampista'),
    ('Paraguay', 1, 'Carlos Coronel', 'Portero'),
    ('Paraguay', 2, 'Robert Rojas', 'Defensa'),
    ('Paraguay', 3, 'Omar Alderete', 'Defensa'),
    ('Paraguay', 4, 'Matías Espinoza', 'Defensa'),
    ('Paraguay', 5, 'Fabián Balbuena', 'Defensa'),
    ('Paraguay', 6, 'Junior Alonso', 'Defensa'),
    ('Paraguay', 7, 'Derlis González', 'Delantero'),
    ('Paraguay', 8, 'Andrés Cubas', 'Centrocampista'),
    ('Paraguay', 9, 'Adam Bareiro', 'Delantero'),
    ('Paraguay', 10, 'Miguel Almirón', 'Delantero'),
    ('Paraguay', 11, 'Ángel Romero', 'Delantero'),
    ('Paraguay', 12, 'Alfredo Aguilar', 'Portero'),
    ('Paraguay', 13, 'Gustavo Gómez', 'Defensa'),
    ('Paraguay', 14, 'Adrian Cubas', 'Centrocampista'),
    ('Paraguay', 15, 'Gustavo Velázquez', 'Defensa'),
    ('Paraguay', 16, 'Mathías Villasanti', 'Centrocampista'),
    ('Paraguay', 17, 'Alejandro Romero Gamarra', 'Centrocampista'),
    ('Paraguay', 18, 'Alex Arce', 'Delantero'),
    ('Paraguay', 19, 'Julio Enciso', 'Delantero'),
    ('Paraguay', 20, 'Richard Sánchez', 'Centrocampista'),
    ('Paraguay', 21, 'Ramón Sosa', 'Delantero'),
    ('Paraguay', 22, 'Rodrigo Morínigo', 'Portero'),
    ('Paraguay', 23, 'Iván Ramírez', 'Defensa'),
    ('Paraguay', 24, 'Damián Bobadilla', 'Centrocampista'),
    ('Paraguay', 25, 'Hernesto Caballero', 'Centrocampista'),
    ('Paraguay', 26, 'Fabrizio Peralta', 'Centrocampista'),
    ('Catar', 1, 'Saad Al-Sheeb', 'Portero'),
    ('Catar', 2, 'Ró-Ró', 'Defensa'),
    ('Catar', 3, 'Al-Mahdi Ali Mukhtar', 'Defensa'),
    ('Catar', 4, 'Mohammed Waad', 'Centrocampista'),
    ('Catar', 5, 'Tarek Salman', 'Defensa'),
    ('Catar', 6, 'Abdulaziz Hatem', 'Centrocampista'),
    ('Catar', 7, 'Ahmed Alaaeldin', 'Delantero'),
    ('Catar', 8, 'Ali Assadalla', 'Centrocampista'),
    ('Catar', 9, 'Mohammed Muntari', 'Delantero'),
    ('Catar', 10, 'Hassan Al-Haydos', 'Delantero'),
    ('Catar', 11, 'Akram Afif', 'Delantero'),
    ('Catar', 12, 'Lucas Mendes', 'Defensa'),
    ('Catar', 13, 'Musab Kheder', 'Defensa'),
    ('Catar', 14, 'Homam Ahmed', 'Defensa'),
    ('Catar', 15, 'Bassam Al-Rawi', 'Defensa'),
    ('Catar', 16, 'Boualem Khoukhi', 'Defensa'),
    ('Catar', 17, 'Ismaeel Mohammad', 'Delantero'),
    ('Catar', 18, 'Sultan Al-Brake', 'Defensa'),
    ('Catar', 19, 'Almoez Ali', 'Delantero'),
    ('Catar', 20, 'Ahmed Fathy', 'Centrocampista'),
    ('Catar', 21, 'Salah Zakaria', 'Portero'),
    ('Catar', 22, 'Meshaal Barsham', 'Portero'),
    ('Catar', 23, 'Assim Madibo', 'Centrocampista'),
    ('Catar', 24, 'Jassem Gaber', 'Defensa'),
    ('Catar', 25, 'Mostafa Meshaal', 'Centrocampista'),
    ('Catar', 26, 'Khaled Mohammed', 'Centrocampista'),
    ('Bosnia y Herzegovina', 1, 'Nikola Vasilj', 'Portero'),
    ('Bosnia y Herzegovina', 2, 'Amar Dedić', 'Defensa'),
    ('Bosnia y Herzegovina', 3, 'Sead Kolašinac', 'Defensa'),
    ('Bosnia y Herzegovina', 4, 'Dennis Hadžikadunić', 'Defensa'),
    ('Bosnia y Herzegovina', 5, 'Nihad Mujakić', 'Defensa'),
    ('Bosnia y Herzegovina', 6, 'Ivan Šunjić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 7, 'Esmir Bajraktarević', 'Centrocampista'),
    ('Bosnia y Herzegovina', 8, 'Amir Hadžiahmetović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 9, 'Ermedin Demirović', 'Delantero'),
    ('Bosnia y Herzegovina', 10, 'Edin Džeko', 'Delantero'),
    ('Bosnia y Herzegovina', 11, 'Haris Tabaković', 'Delantero'),
    ('Bosnia y Herzegovina', 12, 'Martin Zlomislić', 'Portero'),
    ('Bosnia y Herzegovina', 13, 'Stjepan Radeljić', 'Defensa'),
    ('Bosnia y Herzegovina', 14, 'Nikola Katić', 'Defensa'),
    ('Bosnia y Herzegovina', 15, 'Tarik Muharemović', 'Defensa'),
    ('Bosnia y Herzegovina', 16, 'Benjamin Tahirović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 17, 'Armin Gigović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 18, 'Dženis Burnić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 19, 'Ivan Bašić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 20, 'Amar Memić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 21, 'Nidal Čelik', 'Defensa'),
    ('Bosnia y Herzegovina', 22, 'Osman Hadžikić', 'Portero'),
    ('Bosnia y Herzegovina', 23, 'Kerim Alajbegović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 24, 'Ermin Mahmić', 'Defensa'),
    ('Bosnia y Herzegovina', 25, 'Samed Baždar', 'Delantero'),
    ('Bosnia y Herzegovina', 26, 'Jovo Lukić', 'Delantero'),
    ('Panamá', 1, 'Luis Mejía', 'Portero'),
    ('Panamá', 2, 'César Blackman', 'Defensa'),
    ('Panamá', 3, 'José Córdoba', 'Defensa'),
    ('Panamá', 4, 'Eduardo Anderson', 'Defensa'),
    ('Panamá', 5, 'Abdiel Ayarza', 'Centrocampista'),
    ('Panamá', 6, 'Cristian Martínez', 'Centrocampista'),
    ('Panamá', 7, 'José Luis Rodríguez', 'Delantero'),
    ('Panamá', 8, 'Adalberto Carrasquilla', 'Centrocampista'),
    ('Panamá', 9, 'Eduardo Guerrero', 'Delantero'),
    ('Panamá', 10, 'Édgar Yoel Bárcenas', 'Delantero'),
    ('Panamá', 11, 'Ismael Díaz', 'Delantero'),
    ('Panamá', 12, 'César Samudio', 'Portero'),
    ('Panamá', 13, 'Fidel Escobar', 'Defensa'),
    ('Panamá', 14, 'Jovani Welch', 'Centrocampista'),
    ('Panamá', 15, 'Eric Davis', 'Defensa'),
    ('Panamá', 16, 'Andrés Andrade', 'Defensa'),
    ('Panamá', 17, 'José Fajardo', 'Delantero'),
    ('Panamá', 18, 'Michael Amir Murillo', 'Defensa'),
    ('Panamá', 19, 'Alberto Quintero', 'Delantero'),
    ('Panamá', 20, 'Aníbal Godoy', 'Centrocampista'),
    ('Panamá', 21, 'César Yanis', 'Delantero'),
    ('Panamá', 22, 'Orlando Mosquera', 'Portero'),
    ('Panamá', 23, 'Kahiser Lenis', 'Delantero'),
    ('Panamá', 24, 'Edgardo Fariña', 'Defensa'),
    ('Panamá', 25, 'Martin Morán', 'Centrocampista'),
    ('Panamá', 26, 'Carlos Harvey', 'Defensa'),
    ('Costa de Marfil', 1, 'Yahia Fofana', 'Portero'),
    ('Costa de Marfil', 2, 'Ousmane Diomande', 'Defensa'),
    ('Costa de Marfil', 3, 'Ghislain Konan', 'Defensa'),
    ('Costa de Marfil', 4, 'Jean Seri', 'Centrocampista'),
    ('Costa de Marfil', 5, 'Wilfried Singo', 'Defensa'),
    ('Costa de Marfil', 6, 'Seko Fofana', 'Centrocampista'),
    ('Costa de Marfil', 7, 'Odilon Kossounou', 'Defensa'),
    ('Costa de Marfil', 8, 'Franck Kessié', 'Centrocampista'),
    ('Costa de Marfil', 9, 'Jonathan Bamba', 'Delantero'),
    ('Costa de Marfil', 10, 'Karim Konaté', 'Delantero'),
    ('Costa de Marfil', 11, 'Jean-Philippe Krasso', 'Delantero'),
    ('Costa de Marfil', 12, 'Badra Ali Sangaré', 'Portero'),
    ('Costa de Marfil', 13, 'Jeremie Boga', 'Delantero'),
    ('Costa de Marfil', 14, 'Oumar Diakité', 'Delantero'),
    ('Costa de Marfil', 15, 'Max Gradel', 'Delantero'),
    ('Costa de Marfil', 16, 'Charles Folly', 'Portero'),
    ('Costa de Marfil', 17, 'Serge Aurier', 'Defensa'),
    ('Costa de Marfil', 18, 'Ibrahim Sangaré', 'Centrocampista'),
    ('Costa de Marfil', 19, 'Nicolas Pépé', 'Delantero'),
    ('Costa de Marfil', 20, 'Christian Kouamé', 'Delantero'),
    ('Costa de Marfil', 21, 'Evan Ndicka', 'Defensa'),
    ('Costa de Marfil', 22, 'Sebastien Haller', 'Delantero'),
    ('Costa de Marfil', 23, 'Simon Adingra', 'Delantero'),
    ('Costa de Marfil', 24, 'Willy Boly', 'Defensa'),
    ('Costa de Marfil', 25, 'Lazare Amani', 'Centrocampista'),
    ('Costa de Marfil', 26, 'Ismaël Diallo', 'Defensa'),
    ('Escocia', 1, 'Angus Gunn', 'Portero'),
    ('Escocia', 2, 'Anthony Ralston', 'Defensa'),
    ('Escocia', 3, 'Andrew Robertson', 'Defensa'),
    ('Escocia', 4, 'Scott McTominay', 'Centrocampista'),
    ('Escocia', 5, 'Grant Hanley', 'Defensa'),
    ('Escocia', 6, 'John McGinn', 'Centrocampista'),
    ('Escocia', 7, 'John Souttar', 'Defensa'),
    ('Escocia', 8, 'Billy Gilmour', 'Centrocampista'),
    ('Escocia', 9, 'Lawrence Shankland', 'Delantero'),
    ('Escocia', 10, 'Che Adams', 'Delantero'),
    ('Escocia', 11, 'Ryan Christie', 'Centrocampista'),
    ('Escocia', 12, 'Liam Kelly', 'Portero'),
    ('Escocia', 13, 'Jack Hendry', 'Defensa'),
    ('Escocia', 14, 'Ryan Porteous', 'Defensa'),
    ('Escocia', 15, 'Liam Cooper', 'Defensa'),
    ('Escocia', 16, 'Kenny McLean', 'Centrocampista'),
    ('Escocia', 17, 'Stuart Armstrong', 'Centrocampista'),
    ('Escocia', 18, 'Lewis Morgan', 'Delantero'),
    ('Escocia', 19, 'Tommy Conway', 'Delantero'),
    ('Escocia', 20, 'Ryan Jack', 'Centrocampista'),
    ('Escocia', 21, 'Zander Clark', 'Portero'),
    ('Escocia', 22, 'Greg Taylor', 'Defensa'),
    ('Escocia', 23, 'James Forrest', 'Delantero'),
    ('Escocia', 24, 'Callum McGregor', 'Centrocampista'),
    ('Escocia', 25, 'Ross McCrorie', 'Defensa'),
    ('Escocia', 26, 'Scott McKenna', 'Defensa'),
    ('Irán', 1, 'Alireza Beiranvand', 'Portero'),
    ('Irán', 2, 'Sadegh Moharrami', 'Defensa'),
    ('Irán', 3, 'Ehsan Hajsafi', 'Defensa'),
    ('Irán', 4, 'Shojae Khalilzadeh', 'Defensa'),
    ('Irán', 5, 'Milad Mohammadi', 'Defensa'),
    ('Irán', 6, 'Saeid Ezatolahi', 'Centrocampista'),
    ('Irán', 7, 'Alireza Jahanbakhsh', 'Delantero'),
    ('Irán', 8, 'Morteza Pouraliganji', 'Defensa'),
    ('Irán', 9, 'Mehdi Taremi', 'Delantero'),
    ('Irán', 10, 'Karim Ansarifard', 'Delantero'),
    ('Irán', 11, 'Vahid Amiri', 'Centrocampista'),
    ('Irán', 12, 'Payam Niazmand', 'Portero'),
    ('Irán', 13, 'Hossein Kanaanizadegan', 'Defensa'),
    ('Irán', 14, 'Saman Ghoddos', 'Centrocampista'),
    ('Irán', 15, 'Rouzbeh Cheshmi', 'Centrocampista'),
    ('Irán', 16, 'Mehdi Torabi', 'Delantero'),
    ('Irán', 17, 'Ali Gholizadeh', 'Delantero'),
    ('Irán', 18, 'Karim Karimi', 'Centrocampista'),
    ('Irán', 19, 'Majid Hosseini', 'Defensa'),
    ('Irán', 20, 'Sardar Azmoun', 'Delantero'),
    ('Irán', 21, 'Mohebi Mohammad', 'Delantero'),
    ('Irán', 22, 'Hossein Hosseini', 'Portero'),
    ('Irán', 23, 'Ramin Rezaeian', 'Defensa'),
    ('Irán', 24, 'Aria Yousefi', 'Defensa'),
    ('Irán', 25, 'Mohammad Ghorbani', 'Centrocampista'),
    ('Irán', 26, 'Shahriyar Moghanlou', 'Delantero'),
    ('Gales', 1, 'Danny Ward', 'Portero'),
    ('Gales', 2, 'Neco Williams', 'Defensa'),
    ('Gales', 3, 'Ben Davies', 'Defensa'),
    ('Gales', 4, 'Chris Mepham', 'Defensa'),
    ('Gales', 5, 'Joe Rodon', 'Defensa'),
    ('Gales', 6, 'Ethan Ampadu', 'Centrocampista'),
    ('Gales', 7, 'David Brooks', 'Delantero'),
    ('Gales', 8, 'Harry Wilson', 'Centrocampista'),
    ('Gales', 9, 'Brennan Johnson', 'Delantero'),
    ('Gales', 10, 'Aaron Ramsey', 'Centrocampista'),
    ('Gales', 11, 'Daniel James', 'Delantero'),
    ('Gales', 12, 'Adam Davies', 'Portero'),
    ('Gales', 13, 'Connor Roberts', 'Defensa'),
    ('Gales', 14, 'Sorba Thomas', 'Delantero'),
    ('Gales', 15, 'Jordan James', 'Centrocampista'),
    ('Gales', 16, 'Charlie Savage', 'Centrocampista'),
    ('Gales', 17, 'Kieffer Moore', 'Delantero'),
    ('Gales', 18, 'Nathan Broadhead', 'Delantero'),
    ('Gales', 19, 'Wes Burns', 'Delantero'),
    ('Gales', 20, 'Ben Cabango', 'Defensa'),
    ('Gales', 21, 'Jay Dasilva', 'Defensa'),
    ('Gales', 22, 'Tom King', 'Portero'),
    ('Gales', 23, 'Rubin Colwill', 'Centrocampista'),
    ('Gales', 24, 'Rabbi Matondo', 'Delantero'),
    ('Gales', 25, 'Josh Sheehan', 'Centrocampista'),
    ('Gales', 26, 'Liam Cullen', 'Delantero'),
    ('Jamaica', 1, 'Andre Blake', 'Portero'),
    ('Jamaica', 2, 'Dexter Lembikisa', 'Defensa'),
    ('Jamaica', 3, 'Amari\'i Bell', 'Defensa'),
    ('Jamaica', 4, 'Richard King', 'Defensa'),
    ('Jamaica', 5, 'Ethan Pinnock', 'Defensa'),
    ('Jamaica', 6, 'Di\'Shon Bernard', 'Defensa'),
    ('Jamaica', 7, 'Leon Bailey', 'Delantero'),
    ('Jamaica', 8, 'Bobby Decordova-Reid', 'Centrocampista'),
    ('Jamaica', 9, 'Michail Antonio', 'Delantero'),
    ('Jamaica', 10, 'Shamar Nicholson', 'Delantero'),
    ('Jamaica', 11, 'Demarai Gray', 'Delantero'),
    ('Jamaica', 12, 'Jahmali Waite', 'Portero'),
    ('Jamaica', 13, 'Damion Lowe', 'Defensa'),
    ('Jamaica', 14, 'Kasey Palmer', 'Centrocampista'),
    ('Jamaica', 15, 'Joel Latibeaudiere', 'Defensa'),
    ('Jamaica', 16, 'Karoy Anderson', 'Centrocampista'),
    ('Jamaica', 17, 'Coniah Boyce-Clarke', 'Portero'),
    ('Jamaica', 18, 'Renaldo Cephas', 'Delantero'),
    ('Jamaica', 19, 'Kevon Lambert', 'Centrocampista'),
    ('Jamaica', 20, 'Tayvon Gray', 'Defensa'),
    ('Jamaica', 21, 'Kaheim Dixon', 'Delantero'),
    ('Jamaica', 22, 'Greg Leigh', 'Defensa'),
    ('Jamaica', 23, 'Michael Hector', 'Defensa'),
    ('Jamaica', 24, 'Alex Marshall', 'Centrocampista'),
    ('Jamaica', 25, 'Devonte Campbell', 'Delantero'),
    ('Jamaica', 26, 'Jon Russell', 'Centrocampista'),
    ('Australia', 1, 'Mathew Ryan', 'Portero'),
    ('Australia', 2, 'Gethin Jones', 'Defensa'),
    ('Australia', 3, 'Nathaniel Atkinson', 'Defensa'),
    ('Australia', 4, 'Kye Rowles', 'Defensa'),
    ('Australia', 5, 'Jordan Bos', 'Defensa'),
    ('Australia', 6, 'Martin Boyle', 'Delantero'),
    ('Australia', 7, 'Samuel Silvera', 'Delantero'),
    ('Australia', 8, 'Connor Metcalfe', 'Centrocampista'),
    ('Australia', 9, 'Bruno Fornaroli', 'Delantero'),
    ('Australia', 10, 'Kusini Yengi', 'Delantero'),
    ('Australia', 11, 'Marco Tilio', 'Delantero'),
    ('Australia', 12, 'Lawrence Thomas', 'Portero'),
    ('Australia', 13, 'Aiden O\'Neill', 'Centrocampista'),
    ('Australia', 14, 'Riley McGree', 'Centrocampista'),
    ('Australia', 15, 'Mitchell Duke', 'Delantero'),
    ('Australia', 16, 'Aziz Behich', 'Defensa'),
    ('Australia', 17, 'Keanu Baccus', 'Centrocampista'),
    ('Australia', 18, 'Joe Gauci', 'Portero'),
    ('Australia', 19, 'Harry Souttar', 'Defensa'),
    ('Australia', 20, 'Lewis Miller', 'Defensa'),
    ('Australia', 21, 'Cameron Burgess', 'Defensa'),
    ('Australia', 22, 'Jackson Irvine', 'Centrocampista'),
    ('Australia', 23, 'Craig Goodwin', 'Delantero'),
    ('Australia', 24, 'John Iredale', 'Delantero'),
    ('Australia', 25, 'Patrick Yazbek', 'Centrocampista'),
    ('Australia', 26, 'Thomas Deng', 'Defensa'),
    ('Uzbekistán', 1, 'Utkir Yusupov', 'Portero'),
    ('Uzbekistán', 2, 'Saidazamat Mirsaidov', 'Defensa'),
    ('Uzbekistán', 3, 'Khojiakbar Alijonov', 'Defensa'),
    ('Uzbekistán', 4, 'Farrukh Sayfiev', 'Defensa'),
    ('Uzbekistán', 5, 'Rustam Ashurmatov', 'Defensa'),
    ('Uzbekistán', 6, 'Diyor Kholmatov', 'Centrocampista'),
    ('Uzbekistán', 7, 'Otabek Shukurov', 'Centrocampista'),
    ('Uzbekistán', 8, 'Jamshid Iskanderov', 'Centrocampista'),
    ('Uzbekistán', 9, 'Odiljon Hamrobekov', 'Centrocampista'),
    ('Uzbekistán', 10, 'Jaloliddin Masharipov', 'Centrocampista'),
    ('Uzbekistán', 11, 'Oston Urunov', 'Delantero'),
    ('Uzbekistán', 12, 'Abduvohid Nematov', 'Portero'),
    ('Uzbekistán', 13, 'Sherzod Nasrullaev', 'Defensa'),
    ('Uzbekistán', 14, 'Eldor Shomurodov', 'Delantero'),
    ('Uzbekistán', 15, 'Umar Eshmurodov', 'Defensa'),
    ('Uzbekistán', 16, 'Abdukodir Khusanov', 'Defensa'),
    ('Uzbekistán', 17, 'Bobur Abdikholikov', 'Delantero'),
    ('Uzbekistán', 18, 'Abdulla Abdullaev', 'Defensa'),
    ('Uzbekistán', 19, 'Azizbek Turgunboev', 'Delantero'),
    ('Uzbekistán', 20, 'Khojimat Erkinov', 'Delantero'),
    ('Uzbekistán', 21, 'Igor Sergeev', 'Delantero'),
    ('Uzbekistán', 22, 'Botirali Ergashev', 'Portero'),
    ('Uzbekistán', 23, 'Husniddin Aliqulov', 'Defensa'),
    ('Uzbekistán', 24, 'Abbosbek Fayzullaev', 'Centrocampista'),
    ('Uzbekistán', 25, 'Zafarmurod Abdurakhmatov', 'Defensa'),
    ('Uzbekistán', 26, 'Muhammadkodir Hamraliev', 'Defensa'),
    ('Venezuela', 1, 'Joel Graterol', 'Portero'),
    ('Venezuela', 2, 'Nahuel Ferraresi', 'Defensa'),
    ('Venezuela', 3, 'Yordan Osorio', 'Defensa'),
    ('Venezuela', 4, 'Jon Aramburu', 'Defensa'),
    ('Venezuela', 5, 'Junior Moreno', 'Centrocampista'),
    ('Venezuela', 6, 'Yangel Herrera', 'Centrocampista'),
    ('Venezuela', 7, 'Jefferson Savarino', 'Delantero'),
    ('Venezuela', 8, 'José Martínez', 'Centrocampista'),
    ('Venezuela', 9, 'Salomón Rondón', 'Delantero'),
    ('Venezuela', 10, 'Yeferson Soteldo', 'Delantero'),
    ('Venezuela', 11, 'Darwin Machís', 'Delantero'),
    ('Venezuela', 12, 'José Contreras', 'Portero'),
    ('Venezuela', 13, 'Christian Makoun', 'Defensa'),
    ('Venezuela', 14, 'Christian Cásseres Jr.', 'Centrocampista'),
    ('Venezuela', 15, 'Miguel Navarro', 'Defensa'),
    ('Venezuela', 16, 'Telasco Segovia', 'Centrocampista'),
    ('Venezuela', 17, 'Matías Lacava', 'Delantero'),
    ('Venezuela', 18, 'Jhonder Cádiz', 'Delantero'),
    ('Venezuela', 19, 'Eric Ramírez', 'Delantero'),
    ('Venezuela', 20, 'Wilker Ángel', 'Defensa'),
    ('Venezuela', 21, 'Alexander González', 'Defensa'),
    ('Venezuela', 22, 'Rafael Romo', 'Portero'),
    ('Venezuela', 24, 'Kervin Andrade', 'Centrocampista'),
    ('Venezuela', 25, 'Jhon Chancellor', 'Defensa'),
    ('Venezuela', 26, 'Eduard Bello', 'Delantero'),
    ('Polonia', 1, 'Wojciech Szczęsny', 'Portero'),
    ('Polonia', 2, 'Barthosz Salamon', 'Defensa'),
    ('Polonia', 3, 'Paweł Dawidowicz', 'Defensa'),
    ('Polonia', 4, 'Sebastian Walukiewicz', 'Defensa'),
    ('Polonia', 5, 'Jan Bednarek', 'Defensa'),
    ('Polonia', 6, 'Jakub Piotrowski', 'Centrocampista'),
    ('Polonia', 7, 'Arkadiusz Milik', 'Delantero'),
    ('Polonia', 8, 'Jakub Moder', 'Centrocampista'),
    ('Polonia', 9, 'Robert Lewandowski', 'Delantero'),
    ('Polonia', 10, 'Piotr Zieliński', 'Centrocampista'),
    ('Polonia', 11, 'Karol Świderski', 'Delantero'),
    ('Polonia', 12, 'Łukasz Skorupski', 'Portero'),
    ('Polonia', 13, 'Taras Romanczuk', 'Centrocampista'),
    ('Polonia', 14, 'Jakub Kiwior', 'Defensa'),
    ('Polonia', 15, 'Tymoteusz Puchacz', 'Defensa'),
    ('Polonia', 16, 'Adam Buksa', 'Delantero'),
    ('Polonia', 17, 'Damian Szymański', 'Centrocampista'),
    ('Polonia', 18, 'Bartosz Bereszyński', 'Defensa'),
    ('Polonia', 19, 'Przemysław Frankowski', 'Centrocampista'),
    ('Polonia', 20, 'Sebastian Szymański', 'Centrocampista'),
    ('Polonia', 21, 'Nicola Zalewski', 'Centrocampista'),
    ('Polonia', 22, 'Marcin Bułka', 'Portero'),
    ('Polonia', 23, 'Krzysztof Piątek', 'Delantero'),
    ('Polonia', 24, 'Michał Skóraś', 'Delantero'),
    ('Polonia', 25, 'Kacper Urbański', 'Centrocampista'),
    ('Polonia', 26, 'Mateusz Kochalski', 'Portero'),
    ('Argelia', 1, 'Mustapha Zeghba', 'Portero'),
    ('Argelia', 2, 'Aissa Mandi', 'Defensa'),
    ('Argelia', 3, 'Rayayan Aït-Nouri', 'Defensa'),
    ('Argelia', 4, 'Mohamed Amine Tougai', 'Defensa'),
    ('Argelia', 5, 'Ahmed Touba', 'Defensa'),
    ('Argelia', 6, 'Ramiz Zerrouki', 'Centrocampista'),
    ('Argelia', 7, 'Riyad Mahrez', 'Delantero'),
    ('Argelia', 8, 'Houssem Aouar', 'Centrocampista'),
    ('Argelia', 9, 'Baghdad Bounedjah', 'Delantero'),
    ('Argelia', 10, 'Sofiane Feghouli', 'Centrocampista'),
    ('Argelia', 11, 'Amine Gouiri', 'Delantero'),
    ('Argelia', 12, 'Anthony Mandrea', 'Portero'),
    ('Argelia', 13, 'Islam Slimani', 'Delantero'),
    ('Argelia', 14, 'Hicham Boudaoui', 'Centrocampista'),
    ('Argelia', 15, 'Fares Chaïbi', 'Centrocampista'),
    ('Argelia', 16, 'Oussama Benbot', 'Portero'),
    ('Argelia', 17, 'Ramy Bensebaini', 'Defensa'),
    ('Argelia', 18, 'Youcef Belaïli', 'Delantero'),
    ('Argelia', 19, 'Zineddine Belaïd', 'Defensa'),
    ('Argelia', 20, 'Kevin Van Den Kerkhof', 'Defensa'),
    ('Argelia', 21, 'Nabil Bentaleb', 'Centrocampista'),
    ('Argelia', 22, 'Ismaël Bennacer', 'Centrocampista'),
    ('Argelia', 23, 'Youcef Atal', 'Defensa'),
    ('Argelia', 24, 'Adam Ounas', 'Delantero'),
    ('Argelia', 25, 'Yasser Larouci', 'Defensa'),
    ('Argelia', 26, 'Said Benrahma', 'Delantero'),
    ('Ghana', 1, 'Richard Ofori', 'Portero'),
    ('Ghana', 2, 'Alidu Seidu', 'Defensa'),
    ('Ghana', 3, 'Denis Odoi', 'Defensa'),
    ('Ghana', 4, 'Nicholas Opoku', 'Defensa'),
    ('Ghana', 5, 'Kingsley Schindler', 'Defensa'),
    ('Ghana', 6, 'Salis Abdul Samed', 'Centrocampista'),
    ('Ghana', 7, 'Ransford-Yeboah Königsdörffer', 'Delantero'),
    ('Ghana', 8, 'Majeed Ashimeru', 'Centrocampista'),
    ('Ghana', 9, 'Jordan Ayew', 'Delantero'),
    ('Ghana', 10, 'Andre Ayew', 'Delantero'),
    ('Ghana', 11, 'Osman Bukari', 'Delantero'),
    ('Ghana', 12, 'Jojo Wollacott', 'Portero'),
    ('Ghana', 13, 'Mohammed Kudus', 'Centrocampista'),
    ('Ghana', 14, 'Gideon Mensah', 'Defensa'),
    ('Ghana', 15, 'Joseph Aidoo', 'Defensa'),
    ('Ghana', 16, 'Lawrence Ati-Zigi', 'Portero'),
    ('Ghana', 17, 'Baba Rahman', 'Defensa'),
    ('Ghana', 18, 'Daniel Amartey', 'Defensa'),
    ('Ghana', 19, 'Iñaki Williams', 'Delantero'),
    ('Ghana', 20, 'Alexander Djiku', 'Defensa'),
    ('Ghana', 21, 'Semed Salis', 'Centrocampista'),
    ('Ghana', 22, 'Kamaldeen Sulemana', 'Delantero'),
    ('Ghana', 23, 'Elisha Owusu', 'Centrocampista'),
    ('Ghana', 24, 'Ernest Nuamah', 'Delantero'),
    ('Ghana', 25, 'Antoine Semenyo', 'Delantero'),
    ('Ghana', 26, 'Iddrisu Baba', 'Centrocampista'),
    ('Dinamarca', 1, 'Kasper Schmeichel', 'Portero'),
    ('Dinamarca', 2, 'Joachim Andersen', 'Defensa'),
    ('Dinamarca', 3, 'Jannik Vestergaard', 'Defensa'),
    ('Dinamarca', 4, 'Simon Kjær', 'Defensa'),
    ('Dinamarca', 5, 'Joakim Mæhle', 'Defensa'),
    ('Dinamarca', 6, 'Andreas Christensen', 'Defensa'),
    ('Dinamarca', 7, 'Mathias Jensen', 'Centrocampista'),
    ('Dinamarca', 8, 'Thomas Delaney', 'Centrocampista'),
    ('Dinamarca', 9, 'Rasmus Højlund', 'Delantero'),
    ('Dinamarca', 10, 'Christian Eriksen', 'Centrocampista'),
    ('Dinamarca', 11, 'Andreas Skov Olsen', 'Delantero'),
    ('Dinamarca', 12, 'Mads Hermansen', 'Portero'),
    ('Dinamarca', 13, 'Zanka', 'Defensa'),
    ('Dinamarca', 14, 'Mikkel Damsgaard', 'Delantero'),
    ('Dinamarca', 15, 'Christian Nørgaard', 'Centrocampista'),
    ('Dinamarca', 16, 'Frederik Rønnow', 'Portero'),
    ('Dinamarca', 17, 'Victor Kristiansen', 'Defensa'),
    ('Dinamarca', 18, 'Alexander Bah', 'Defensa'),
    ('Dinamarca', 19, 'Jonas Wind', 'Delantero'),
    ('Dinamarca', 20, 'Yussuf Poulsen', 'Delantero'),
    ('Dinamarca', 21, 'Morten Hjulmand', 'Centrocampista'),
    ('Dinamarca', 22, 'Pierre-Emile Højbjerg', 'Centrocampista'),
    ('Dinamarca', 23, 'Kasper Dolberg', 'Delantero'),
    ('Dinamarca', 24, 'Anders Dreyer', 'Delantero'),
    ('Dinamarca', 25, 'Rasmus Kristensen', 'Defensa'),
    ('Dinamarca', 26, 'Jacob Bruun Larsen', 'Delantero'),
    ('Serbia', 1, 'Predrag Rajković', 'Portero'),
    ('Serbia', 2, 'Strahinja Pavlović', 'Defensa'),
    ('Serbia', 3, 'Nemanja Stojić', 'Defensa'),
    ('Serbia', 4, 'Nikola Milenković', 'Defensa'),
    ('Serbia', 5, 'Nemanja Maksimović', 'Centrocampista'),
    ('Serbia', 6, 'Nemanja Gudelj', 'Centrocampista'),
    ('Serbia', 7, 'Veljko Birmančević', 'Delantero'),
    ('Serbia', 8, 'Luka Jović', 'Delantero'),
    ('Serbia', 9, 'Aleksandar Mitrović', 'Delantero'),
    ('Serbia', 10, 'Dušan Tadić', 'Centrocampista'),
    ('Serbia', 11, 'Filip Kostić', 'Centrocampista'),
    ('Serbia', 12, 'Đorđe Petrović', 'Portero'),
    ('Serbia', 13, 'Miloš Veljković', 'Defensa'),
    ('Serbia', 14, 'Srđan Babić', 'Defensa'),
    ('Serbia', 15, 'Uroš Spajić', 'Defensa'),
    ('Serbia', 16, 'Srđan Mijailović', 'Defensa'),
    ('Serbia', 17, 'Andrija Živković', 'Centrocampista'),
    ('Serbia', 18, 'Petar Ratkov', 'Delantero'),
    ('Serbia', 19, 'Lazar Samardžić', 'Centrocampista'),
    ('Serbia', 20, 'Sergej Milinković-Savić', 'Centrocampista'),
    ('Serbia', 21, 'Mijat Gaćinović', 'Centrocampista'),
    ('Serbia', 22, 'Saša Lukić', 'Centrocampista'),
    ('Serbia', 23, 'Vanja Milinković-Savić', 'Portero'),
    ('Serbia', 24, 'Ivan Ilić', 'Centrocampista'),
    ('Serbia', 25, 'Filip Mladenović', 'Defensa'),
    ('Nigeria', 1, 'Francis Uzoho', 'Portero'),
    ('Nigeria', 2, 'Ola Aina', 'Defensa'),
    ('Nigeria', 3, 'Zaidu Sanusi', 'Defensa'),
    ('Nigeria', 4, 'Alhassan Yusuf', 'Centrocampista'),
    ('Nigeria', 5, 'William Troost-Ekong', 'Defensa'),
    ('Nigeria', 6, 'Semilogo Ajayi', 'Defensa'),
    ('Nigeria', 7, 'Ahmed Musa', 'Delantero'),
    ('Nigeria', 8, 'Frank Onyeka', 'Centrocampista'),
    ('Nigeria', 9, 'Victor Osimhen', 'Delantero'),
    ('Nigeria', 10, 'Joe Aribo', 'Centrocampista'),
    ('Nigeria', 11, 'Samuel Chukwueze', 'Delantero'),
    ('Nigeria', 12, 'Bright Osayi-Samuel', 'Defensa'),
    ('Nigeria', 13, 'Bruno Onyemaechi', 'Defensa'),
    ('Nigeria', 14, 'Kelechi Iheanacho', 'Delantero'),
    ('Nigeria', 15, 'Moses Simon', 'Delantero'),
    ('Nigeria', 16, 'Olorunleke Ojo', 'Portero'),
    ('Nigeria', 17, 'Alex Iwobi', 'Centrocampista'),
    ('Nigeria', 18, 'Ademola Lookman', 'Delantero'),
    ('Nigeria', 19, 'Umar Sadiq', 'Delantero'),
    ('Nigeria', 20, 'Chidozie Awaziem', 'Defensa'),
    ('Nigeria', 21, 'Calvin Bassey', 'Defensa'),
    ('Nigeria', 22, 'Kenneth Omeruo', 'Defensa'),
    ('Nigeria', 23, 'Stanley Nwabali', 'Portero'),
    ('Nigeria', 24, 'Terem Moffi', 'Delantero'),
    ('Nigeria', 25, 'Raphael Onyedika', 'Centrocampista'),
    ('Nigeria', 26, 'Wilfred Ndidi', 'Centrocampista'),
    ('Nueva Zelanda', 1, 'Max Crocombe', 'Portero'),
    ('Nueva Zelanda', 2, 'Tim Payne', 'Defensa'),
    ('Nueva Zelanda', 3, 'Francis De Vries', 'Defensa'),
    ('Nueva Zelanda', 4, 'Tyler Bindon', 'Defensa'),
    ('Nueva Zelanda', 5, 'Michael Boxall', 'Defensa'),
    ('Nueva Zelanda', 6, 'Joe Bell', 'Centrocampista'),
    ('Nueva Zelanda', 7, 'Matt Garbett', 'Centrocampista'),
    ('Nueva Zelanda', 8, 'Marko Stamenić', 'Centrocampista'),
    ('Nueva Zelanda', 9, 'Chris Wood', 'Delantero'),
    ('Nueva Zelanda', 10, 'Sarpreet Singh', 'Centrocampista'),
    ('Nueva Zelanda', 11, 'Eli Just', 'Delantero'),
    ('Nueva Zelanda', 12, 'Alex Paulsen', 'Portero'),
    ('Nueva Zelanda', 13, 'Liberato Cacace', 'Defensa'),
    ('Nueva Zelanda', 14, 'Nando Pijnaker', 'Defensa'),
    ('Nueva Zelanda', 15, 'Finn Surman', 'Defensa'),
    ('Nueva Zelanda', 16, 'Tommy Smith', 'Defensa'),
    ('Nueva Zelanda', 17, 'Callan Elliot', 'Defensa'),
    ('Nueva Zelanda', 18, 'Alex Rufer', 'Centrocampista'),
    ('Nueva Zelanda', 19, 'Ryan Thomas', 'Centrocampista'),
    ('Nueva Zelanda', 20, 'Lachlan Bayliss', 'Centrocampista'),
    ('Nueva Zelanda', 21, 'Kosta Barbarouses', 'Delantero'),
    ('Nueva Zelanda', 22, 'Michael Woud', 'Portero'),
    ('Nueva Zelanda', 23, 'Ben Waine', 'Delantero'),
    ('Nueva Zelanda', 24, 'Ben Old', 'Delantero'),
    ('Nueva Zelanda', 25, 'Callum McCowatt', 'Delantero'),
    ('Nueva Zelanda', 26, 'Jesse Randall', 'Delantero'),
]

SELECCIONES_FALTANTES = ['Sudáfrica', 'Marruecos', 'Senegal', 'Chile', 'Ucrania', 'Egipto', 'Perú', 'Túnez', 'Gales', 'Jamaica', 'Costa de Marfil', 'Venezuela', 'Polonia', 'Argelia', 'Ghana', 'Dinamarca', 'Serbia', 'Nigeria']

PAIS_TO_ID_EXISTENTE = {'México': 50, 'Canadá': 51, 'Estados Unidos': 52, 'Curazao': 53, 'Argentina': 7, 'Brasil': 8, 'Colombia': 9, 'Ecuador': 10, 'Paraguay': 11, 'Uruguay': 12, 'Austria': 13, 'Bélgica': 14, 'Bosnia y Herzegovina': 15, 'Croacia': 16, 'Chequia': 17, 'Inglaterra': 18, 'Francia': 19, 'Alemania': 20, 'Panamá': 6, 'Países Bajos': 21, 'Noruega': 22, 'Portugal': 23, 'Escocia': 24, 'España': 25, 'Suecia': 26, 'Suiza': 27, 'Turquía': 28, 'Australia': 29, 'Irak': 30, 'Irán': 31, 'Japón': 32, 'Jordania': 33, 'Corea del Sur': 34, 'Catar': 35, 'Arabia Saudita': 36, 'Uzbekistán': 37, 'Nueva Zelanda': 38}
