# Generated file - Jugadores Mundial 2026 (v2)
JUGADORES_DATA = [
    # Francia
    ('Francia', 1, 'Brice Samba', 'Portero'),
    ('Francia', 2, 'Benjamin Pavard', 'Defensa'),
    ('Francia', 3, 'Ferland Mendy', 'Defensa'),
    ('Francia', 4, 'Dayot Upamecano', 'Defensa'),
    ('Francia', 5, 'Jules Koundé', 'Defensa'),
    ('Francia', 6, 'Eduardo Camavinga', 'Centrocampista'),
    ('Francia', 7, 'Antoine Griezmann', 'Delantero'),
    ('Francia', 8, 'Aurélien Tchouaméni', 'Centrocampista'),
    ('Francia', 9, 'Olivier Giroud', 'Delantero'),
    ('Francia', 10, 'Kylian Mbappé', 'Delantero'),
    ('Francia', 11, 'Ousmane Dembélé', 'Delantero'),
    ('Francia', 12, 'Randal Kolo Muani', 'Delantero'),
    ('Francia', 13, 'N\'Golo Kanté', 'Centrocampista'),
    ('Francia', 14, 'Adrien Rabiot', 'Centrocampista'),
    ('Francia', 15, 'Marcus Thuram', 'Delantero'),
    ('Francia', 16, 'Mike Maignan', 'Portero'),
    ('Francia', 17, 'William Saliba', 'Defensa'),
    ('Francia', 18, 'Warren Zaïre-Emery', 'Centrocampista'),
    ('Francia', 19, 'Youssouf Fofana', 'Centrocampista'),
    ('Francia', 20, 'Kingsley Coman', 'Delantero'),
    ('Francia', 21, 'Jonathan Clauss', 'Defensa'),
    ('Francia', 22, 'Théo Hernandez', 'Defensa'),
    ('Francia', 23, 'Alphonse Areola', 'Portero'),
    ('Francia', 24, 'Ibrahima Konaté', 'Defensa'),
    ('Francia', 25, 'Bradley Barcola', 'Delantero'),
    ('Francia', 26, 'Dayot Upamecano', 'Defensa'),

    # España
    ('España', 1, 'David Raya', 'Portero'),
    ('España', 2, 'Dani Carvajal', 'Defensa'),
    ('España', 3, 'Robin Le Normand', 'Defensa'),
    ('España', 4, 'Nacho Fernández', 'Defensa'),
    ('España', 5, 'Daniel Vivian', 'Defensa'),
    ('España', 6, 'Mikel Merino', 'Centrocampista'),
    ('España', 7, 'Álvaro Morata', 'Delantero'),
    ('España', 8, 'Fabian Ruiz', 'Centrocampista'),
    ('España', 9, 'Joselu Mato', 'Delantero'),
    ('España', 10, 'Dani Olmo', 'Centrocampista'),
    ('España', 11, 'Ferran Torres', 'Delantero'),
    ('España', 12, 'Alex Grimaldo', 'Defensa'),
    ('España', 13, 'Álex Remiro', 'Portero'),
    ('España', 14, 'Aymeric Laporte', 'Defensa'),
    ('España', 15, 'Alex Baena', 'Centrocampista'),
    ('España', 16, 'Rodri Hernández', 'Centrocampista'),
    ('España', 17, 'Nico Williams', 'Delantero'),
    ('España', 18, 'Martin Zubimendi', 'Centrocampista'),
    ('España', 19, 'Lamine Yamal', 'Delantero'),
    ('España', 20, 'Pedri González', 'Centrocampista'),
    ('España', 21, 'Mikel Oyarzabal', 'Delantero'),
    ('España', 22, 'Jesus Navas', 'Defensa'),
    ('España', 23, 'Unai Simón', 'Portero'),
    ('España', 24, 'Marc Cucurella', 'Defensa'),
    ('España', 25, 'Fermín López', 'Centrocampista'),
    ('España', 26, 'Ayoze Pérez', 'Delantero'),

    # Inglaterra
    ('Inglaterra', 1, 'Jordan Pickford', 'Portero'),
    ('Inglaterra', 2, 'Kyle Walker', 'Defensa'),
    ('Inglaterra', 3, 'Luke Shaw', 'Defensa'),
    ('Inglaterra', 4, 'Declan Rice', 'Centrocampista'),
    ('Inglaterra', 5, 'John Stones', 'Defensa'),
    ('Inglaterra', 6, 'Marc Guéhi', 'Defensa'),
    ('Inglaterra', 7, 'Bukayo Saka', 'Delantero'),
    ('Inglaterra', 8, 'Trent Alexander-Arnold', 'Centrocampista'),
    ('Inglaterra', 9, 'Harry Kane', 'Delantero'),
    ('Inglaterra', 10, 'Jude Bellingham', 'Centrocampista'),
    ('Inglaterra', 11, 'Phil Foden', 'Delantero'),
    ('Inglaterra', 12, 'Kieran Trippier', 'Defensa'),
    ('Inglaterra', 13, 'Aaron Ramsdale', 'Portero'),
    ('Inglaterra', 14, 'Ezri Konsa', 'Defensa'),
    ('Inglaterra', 15, 'Lewis Dunk', 'Defensa'),
    ('Inglaterra', 16, 'Conor Gallagher', 'Centrocampista'),
    ('Inglaterra', 17, 'Ivan Toney', 'Delantero'),
    ('Inglaterra', 18, 'Anthony Gordon', 'Delantero'),
    ('Inglaterra', 19, 'Ollie Watkins', 'Delantero'),
    ('Inglaterra', 20, 'Jarrod Bowen', 'Delantero'),
    ('Inglaterra', 21, 'Eberechi Eze', 'Delantero'),
    ('Inglaterra', 22, 'Joe Gomez', 'Defensa'),
    ('Inglaterra', 23, 'Dean Henderson', 'Portero'),
    ('Inglaterra', 24, 'Cole Palmer', 'Centrocampista'),
    ('Inglaterra', 25, 'Adam Wharton', 'Centrocampista'),
    ('Inglaterra', 26, 'Kobbie Mainoo', 'Centrocampista'),

    # Alemania
    ('Alemania', 1, 'Manuel Neuer', 'Portero'),
    ('Alemania', 2, 'Antonio Rüdiger', 'Defensa'),
    ('Alemania', 3, 'David Raum', 'Defensa'),
    ('Alemania', 4, 'Jonathan Tah', 'Defensa'),
    ('Alemania', 5, 'Pascal Groß', 'Centrocampista'),
    ('Alemania', 6, 'Joshua Kimmich', 'Defensa'),
    ('Alemania', 7, 'Kai Havertz', 'Delantero'),
    ('Alemania', 8, 'Toni Kroos', 'Centrocampista'),
    ('Alemania', 9, 'Niclas Füllkrug', 'Delantero'),
    ('Alemania', 10, 'Jamal Musiala', 'Centrocampista'),
    ('Alemania', 11, 'Chris Führich', 'Delantero'),
    ('Alemania', 12, 'Oliver Baumann', 'Portero'),
    ('Alemania', 13, 'Thomas Müller', 'Delantero'),
    ('Alemania', 14, 'Maximilian Beier', 'Delantero'),
    ('Alemania', 15, 'Nico Schlotterbeck', 'Defensa'),
    ('Alemania', 16, 'Waldemar Anton', 'Defensa'),
    ('Alemania', 17, 'Florian Wirtz', 'Centrocampista'),
    ('Alemania', 18, 'Maximilian Mittelstädt', 'Defensa'),
    ('Alemania', 19, 'Leroy Sané', 'Delantero'),
    ('Alemania', 20, 'Benjamin Henrichs', 'Defensa'),
    ('Alemania', 21, 'Ilkay Gündogan', 'Centrocampista'),
    ('Alemania', 22, 'Marc-André ter Stegen', 'Portero'),
    ('Alemania', 23, 'Robert Andrich', 'Centrocampista'),
    ('Alemania', 24, 'Robin Koch', 'Defensa'),
    ('Alemania', 25, 'Emre Can', 'Centrocampista'),
    ('Alemania', 26, 'Deniz Undav', 'Delantero'),

    # Portugal
    ('Portugal', 1, 'Rui Patrício', 'Portero'),
    ('Portugal', 2, 'Nélson Semedo', 'Defensa'),
    ('Portugal', 3, 'Pepe', 'Defensa'),
    ('Portugal', 4, 'Rúben Dias', 'Defensa'),
    ('Portugal', 5, 'Diogo Dalot', 'Defensa'),
    ('Portugal', 6, 'João Palhinha', 'Centrocampista'),
    ('Portugal', 7, 'Cristiano Ronaldo', 'Delantero'),
    ('Portugal', 8, 'Bruno Fernandes', 'Centrocampista'),
    ('Portugal', 9, 'Gonçalo Ramos', 'Delantero'),
    ('Portugal', 10, 'Bernardo Silva', 'Centrocampista'),
    ('Portugal', 11, 'João Félix', 'Delantero'),
    ('Portugal', 12, 'José Sá', 'Portero'),
    ('Portugal', 13, 'Danilo Pereira', 'Defensa'),
    ('Portugal', 14, 'Gonçalo Inácio', 'Defensa'),
    ('Portugal', 15, 'João Neves', 'Centrocampista'),
    ('Portugal', 16, 'Matheus Nunes', 'Centrocampista'),
    ('Portugal', 17, 'Rafael Leão', 'Delantero'),
    ('Portugal', 18, 'Rúben Neves', 'Centrocampista'),
    ('Portugal', 19, 'Nuno Mendes', 'Defensa'),
    ('Portugal', 20, 'João Cancelo', 'Defensa'),
    ('Portugal', 21, 'Diogo Jota', 'Delantero'),
    ('Portugal', 22, 'Diogo Costa', 'Portero'),
    ('Portugal', 23, 'Vitinha', 'Centrocampista'),
    ('Portugal', 24, 'António Silva', 'Defensa'),
    ('Portugal', 25, 'Pedro Neto', 'Delantero'),
    ('Portugal', 26, 'Francisco Conceição', 'Delantero'),

    # Países Bajos
    ('Países Bajos', 1, 'Bart Verbruggen', 'Portero'),
    ('Países Bajos', 2, 'Lutsharel Geertruida', 'Defensa'),
    ('Países Bajos', 3, 'Matthijs de Ligt', 'Defensa'),
    ('Países Bajos', 4, 'Virgil van Dijk', 'Defensa'),
    ('Países Bajos', 5, 'Nathan Aké', 'Defensa'),
    ('Países Bajos', 6, 'Stefan de Vrij', 'Defensa'),
    ('Países Bajos', 7, 'Xavi Simons', 'Centrocampista'),
    ('Países Bajos', 8, 'Georginio Wijnaldum', 'Centrocampista'),
    ('Países Bajos', 9, 'Wout Weghorst', 'Delantero'),
    ('Países Bajos', 10, 'Memphis Depay', 'Delantero'),
    ('Países Bajos', 11, 'Cody Gakpo', 'Delantero'),
    ('Países Bajos', 12, 'Jeremie Frimpong', 'Defensa'),
    ('Países Bajos', 13, 'Justin Bijlow', 'Portero'),
    ('Países Bajos', 14, 'Tijjani Reijnders', 'Centrocampista'),
    ('Países Bajos', 15, 'Micky van de Ven', 'Defensa'),
    ('Países Bajos', 16, 'Joey Veerman', 'Centrocampista'),
    ('Países Bajos', 17, 'Daley Blind', 'Defensa'),
    ('Países Bajos', 18, 'Donyell Malen', 'Delantero'),
    ('Países Bajos', 19, 'Brian Brobbey', 'Delantero'),
    ('Países Bajos', 20, 'Teun Koopmeiners', 'Centrocampista'),
    ('Países Bajos', 21, 'Joshua Zirkzee', 'Delantero'),
    ('Países Bajos', 22, 'Denzel Dumfries', 'Defensa'),
    ('Países Bajos', 23, 'Mark Flekken', 'Portero'),
    ('Países Bajos', 24, 'Jerdy Schouten', 'Centrocampista'),
    ('Países Bajos', 25, 'Ryan Gravenberch', 'Centrocampista'),
    ('Países Bajos', 26, 'Steven Bergwijn', 'Delantero'),

    # Bélgica
    ('Bélgica', 1, 'Koen Casteels', 'Portero'),
    ('Bélgica', 2, 'Zeno Debast', 'Defensa'),
    ('Bélgica', 3, 'Arthur Theate', 'Defensa'),
    ('Bélgica', 4, 'Wout Faes', 'Defensa'),
    ('Bélgica', 5, 'Jan Vertonghen', 'Defensa'),
    ('Bélgica', 6, 'Axel Witsel', 'Defensa'),
    ('Bélgica', 7, 'Kevin De Bruyne', 'Centrocampista'),
    ('Bélgica', 8, 'Youri Tielemans', 'Centrocampista'),
    ('Bélgica', 9, 'Leandro Trossard', 'Delantero'),
    ('Bélgica', 10, 'Romelu Lukaku', 'Delantero'),
    ('Bélgica', 11, 'Yannick Carrasco', 'Delantero'),
    ('Bélgica', 12, 'Thomas Kaminski', 'Portero'),
    ('Bélgica', 13, 'Matz Sels', 'Portero'),
    ('Bélgica', 14, 'Dodi Lukebakio', 'Delantero'),
    ('Bélgica', 15, 'Thomas Meunier', 'Defensa'),
    ('Bélgica', 16, 'Aster Vranckx', 'Centrocampista'),
    ('Bélgica', 17, 'Charles De Ketelaere', 'Delantero'),
    ('Bélgica', 18, 'Orel Mangala', 'Centrocampista'),
    ('Bélgica', 19, 'Johan Bakayoko', 'Delantero'),
    ('Bélgica', 20, 'Loïs Openda', 'Delantero'),
    ('Bélgica', 21, 'Timothy Castagne', 'Defensa'),
    ('Bélgica', 22, 'Jérémy Doku', 'Delantero'),
    ('Bélgica', 23, 'Arthur Vermeeren', 'Centrocampista'),
    ('Bélgica', 24, 'Amadou Onana', 'Centrocampista'),
    ('Bélgica', 25, 'Maxim De Cuyper', 'Defensa'),
    ('Bélgica', 26, 'Mandela Keita', 'Centrocampista'),

    # Uruguay
    ('Uruguay', 1, 'Sergio Rochet', 'Portero'),
    ('Uruguay', 2, 'José María Giménez', 'Defensa'),
    ('Uruguay', 3, 'Sebastián Cáceres', 'Defensa'),
    ('Uruguay', 4, 'Ronald Araújo', 'Defensa'),
    ('Uruguay', 5, 'Manuel Ugarte', 'Centrocampista'),
    ('Uruguay', 6, 'Rodrigo Bentancur', 'Centrocampista'),
    ('Uruguay', 7, 'Nicolás de la Cruz', 'Centrocampista'),
    ('Uruguay', 8, 'Nahitan Nández', 'Centrocampista'),
    ('Uruguay', 9, 'Luis Suárez', 'Delantero'),
    ('Uruguay', 10, 'Giorgian de Arrascaeta', 'Centrocampista'),
    ('Uruguay', 11, 'Facundo Pellistri', 'Delantero'),
    ('Uruguay', 12, 'Santiago Mele', 'Portero'),
    ('Uruguay', 13, 'Guillermo Varela', 'Defensa'),
    ('Uruguay', 14, 'Agustín Canobbio', 'Delantero'),
    ('Uruguay', 15, 'Federico Valverde', 'Centrocampista'),
    ('Uruguay', 16, 'Mathías Olivera', 'Defensa'),
    ('Uruguay', 17, 'Matías Viña', 'Defensa'),
    ('Uruguay', 18, 'Brian Rodríguez', 'Delantero'),
    ('Uruguay', 19, 'Darwin Núñez', 'Delantero'),
    ('Uruguay', 20, 'Maximiliano Araújo', 'Delantero'),
    ('Uruguay', 21, 'Emiliano Martínez Toranza', 'Centrocampista'),
    ('Uruguay', 22, 'Nicolás Marichal', 'Defensa'),
    ('Uruguay', 23, 'Franco Israel', 'Portero'),
    ('Uruguay', 24, 'Lucas Olaza', 'Defensa'),
    ('Uruguay', 25, 'Cristian Olivera', 'Delantero'),
    ('Uruguay', 26, 'Brian Ocampo', 'Delantero'),

    # Colombia
    ('Colombia', 1, 'David Ospina', 'Portero'),
    ('Colombia', 2, 'Carlos Cuesta', 'Defensa'),
    ('Colombia', 3, 'Jhon Lucumí', 'Defensa'),
    ('Colombia', 4, 'Santiago Arias', 'Defensa'),
    ('Colombia', 5, 'Kevin Castaño', 'Centrocampista'),
    ('Colombia', 6, 'Richard Ríos', 'Centrocampista'),
    ('Colombia', 7, 'Luis Díaz', 'Delantero'),
    ('Colombia', 8, 'Jorge Carrascal', 'Centrocampista'),
    ('Colombia', 9, 'Miguel Borja', 'Delantero'),
    ('Colombia', 10, 'James Rodríguez', 'Centrocampista'),
    ('Colombia', 11, 'Jhon Arias', 'Delantero'),
    ('Colombia', 12, 'Camilo Vargas', 'Portero'),
    ('Colombia', 13, 'Yerry Mina', 'Defensa'),
    ('Colombia', 14, 'Andrés Gómez', 'Delantero'),
    ('Colombia', 15, 'Mateus Uribe', 'Centrocampista'),
    ('Colombia', 16, 'Jefferson Lerma', 'Centrocampista'),
    ('Colombia', 17, 'Johan Mojica', 'Defensa'),
    ('Colombia', 18, 'Luis Sinisterra', 'Delantero'),
    ('Colombia', 19, 'Rafael Santos Borré', 'Delantero'),
    ('Colombia', 20, 'Juan Fernando Quintero', 'Centrocampista'),
    ('Colombia', 21, 'Daniel Muñoz', 'Defensa'),
    ('Colombia', 22, 'Yáser Asprilla', 'Centrocampista'),
    ('Colombia', 23, 'Álvaro Montero', 'Portero'),
    ('Colombia', 24, 'Davinson Sánchez', 'Defensa'),
    ('Colombia', 25, 'Deiver Machado', 'Defensa'),
    ('Colombia', 26, 'Jhon Durán', 'Delantero'),

    # Croacia
    ('Croacia', 1, 'Dominik Livaković', 'Portero'),
    ('Croacia', 2, 'Josip Stanišić', 'Defensa'),
    ('Croacia', 3, 'Borna Sosa', 'Defensa'),
    ('Croacia', 4, 'Ivan Perišić', 'Delantero'),
    ('Croacia', 5, 'Martin Erlić', 'Defensa'),
    ('Croacia', 6, 'Josip Šutalo', 'Defensa'),
    ('Croacia', 7, 'Lovro Majer', 'Centrocampista'),
    ('Croacia', 8, 'Mateo Kovačić', 'Centrocampista'),
    ('Croacia', 9, 'Andrej Kramarić', 'Delantero'),
    ('Croacia', 10, 'Luka Modrić', 'Centrocampista'),
    ('Croacia', 11, 'Marcelo Brozović', 'Centrocampista'),
    ('Croacia', 12, 'Nediljko Labrović', 'Portero'),
    ('Croacia', 13, 'Nikola Vlašić', 'Centrocampista'),
    ('Croacia', 14, 'Marco Pašalić', 'Delantero'),
    ('Croacia', 15, 'Mario Pašalić', 'Centrocampista'),
    ('Croacia', 16, 'Ivica Ivušić', 'Portero'),
    ('Croacia', 17, 'Bruno Petković', 'Delantero'),
    ('Croacia', 18, 'Luka Ivanušec', 'Centrocampista'),
    ('Croacia', 19, 'Borna Barišić', 'Defensa'),
    ('Croacia', 20, 'Joško Gvardiol', 'Defensa'),
    ('Croacia', 21, 'Domagoj Vida', 'Defensa'),
    ('Croacia', 22, 'Josip Juranović', 'Defensa'),
    ('Croacia', 23, 'Luka Sučić', 'Centrocampista'),
    ('Croacia', 24, 'Martin Baturina', 'Centrocampista'),
    ('Croacia', 25, 'Petar Musa', 'Delantero'),
    ('Croacia', 26, 'Dion Drena Beljo', 'Delantero'),

    # Marruecos
    ('Marruecos', 1, 'Yassine Bounou', 'Portero'),
    ('Marruecos', 2, 'Achraf Hakimi', 'Defensa'),
    ('Marruecos', 3, 'Noussair Mazraoui', 'Defensa'),
    ('Marruecos', 4, 'Sofyan Amrabat', 'Centrocampista'),
    ('Marruecos', 5, 'Nayef Aguerd', 'Defensa'),
    ('Marruecos', 6, 'Romain Saïss', 'Defensa'),
    ('Marruecos', 7, 'Hakim Ziyech', 'Delantero'),
    ('Marruecos', 8, 'Azzedine Ounahi', 'Centrocampista'),
    ('Marruecos', 9, 'Abderrazak Hamdallah', 'Delantero'),
    ('Marruecos', 10, 'Anass Zaroury', 'Delantero'),
    ('Marruecos', 11, 'Abde Ezzalzouli', 'Delantero'),
    ('Marruecos', 12, 'Munir Mohamedi', 'Portero'),
    ('Marruecos', 13, 'Ilias Chair', 'Centrocampista'),
    ('Marruecos', 14, 'Zakaria Aboukhlal', 'Delantero'),
    ('Marruecos', 15, 'Selim Amallah', 'Centrocampista'),
    ('Marruecos', 16, 'Yahia Attiyat Allah', 'Defensa'),
    ('Marruecos', 17, 'Sofiane Boufal', 'Delantero'),
    ('Marruecos', 18, 'Jawad El Yamiq', 'Defensa'),
    ('Marruecos', 19, 'Youssef En-Nesyri', 'Delantero'),
    ('Marruecos', 20, 'Achraf Dari', 'Defensa'),
    ('Marruecos', 21, 'Walid Cheddira', 'Delantero'),
    ('Marruecos', 22, 'Ahmed Reda Tagnaouti', 'Portero'),
    ('Marruecos', 23, 'Bilal El Khannouss', 'Centrocampista'),
    ('Marruecos', 24, 'Badr Benoun', 'Defensa'),
    ('Marruecos', 25, 'Yahya Jabrane', 'Centrocampista'),
    ('Marruecos', 26, 'Brahim Díaz', 'Delantero'),

    # Ecuador
    ('Ecuador', 1, 'Hernán Galíndez', 'Portero'),
    ('Ecuador', 2, 'Félix Torres', 'Defensa'),
    ('Ecuador', 3, 'Piero Hincapié', 'Defensa'),
    ('Ecuador', 4, 'Joel Ordóñez', 'Defensa'),
    ('Ecuador', 5, 'José Cifuentes', 'Centrocampista'),
    ('Ecuador', 6, 'William Pacho', 'Defensa'),
    ('Ecuador', 7, 'Pervis Estupiñán', 'Defensa'),
    ('Ecuador', 8, 'Carlos Gruezo', 'Centrocampista'),
    ('Ecuador', 9, 'John Yeboah', 'Delantero'),
    ('Ecuador', 10, 'Kendry Páez', 'Centrocampista'),
    ('Ecuador', 11, 'Kevin Rodríguez', 'Delantero'),
    ('Ecuador', 12, 'Moisés Ramírez', 'Portero'),
    ('Ecuador', 13, 'Enner Valencia', 'Delantero'),
    ('Ecuador', 14, 'Alan Minda', 'Delantero'),
    ('Ecuador', 15, 'Ángel Mena', 'Centrocampista'),
    ('Ecuador', 16, 'Jeremy Sarmiento', 'Delantero'),
    ('Ecuador', 17, 'Angelo Preciado', 'Defensa'),
    ('Ecuador', 18, 'Jhojan Julio', 'Delantero'),
    ('Ecuador', 19, 'Jordy Caicedo', 'Delantero'),
    ('Ecuador', 20, 'Alan Franco', 'Centrocampista'),
    ('Ecuador', 21, 'Moisés Caicedo', 'Centrocampista'),
    ('Ecuador', 22, 'Alexander Domínguez', 'Portero'),
    ('Ecuador', 23, 'Jackson Porozo', 'Defensa'),
    ('Ecuador', 24, 'José Hurtado', 'Defensa'),
    ('Ecuador', 25, 'Cristian Ramírez', 'Defensa'),
    ('Ecuador', 26, 'Joao Ortiz', 'Centrocampista'),

    # Senegal
    ('Senegal', 1, 'Édouard Mendy', 'Portero'),
    ('Senegal', 2, 'Formose Mendy', 'Defensa'),
    ('Senegal', 3, 'Kalidou Koulibaly', 'Defensa'),
    ('Senegal', 4, 'Abdoulaye Seck', 'Defensa'),
    ('Senegal', 5, 'Idrissa Gueye', 'Centrocampista'),
    ('Senegal', 6, 'Nampalys Mendy', 'Centrocampista'),
    ('Senegal', 7, 'Nicolas Jackson', 'Delantero'),
    ('Senegal', 8, 'Cheikhou Kouyaté', 'Centrocampista'),
    ('Senegal', 9, 'Iliman Ndiaye', 'Delantero'),
    ('Senegal', 10, 'Sadio Mané', 'Delantero'),
    ('Senegal', 11, 'Boulaye Dia', 'Delantero'),
    ('Senegal', 12, 'Fodé Ballo-Touré', 'Defensa'),
    ('Senegal', 13, 'Ismail Jakobs', 'Defensa'),
    ('Senegal', 14, 'Ismaïla Sarr', 'Delantero'),
    ('Senegal', 15, 'Krépin Diatta', 'Centrocampista'),
    ('Senegal', 16, 'Seny Dieng', 'Portero'),
    ('Senegal', 17, 'Pape Matar Sarr', 'Centrocampista'),
    ('Senegal', 18, 'Abdou Diallo', 'Defensa'),
    ('Senegal', 19, 'Moussa Niakhaté', 'Defensa'),
    ('Senegal', 20, 'Habib Diallo', 'Delantero'),
    ('Senegal', 21, 'Lamine Camara', 'Centrocampista'),
    ('Senegal', 22, 'Mory Diaw', 'Portero'),
    ('Senegal', 23, 'Pathé Ciss', 'Centrocampista'),
    ('Senegal', 24, 'Abdallah Sima', 'Delantero'),
    ('Senegal', 25, 'Pape Gueye', 'Centrocampista'),
    ('Senegal', 26, 'Cheikh Ndiaye', 'Portero'),

    # Japón
    ('Japón', 1, 'Daiya Maekawa', 'Portero'),
    ('Japón', 2, 'Yukinari Sugawara', 'Defensa'),
    ('Japón', 3, 'Shogo Taniguchi', 'Defensa'),
    ('Japón', 4, 'Ko Itakura', 'Defensa'),
    ('Japón', 5, 'Hidemasa Morita', 'Centrocampista'),
    ('Japón', 6, 'Wataru Endo', 'Centrocampista'),
    ('Japón', 7, 'Kaoru Mitoma', 'Delantero'),
    ('Japón', 8, 'Takumi Minamino', 'Centrocampista'),
    ('Japón', 9, 'Ayase Ueda', 'Delantero'),
    ('Japón', 10, 'Ritsu Doan', 'Delantero'),
    ('Japón', 11, 'Mao Hosoya', 'Delantero'),
    ('Japón', 12, 'Taishi Brandon Nozawa', 'Portero'),
    ('Japón', 13, 'Keito Nakamura', 'Delantero'),
    ('Japón', 14, 'Junya Ito', 'Delantero'),
    ('Japón', 15, 'Koki Machida', 'Defensa'),
    ('Japón', 16, 'Seiya Maikuma', 'Defensa'),
    ('Japón', 17, 'Ao Tanaka', 'Centrocampista'),
    ('Japón', 18, 'Takuma Asano', 'Delantero'),
    ('Japón', 19, 'Yuta Nakayama', 'Defensa'),
    ('Japón', 20, 'Takefusa Kubo', 'Delantero'),
    ('Japón', 21, 'Hiroki Ito', 'Defensa'),
    ('Japón', 22, 'Takehiro Tomiyasu', 'Defensa'),
    ('Japón', 23, 'Zion Suzuki', 'Portero'),
    ('Japón', 24, 'Kuryu Matsuki', 'Centrocampista'),
    ('Japón', 25, 'Daizen Maeda', 'Delantero'),
    ('Japón', 26, 'Reo Hatate', 'Centrocampista'),

    # Suiza
    ('Suiza', 1, 'Yann Sommer', 'Portero'),
    ('Suiza', 2, 'Leonidas Stergiou', 'Defensa'),
    ('Suiza', 3, 'Silvan Widmer', 'Defensa'),
    ('Suiza', 4, 'Nico Elvedi', 'Defensa'),
    ('Suiza', 5, 'Manuel Akanji', 'Defensa'),
    ('Suiza', 6, 'Denis Zakaria', 'Centrocampista'),
    ('Suiza', 7, 'Breel Embolo', 'Delantero'),
    ('Suiza', 8, 'Remo Freuler', 'Centrocampista'),
    ('Suiza', 9, 'Noah Okafor', 'Delantero'),
    ('Suiza', 10, 'Granit Xhaka', 'Centrocampista'),
    ('Suiza', 11, 'Renato Steffen', 'Delantero'),
    ('Suiza', 12, 'Yvon Mvogo', 'Portero'),
    ('Suiza', 13, 'Ricardo Rodríguez', 'Defensa'),
    ('Suiza', 14, 'Steven Zuber', 'Centrocampista'),
    ('Suiza', 15, 'Cédric Zesiger', 'Defensa'),
    ('Suiza', 16, 'Vincent Sierro', 'Centrocampista'),
    ('Suiza', 17, 'Ruben Vargas', 'Delantero'),
    ('Suiza', 18, 'Kwadwo Duah', 'Delantero'),
    ('Suiza', 19, 'Dan Ndoye', 'Delantero'),
    ('Suiza', 20, 'Michel Aebischer', 'Centrocampista'),
    ('Suiza', 21, 'Ulysses Garcia', 'Defensa'),
    ('Suiza', 22, 'Fabian Schär', 'Defensa'),
    ('Suiza', 23, 'Xherdan Shaqiri', 'Centrocampista'),
    ('Suiza', 24, 'Gregor Kobel', 'Portero'),
    ('Suiza', 25, 'Zeki Amdouni', 'Delantero'),
    ('Suiza', 26, 'Ardon Jashari', 'Centrocampista'),

    # Corea del Sur
    ('Corea del Sur', 1, 'Kim Seung-gyu', 'Portero'),
    ('Corea del Sur', 2, 'Lee Ki-je', 'Defensa'),
    ('Corea del Sur', 3, 'Kim Jin-su', 'Defensa'),
    ('Corea del Sur', 4, 'Kim Min-jae', 'Defensa'),
    ('Corea del Sur', 5, 'Park Yong-woo', 'Centrocampista'),
    ('Corea del Sur', 6, 'Hwang In-beom', 'Centrocampista'),
    ('Corea del Sur', 7, 'Son Heung-min', 'Delantero'),
    ('Corea del Sur', 8, 'Hong Hyun-seok', 'Centrocampista'),
    ('Corea del Sur', 9, 'Cho Gue-sung', 'Delantero'),
    ('Corea del Sur', 10, 'Lee Jae-sung', 'Centrocampista'),
    ('Corea del Sur', 11, 'Hwang Hee-chan', 'Delantero'),
    ('Corea del Sur', 12, 'Song Bum-keun', 'Portero'),
    ('Corea del Sur', 13, 'Lee Soon-min', 'Centrocampista'),
    ('Corea del Sur', 14, 'Moon Seon-min', 'Delantero'),
    ('Corea del Sur', 15, 'Jung Seung-hyun', 'Defensa'),
    ('Corea del Sur', 16, 'Park Jin-seob', 'Defensa'),
    ('Corea del Sur', 17, 'Jeong Woo-yeong', 'Centrocampista'),
    ('Corea del Sur', 18, 'Lee Kang-in', 'Centrocampista'),
    ('Corea del Sur', 19, 'Kim Young-gwon', 'Defensa'),
    ('Corea del Sur', 20, 'Oh Hyeon-gyu', 'Delantero'),
    ('Corea del Sur', 21, 'Jo Hyeon-woo', 'Portero'),
    ('Corea del Sur', 22, 'Seol Young-woo', 'Defensa'),
    ('Corea del Sur', 23, 'Kim Tae-hwan', 'Defensa'),
    ('Corea del Sur', 24, 'Kim Ju-sung', 'Defensa'),
    ('Corea del Sur', 25, 'Kim Ji-soo', 'Defensa'),
    ('Corea del Sur', 26, 'Yang Hyun-jun', 'Delantero'),

    # Australia
    ('Australia', 1, 'Mathew Ryan', 'Portero'),
    ('Australia', 2, 'Gethin Jones', 'Defensa'),
    ('Australia', 3, 'Nathaniel Atkinson', 'Defensa'),
    ('Australia', 4, 'Kye Rowles', 'Defensa'),
    ('Australia', 5, 'Jordan Bos', 'Defensa'),
    ('Australia', 6, 'Martin Boyle', 'Delantero'),
    ('Australia', 7, 'Samuel Silvera', 'Delantero'),
    ('Australia', 8, 'Connor Metcalfe', 'Centrocampista'),
    ('Australia', 9, 'Bruno Fornaroli', 'Delantero'),
    ('Australia', 10, 'Kusini Yengi', 'Delantero'),
    ('Australia', 11, 'Marco Tilio', 'Delantero'),
    ('Australia', 12, 'Lawrence Thomas', 'Portero'),
    ('Australia', 13, 'Aiden O\'Neill', 'Centrocampista'),
    ('Australia', 14, 'Riley McGree', 'Centrocampista'),
    ('Australia', 15, 'Mitchell Duke', 'Delantero'),
    ('Australia', 16, 'Aziz Behich', 'Defensa'),
    ('Australia', 17, 'Keanu Baccus', 'Centrocampista'),
    ('Australia', 18, 'Joe Gauci', 'Portero'),
    ('Australia', 19, 'Harry Souttar', 'Defensa'),
    ('Australia', 20, 'Lewis Miller', 'Defensa'),
    ('Australia', 21, 'Cameron Burgess', 'Defensa'),
    ('Australia', 22, 'Jackson Irvine', 'Centrocampista'),
    ('Australia', 23, 'Craig Goodwin', 'Delantero'),
    ('Australia', 24, 'John Iredale', 'Delantero'),
    ('Australia', 25, 'Patrick Yazbek', 'Centrocampista'),
    ('Australia', 26, 'Thomas Deng', 'Defensa'),

    # Austria
    ('Austria', 1, 'Heinz Lindner', 'Portero'),
    ('Austria', 2, 'Maximilian Wöber', 'Defensa'),
    ('Austria', 3, 'Gernot Trauner', 'Defensa'),
    ('Austria', 4, 'Kevin Danso', 'Defensa'),
    ('Austria', 5, 'Stefan Posch', 'Defensa'),
    ('Austria', 6, 'Nicolas Seiwald', 'Centrocampista'),
    ('Austria', 7, 'Marko Arnautović', 'Delantero'),
    ('Austria', 8, 'Alexander Prass', 'Centrocampista'),
    ('Austria', 9, 'Marcel Sabitzer', 'Centrocampista'),
    ('Austria', 10, 'Andreas Weimann', 'Delantero'),
    ('Austria', 11, 'Michael Gregoritsch', 'Delantero'),
    ('Austria', 12, 'Niklas Hedl', 'Portero'),
    ('Austria', 13, 'Patrick Pentz', 'Portero'),
    ('Austria', 14, 'Leopold Querfeld', 'Defensa'),
    ('Austria', 15, 'Philipp Lienhart', 'Defensa'),
    ('Austria', 16, 'Phillipp Mwene', 'Defensa'),
    ('Austria', 17, 'Florian Kainz', 'Centrocampista'),
    ('Austria', 18, 'Romano Schmid', 'Centrocampista'),
    ('Austria', 19, 'Christoph Baumgartner', 'Centrocampista'),
    ('Austria', 20, 'Konrad Laimer', 'Centrocampista'),
    ('Austria', 21, 'Flavius Daniliuc', 'Defensa'),
    ('Austria', 22, 'Matthias Seidl', 'Centrocampista'),
    ('Austria', 23, 'Patrick Wimmer', 'Delantero'),
    ('Austria', 24, 'Marco Grüll', 'Delantero'),
    ('Austria', 25, 'Maximilian Entrup', 'Delantero'),
    ('Austria', 26, 'Thierno Ballo', 'Centrocampista'),

    # Turquía
    ('Turquía', 1, 'Mert Günok', 'Portero'),
    ('Turquía', 2, 'Zeki Çelik', 'Defensa'),
    ('Turquía', 3, 'Merih Demiral', 'Defensa'),
    ('Turquía', 4, 'Samet Akaydin', 'Defensa'),
    ('Turquía', 5, 'Okay Yokuşlu', 'Centrocampista'),
    ('Turquía', 6, 'Orkun Kökçü', 'Centrocampista'),
    ('Turquía', 7, 'Kerem Aktürkoğlu', 'Delantero'),
    ('Turquía', 8, 'Arda Güler', 'Centrocampista'),
    ('Turquía', 9, 'Cenk Tosun', 'Delantero'),
    ('Turquía', 10, 'Hakan Çalhanoğlu', 'Centrocampista'),
    ('Turquía', 11, 'Yusuf Yazıcı', 'Delantero'),
    ('Turquía', 12, 'Altay Bayındır', 'Portero'),
    ('Turquía', 13, 'Ahmetcan Kaplan', 'Defensa'),
    ('Turquía', 14, 'Abdülkerim Bardakcı', 'Defensa'),
    ('Turquía', 15, 'Salih Özcan', 'Centrocampista'),
    ('Turquía', 16, 'Ismail Yüksek', 'Centrocampista'),
    ('Turquía', 17, 'İrfan Can Kahveci', 'Centrocampista'),
    ('Turquía', 18, 'Mert Müldür', 'Defensa'),
    ('Turquía', 19, 'Kenan Yıldız', 'Delantero'),
    ('Turquía', 20, 'Ferdi Kadıoğlu', 'Defensa'),
    ('Turquía', 21, 'Barış Alper Yılmaz', 'Delantero'),
    ('Turquía', 22, 'Kaan Ayhan', 'Defensa'),
    ('Turquía', 23, 'Uğurcan Çakır', 'Portero'),
    ('Turquía', 24, 'Semih Kılıçsoy', 'Delantero'),
    ('Turquía', 25, 'Yunis Akgün', 'Delantero'),
    ('Turquía', 26, 'Bertuğ Yıldırım', 'Delantero'),

    # Panamá
    ('Panamá', 1, 'Luis Mejía', 'Portero'),
    ('Panamá', 2, 'César Blackman', 'Defensa'),
    ('Panamá', 3, 'José Córdoba', 'Defensa'),
    ('Panamá', 4, 'Eduardo Anderson', 'Defensa'),
    ('Panamá', 5, 'Abdiel Ayarza', 'Centrocampista'),
    ('Panamá', 6, 'Cristian Martínez', 'Centrocampista'),
    ('Panamá', 7, 'José Luis Rodríguez', 'Delantero'),
    ('Panamá', 8, 'Adalberto Carrasquilla', 'Centrocampista'),
    ('Panamá', 9, 'Eduardo Guerrero', 'Delantero'),
    ('Panamá', 10, 'Édgar Yoel Bárcenas', 'Delantero'),
    ('Panamá', 11, 'Ismael Díaz', 'Delantero'),
    ('Panamá', 12, 'César Samudio', 'Portero'),
    ('Panamá', 13, 'Fidel Escobar', 'Defensa'),
    ('Panamá', 14, 'Jovani Welch', 'Centrocampista'),
    ('Panamá', 15, 'Eric Davis', 'Defensa'),
    ('Panamá', 16, 'Andrés Andrade', 'Defensa'),
    ('Panamá', 17, 'José Fajardo', 'Delantero'),
    ('Panamá', 18, 'Michael Amir Murillo', 'Defensa'),
    ('Panamá', 19, 'Alberto Quintero', 'Delantero'),
    ('Panamá', 20, 'Aníbal Godoy', 'Centrocampista'),
    ('Panamá', 21, 'César Yanis', 'Delantero'),
    ('Panamá', 22, 'Orlando Mosquera', 'Portero'),
    ('Panamá', 23, 'Kahiser Lenis', 'Delantero'),
    ('Panamá', 24, 'Edgardo Fariña', 'Defensa'),
    ('Panamá', 25, 'Martin Morán', 'Centrocampista'),
    ('Panamá', 26, 'Carlos Harvey', 'Defensa'),

    # Escocia
    ('Escocia', 1, 'Angus Gunn', 'Portero'),
    ('Escocia', 2, 'Anthony Ralston', 'Defensa'),
    ('Escocia', 3, 'Andrew Robertson', 'Defensa'),
    ('Escocia', 4, 'Scott McTominay', 'Centrocampista'),
    ('Escocia', 5, 'Grant Hanley', 'Defensa'),
    ('Escocia', 6, 'John McGinn', 'Centrocampista'),
    ('Escocia', 7, 'John Souttar', 'Defensa'),
    ('Escocia', 8, 'Billy Gilmour', 'Centrocampista'),
    ('Escocia', 9, 'Lawrence Shankland', 'Delantero'),
    ('Escocia', 10, 'Che Adams', 'Delantero'),
    ('Escocia', 11, 'Ryan Christie', 'Centrocampista'),
    ('Escocia', 12, 'Liam Kelly', 'Portero'),
    ('Escocia', 13, 'Jack Hendry', 'Defensa'),
    ('Escocia', 14, 'Ryan Porteous', 'Defensa'),
    ('Escocia', 15, 'Liam Cooper', 'Defensa'),
    ('Escocia', 16, 'Kenny McLean', 'Centrocampista'),
    ('Escocia', 17, 'Stuart Armstrong', 'Centrocampista'),
    ('Escocia', 18, 'Lewis Morgan', 'Delantero'),
    ('Escocia', 19, 'Tommy Conway', 'Delantero'),
    ('Escocia', 20, 'Ryan Jack', 'Centrocampista'),
    ('Escocia', 21, 'Zander Clark', 'Portero'),
    ('Escocia', 22, 'Greg Taylor', 'Defensa'),
    ('Escocia', 23, 'James Forrest', 'Delantero'),
    ('Escocia', 24, 'Callum McGregor', 'Centrocampista'),
    ('Escocia', 25, 'Ross McCrorie', 'Defensa'),
    ('Escocia', 26, 'Scott McKenna', 'Defensa'),

    # Costa de Marfil
    ('Costa de Marfil', 1, 'Yahia Fofana', 'Portero'),
    ('Costa de Marfil', 2, 'Ousmane Diomande', 'Defensa'),
    ('Costa de Marfil', 3, 'Ghislain Konan', 'Defensa'),
    ('Costa de Marfil', 4, 'Jean Seri', 'Centrocampista'),
    ('Costa de Marfil', 5, 'Wilfried Singo', 'Defensa'),
    ('Costa de Marfil', 6, 'Seko Fofana', 'Centrocampista'),
    ('Costa de Marfil', 7, 'Odilon Kossounou', 'Defensa'),
    ('Costa de Marfil', 8, 'Franck Kessié', 'Centrocampista'),
    ('Costa de Marfil', 9, 'Jonathan Bamba', 'Delantero'),
    ('Costa de Marfil', 10, 'Karim Konaté', 'Delantero'),
    ('Costa de Marfil', 11, 'Jean-Philippe Krasso', 'Delantero'),
    ('Costa de Marfil', 12, 'Badra Ali Sangaré', 'Portero'),
    ('Costa de Marfil', 13, 'Jeremie Boga', 'Delantero'),
    ('Costa de Marfil', 14, 'Oumar Diakité', 'Delantero'),
    ('Costa de Marfil', 15, 'Max Gradel', 'Delantero'),
    ('Costa de Marfil', 16, 'Charles Folly', 'Portero'),
    ('Costa de Marfil', 17, 'Serge Aurier', 'Defensa'),
    ('Costa de Marfil', 18, 'Ibrahim Sangaré', 'Centrocampista'),
    ('Costa de Marfil', 19, 'Nicolas Pépé', 'Delantero'),
    ('Costa de Marfil', 20, 'Christian Kouamé', 'Delantero'),
    ('Costa de Marfil', 21, 'Evan Ndicka', 'Defensa'),
    ('Costa de Marfil', 22, 'Sebastien Haller', 'Delantero'),
    ('Costa de Marfil', 23, 'Simon Adingra', 'Delantero'),
    ('Costa de Marfil', 24, 'Willy Boly', 'Defensa'),
    ('Costa de Marfil', 25, 'Lazare Amani', 'Centrocampista'),
    ('Costa de Marfil', 26, 'Ismaël Diallo', 'Defensa'),

    # Irán
    ('Irán', 1, 'Alireza Beiranvand', 'Portero'),
    ('Irán', 2, 'Sadegh Moharrami', 'Defensa'),
    ('Irán', 3, 'Ehsan Hajsafi', 'Defensa'),
    ('Irán', 4, 'Shojae Khalilzadeh', 'Defensa'),
    ('Irán', 5, 'Milad Mohammadi', 'Defensa'),
    ('Irán', 6, 'Saeid Ezatolahi', 'Centrocampista'),
    ('Irán', 7, 'Alireza Jahanbakhsh', 'Delantero'),
    ('Irán', 8, 'Morteza Pouraliganji', 'Defensa'),
    ('Irán', 9, 'Mehdi Taremi', 'Delantero'),
    ('Irán', 10, 'Karim Ansarifard', 'Delantero'),
    ('Irán', 11, 'Vahid Amiri', 'Centrocampista'),
    ('Irán', 12, 'Payam Niazmand', 'Portero'),
    ('Irán', 13, 'Hossein Kanaanizadegan', 'Defensa'),
    ('Irán', 14, 'Saman Ghoddos', 'Centrocampista'),
    ('Irán', 15, 'Rouzbeh Cheshmi', 'Centrocampista'),
    ('Irán', 16, 'Mehdi Torabi', 'Delantero'),
    ('Irán', 17, 'Ali Gholizadeh', 'Delantero'),
    ('Irán', 18, 'Karim Karimi', 'Centrocampista'),
    ('Irán', 19, 'Majid Hosseini', 'Defensa'),
    ('Irán', 20, 'Sardar Azmoun', 'Delantero'),
    ('Irán', 21, 'Mohebi Mohammad', 'Delantero'),
    ('Irán', 22, 'Hossein Hosseini', 'Portero'),
    ('Irán', 23, 'Ramin Rezaeian', 'Defensa'),
    ('Irán', 24, 'Aria Yousefi', 'Defensa'),
    ('Irán', 25, 'Mohammad Ghorbani', 'Centrocampista'),
    ('Irán', 26, 'Shahriyar Moghanlou', 'Delantero'),

    # Noruega
    ('Noruega', 1, 'Ørjan Nyland', 'Portero'),
    ('Noruega', 2, 'Julian Ryerson', 'Defensa'),
    ('Noruega', 3, 'Kristoffer Ajer', 'Defensa'),
    ('Noruega', 4, 'Leo Østigård', 'Defensa'),
    ('Noruega', 5, 'David Møller Wolfe', 'Defensa'),
    ('Noruega', 6, 'Patrick Berg', 'Centrocampista'),
    ('Noruega', 7, 'Alexander Sørloth', 'Delantero'),
    ('Noruega', 8, 'Sander Berge', 'Centrocampista'),
    ('Noruega', 9, 'Erling Haaland', 'Delantero'),
    ('Noruega', 10, 'Martin Ødegaard', 'Centrocampista'),
    ('Noruega', 11, 'Mohamed Elyounoussi', 'Delantero'),
    ('Noruega', 12, 'Matias Dyngeland', 'Portero'),
    ('Noruega', 13, 'Andreas Hanche-Olsen', 'Defensa'),
    ('Noruega', 14, 'Marcus Holmgren Pedersen', 'Defensa'),
    ('Noruega', 15, 'Mortiz Thorsby', 'Centrocampista'),
    ('Noruega', 16, 'Hugo Vetlesen', 'Centrocampista'),
    ('Noruega', 17, 'Kristian Thorstvedt', 'Centrocampista'),
    ('Noruega', 18, 'Fredrik Aursnes', 'Centrocampista'),
    ('Noruega', 19, 'Jørgen Strand Larsen', 'Delantero'),
    ('Noruega', 20, 'Antonio Nusa', 'Delantero'),
    ('Noruega', 21, 'Oscar Bobb', 'Delantero'),
    ('Noruega', 22, 'Egil Selvik', 'Portero'),
    ('Noruega', 23, 'Aron Dønnum', 'Delantero'),
    ('Noruega', 24, 'Jesper Daland', 'Defensa'),
    ('Noruega', 25, 'Osame Sahraoui', 'Delantero'),
    ('Noruega', 26, 'Kristoffer Velde', 'Centrocampista'),

    # Paraguay
    ('Paraguay', 1, 'Carlos Coronel', 'Portero'),
    ('Paraguay', 2, 'Robert Rojas', 'Defensa'),
    ('Paraguay', 3, 'Omar Alderete', 'Defensa'),
    ('Paraguay', 4, 'Matías Espinoza', 'Defensa'),
    ('Paraguay', 5, 'Fabian Balbuena', 'Defensa'),
    ('Paraguay', 6, 'Junior Alonso', 'Defensa'),
    ('Paraguay', 7, 'Derlis González', 'Delantero'),
    ('Paraguay', 8, 'Damián Bobadilla', 'Centrocampista'),
    ('Paraguay', 9, 'Antonio Sanabria', 'Delantero'),
    ('Paraguay', 10, 'Miguel Almirón', 'Delantero'),
    ('Paraguay', 11, 'Ángel Romero', 'Delantero'),
    ('Paraguay', 12, 'Alfredo Aguilar', 'Portero'),
    ('Paraguay', 13, 'Gustavo Gómez', 'Defensa'),
    ('Paraguay', 14, 'Andrés Cubas', 'Centrocampista'),
    ('Paraguay', 15, 'Gustavo Velázquez', 'Defensa'),
    ('Paraguay', 16, 'Matías Rojas', 'Centrocampista'),
    ('Paraguay', 17, 'Alejandro Romero Gamarra', 'Centrocampista'),
    ('Paraguay', 18, 'Alex Arce', 'Delantero'),
    ('Paraguay', 19, 'Julio Enciso', 'Delantero'),
    ('Paraguay', 20, 'Richard Sánchez', 'Centrocampista'),
    ('Paraguay', 21, 'Ramón Sosa', 'Delantero'),
    ('Paraguay', 22, 'Rodrigo Morínigo', 'Portero'),
    ('Paraguay', 23, 'Mathías Villasanti', 'Centrocampista'),
    ('Paraguay', 24, 'Ivan Ramírez', 'Defensa'),
    ('Paraguay', 25, 'Hernesto Caballero', 'Centrocampista'),
    ('Paraguay', 26, 'Adam Bareiro', 'Delantero'),

    # Catar
    ('Catar', 1, 'Saad Al-Sheeb', 'Portero'),
    ('Catar', 2, 'Ró-Ró', 'Defensa'),
    ('Catar', 3, 'Al-Mahdi Ali Mukhtar', 'Defensa'),
    ('Catar', 4, 'Mohammed Waad', 'Centrocampista'),
    ('Catar', 5, 'Tarek Salman', 'Defensa'),
    ('Catar', 6, 'Abdulaziz Hatem', 'Centrocampista'),
    ('Catar', 7, 'Ahmed Alaaeldin', 'Delantero'),
    ('Catar', 8, 'Ali Assadalla', 'Centrocampista'),
    ('Catar', 9, 'Yusuf Abdurisag', 'Delantero'),
    ('Catar', 10, 'Hassan Al-Haydos', 'Delantero'),
    ('Catar', 11, 'Akram Afif', 'Delantero'),
    ('Catar', 12, 'Lucas Mendes', 'Defensa'),
    ('Catar', 13, 'Hazem Shehata', 'Defensa'),
    ('Catar', 14, 'Homam Ahmed', 'Defensa'),
    ('Catar', 15, 'Bassam Al-Rawi', 'Defensa'),
    ('Catar', 16, 'Boualem Khoukhi', 'Defensa'),
    ('Catar', 17, 'Ismaeel Mohammad', 'Delantero'),
    ('Catar', 18, 'Sultan Al-Brake', 'Defensa'),
    ('Catar', 19, 'Almoez Ali', 'Delantero'),
    ('Catar', 20, 'Ahmed Fathy', 'Centrocampista'),
    ('Catar', 21, 'Salah Zakaria', 'Portero'),
    ('Catar', 22, 'Meshaal Barsham', 'Portero'),
    ('Catar', 23, 'Mostafa Meshaal', 'Centrocampista'),
    ('Catar', 24, 'Jassem Gaber', 'Defensa'),
    ('Catar', 25, 'Ahmed Al-Ganehi', 'Delantero'),
    ('Catar', 26, 'Khaled Mohammed', 'Centrocampista'),

    # Bosnia y Herzegovina
    ('Bosnia y Herzegovina', 1, 'Kenan Pirić', 'Portero'),
    ('Bosnia y Herzegovina', 2, 'Anel Ahmedhodžić', 'Defensa'),
    ('Bosnia y Herzegovina', 3, 'Dennis Hadžikadunić', 'Defensa'),
    ('Bosnia y Herzegovina', 4, 'Jusuf Gazibegović', 'Defensa'),
    ('Bosnia y Herzegovina', 5, 'Sead Kolašinac', 'Defensa'),
    ('Bosnia y Herzegovina', 6, 'Benjamin Tahirović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 7, 'Muhamed Bešić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 8, 'Rade Krunić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 9, 'Smail Prevljak', 'Delantero'),
    ('Bosnia y Herzegovina', 10, 'Amer Gojak', 'Centrocampista'),
    ('Bosnia y Herzegovina', 11, 'Edin Džeko', 'Delantero'),
    ('Bosnia y Herzegovina', 12, 'Nikola Vasilj', 'Portero'),
    ('Bosnia y Herzegovina', 13, 'Ermedin Demirović', 'Delantero'),
    ('Bosnia y Herzegovina', 14, 'Sanicanin Sinisa', 'Defensa'),
    ('Bosnia y Herzegovina', 15, 'Eldar Ćivić', 'Defensa'),
    ('Bosnia y Herzegovina', 16, 'Adnis Alagić', 'Centrocampista'),
    ('Bosnia y Herzegovina', 17, 'Amar Rahmanović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 18, 'Amir Hadžiahmetović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 19, 'Kenan Kodro', 'Delantero'),
    ('Bosnia y Herzegovina', 20, 'Miroslav Stevanović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 21, 'Haris Hajradinović', 'Centrocampista'),
    ('Bosnia y Herzegovina', 22, 'Osman Hadžikić', 'Portero'),
    ('Bosnia y Herzegovina', 23, 'Nemanja Bilbija', 'Delantero'),
    ('Bosnia y Herzegovina', 24, 'Stjepan Radeljić', 'Defensa'),
    ('Bosnia y Herzegovina', 25, 'Adrian Leon Barišić', 'Defensa'),
    ('Bosnia y Herzegovina', 26, 'Nail Omerović', 'Centrocampista'),

    # Arabia Saudita
    ('Arabia Saudita', 1, 'Mohammed Al-Yami', 'Portero'),
    ('Arabia Saudita', 2, 'Sultan Al-Ghannam', 'Defensa'),
    ('Arabia Saudita', 3, 'Awn Al-Saluli', 'Defensa'),
    ('Arabia Saudita', 4, 'Ali Lajami', 'Defensa'),
    ('Arabia Saudita', 5, 'Ali Al-Bulaihi', 'Defensa'),
    ('Arabia Saudita', 6, 'Estructural Al-Ghamdi', 'Centrocampista'),
    ('Arabia Saudita', 7, 'Mukhtar Ali', 'Centrocampista'),
    ('Arabia Saudita', 8, 'Abdulelah Al-Malki', 'Centrocampista'),
    ('Arabia Saudita', 9, 'Firas Al-Buraikan', 'Delantero'),
    ('Arabia Saudita', 10, 'Salem Al-Dawsari', 'Delantero'),
    ('Arabia Saudita', 11, 'Saleh Al-Shehri', 'Delantero'),
    ('Arabia Saudita', 12, 'Saud Abdulhamid', 'Defensa'),
    ('Arabia Saudita', 13, 'Yasser Al-Shahrani', 'Defensa'),
    ('Arabia Saudita', 14, 'Abdullah Al-Hamdan', 'Delantero'),
    ('Arabia Saudita', 15, 'Abdullah Radif', 'Delantero'),
    ('Arabia Saudita', 16, 'Sami Al-Najei', 'Centrocampista'),
    ('Arabia Saudita', 17, 'Hassan Al-Tambakti', 'Defensa'),
    ('Arabia Saudita', 18, 'Abdulrahman Ghareeb', 'Delantero'),
    ('Arabia Saudita', 19, 'Fahad Al-Muwallad', 'Delantero'),
    ('Arabia Saudita', 20, 'Faisal Al-Ghamdi', 'Centrocampista'),
    ('Arabia Saudita', 21, 'Raghed Al-Najjar', 'Portero'),
    ('Arabia Saudita', 22, 'Ahmed Al-Kassar', 'Portero'),
    ('Arabia Saudita', 23, 'Ayman Yahya', 'Delantero'),
    ('Arabia Saudita', 24, 'Nasser Al-Dawsari', 'Centrocampista'),
    ('Arabia Saudita', 25, 'Mohammed Al-Breik', 'Defensa'),
    ('Arabia Saudita', 26, 'Hassan Kadesh', 'Defensa'),

    # Uzbekistán
    ('Uzbekistán', 1, 'Utkir Yusupov', 'Portero'),
    ('Uzbekistán', 2, 'Saidazamat Mirsaidov', 'Defensa'),
    ('Uzbekistán', 3, 'Khojiakbar Alijonov', 'Defensa'),
    ('Uzbekistán', 4, 'Farrukh Sayfiev', 'Defensa'),
    ('Uzbekistán', 5, 'Rustam Ashurmatov', 'Defensa'),
    ('Uzbekistán', 6, 'Diyor Kholmatov', 'Centrocampista'),
    ('Uzbekistán', 7, 'Otabek Shukurov', 'Centrocampista'),
    ('Uzbekistán', 8, 'Jamshid Iskanderov', 'Centrocampista'),
    ('Uzbekistán', 9, 'Odiljon Hamrobekov', 'Centrocampista'),
    ('Uzbekistán', 10, 'Jaloliddin Masharipov', 'Centrocampista'),
    ('Uzbekistán', 11, 'Oston Urunov', 'Delantero'),
    ('Uzbekistán', 12, 'Abduvohid Nematov', 'Portero'),
    ('Uzbekistán', 13, 'Sherzod Nasrullaev', 'Defensa'),
    ('Uzbekistán', 14, 'Eldor Shomurodov', 'Delantero'),
    ('Uzbekistán', 15, 'Umar Eshmurodov', 'Defensa'),
    ('Uzbekistán', 16, 'Abdukodir Khusanov', 'Defensa'),
    ('Uzbekistán', 17, 'Bobur Abdikholikov', 'Delantero'),
    ('Uzbekistán', 18, 'Abdulla Abdullaev', 'Defensa'),
    ('Uzbekistán', 19, 'Azizbek Turgunboev', 'Delantero'),
    ('Uzbekistán', 20, 'Khojimat Erkinov', 'Delantero'),
    ('Uzbekistán', 21, 'Igor Sergeev', 'Delantero'),
    ('Uzbekistán', 22, 'Botirali Ergashev', 'Portero'),
    ('Uzbekistán', 23, 'Husniddin Aliqulov', 'Defensa'),
    ('Uzbekistán', 24, 'Abbosbek Fayzullaev', 'Centrocampista'),
    ('Uzbekistán', 25, 'Zafarmurod Abdurakhmatov', 'Defensa'),
    ('Uzbekistán', 26, 'Muhammadkodir Hamraliev', 'Defensa'),

    # Argelia
    ('Argelia', 1, 'Mustapha Zeghba', 'Portero'),
    ('Argelia', 2, 'Aissa Mandi', 'Defensa'),
    ('Argelia', 3, 'Rayayan Aït-Nouri', 'Defensa'),
    ('Argelia', 4, 'Mohamed Amine Tougai', 'Defensa'),
    ('Argelia', 5, 'Ahmed Touba', 'Defensa'),
    ('Argelia', 6, 'Ramiz Zerrouki', 'Centrocampista'),
    ('Argelia', 7, 'Riyad Mahrez', 'Delantero'),
    ('Argelia', 8, 'Houssem Aouar', 'Centrocampista'),
    ('Argelia', 9, 'Baghdad Bounedjah', 'Delantero'),
    ('Argelia', 10, 'Sofiane Feghouli', 'Centrocampista'),
    ('Argelia', 11, 'Amine Gouiri', 'Delantero'),
    ('Argelia', 12, 'Anthony Mandrea', 'Portero'),
    ('Argelia', 13, 'Islam Slimani', 'Delantero'),
    ('Argelia', 14, 'Hicham Boudaoui', 'Centrocampista'),
    ('Argelia', 15, 'Fares Chaïbi', 'Centrocampista'),
    ('Argelia', 16, 'Oussama Benbot', 'Portero'),
    ('Argelia', 17, 'Ramy Bensebaini', 'Defensa'),
    ('Argelia', 18, 'Youcef Belaïli', 'Delantero'),
    ('Argelia', 19, 'Zineddine Belaïd', 'Defensa'),
    ('Argelia', 20, 'Kevin Van Den Kerkhof', 'Defensa'),
    ('Argelia', 21, 'Nabil Bentaleb', 'Centrocampista'),
    ('Argelia', 22, 'Ismaël Bennacer', 'Centrocampista'),
    ('Argelia', 23, 'Youcef Atal', 'Defensa'),
    ('Argelia', 24, 'Adam Ounas', 'Delantero'),
    ('Argelia', 25, 'Yasser Larouci', 'Defensa'),
    ('Argelia', 26, 'Said Benrahma', 'Delantero'),

    # Ghana
    ('Ghana', 1, 'Richard Ofori', 'Portero'),
    ('Ghana', 2, 'Alidu Seidu', 'Defensa'),
    ('Ghana', 3, 'Denis Odoi', 'Defensa'),
    ('Ghana', 4, 'Nicholas Opoku', 'Defensa'),
    ('Ghana', 5, 'Kingsley Schindler', 'Defensa'),
    ('Ghana', 6, 'Salis Abdul Samed', 'Centrocampista'),
    ('Ghana', 7, 'Ransford-Yeboah Königsdörffer', 'Delantero'),
    ('Ghana', 8, 'Majeed Ashimeru', 'Centrocampista'),
    ('Ghana', 9, 'Jordan Ayew', 'Delantero'),
    ('Ghana', 10, 'Andre Ayew', 'Delantero'),
    ('Ghana', 11, 'Osman Bukari', 'Delantero'),
    ('Ghana', 12, 'Jojo Wollacott', 'Portero'),
    ('Ghana', 13, 'Mohammed Kudus', 'Centrocampista'),
    ('Ghana', 14, 'Gideon Mensah', 'Defensa'),
    ('Ghana', 15, 'Joseph Aidoo', 'Defensa'),
    ('Ghana', 16, 'Lawrence Ati-Zigi', 'Portero'),
    ('Ghana', 17, 'Baba Rahman', 'Defensa'),
    ('Ghana', 18, 'Daniel Amartey', 'Defensa'),
    ('Ghana', 19, 'Iñaki Williams', 'Delantero'),
    ('Ghana', 20, 'Alexander Djiku', 'Defensa'),
    ('Ghana', 21, 'Semed Salis', 'Centrocampista'),
    ('Ghana', 22, 'Kamaldeen Sulemana', 'Delantero'),
    ('Ghana', 23, 'Elisha Owusu', 'Centrocampista'),
    ('Ghana', 24, 'Ernest Nuamah', 'Delantero'),
    ('Ghana', 25, 'Antoine Semenyo', 'Delantero'),
    ('Ghana', 26, 'Iddrisu Baba', 'Centrocampista'),

    # Nueva Zelanda
    ('Nueva Zelanda', 1, 'Max Crocombe', 'Portero'),
    ('Nueva Zelanda', 2, 'Tim Payne', 'Defensa'),
    ('Nueva Zelanda', 3, 'Francis De Vries', 'Defensa'),
    ('Nueva Zelanda', 4, 'Tyler Bindon', 'Defensa'),
    ('Nueva Zelanda', 5, 'Michael Boxall', 'Defensa'),
    ('Nueva Zelanda', 6, 'Joe Bell', 'Centrocampista'),
    ('Nueva Zelanda', 7, 'Matt Garbett', 'Centrocampista'),
    ('Nueva Zelanda', 8, 'Marko Stamenić', 'Centrocampista'),
    ('Nueva Zelanda', 9, 'Chris Wood', 'Delantero'),
    ('Nueva Zelanda', 10, 'Sarpreet Singh', 'Centrocampista'),
    ('Nueva Zelanda', 11, 'Eli Just', 'Delantero'),
    ('Nueva Zelanda', 12, 'Alex Paulsen', 'Portero'),
    ('Nueva Zelanda', 13, 'Liberato Cacace', 'Defensa'),
    ('Nueva Zelanda', 14, 'Nando Pijnaker', 'Defensa'),
    ('Nueva Zelanda', 15, 'Finn Surman', 'Defensa'),
    ('Nueva Zelanda', 16, 'Tommy Smith', 'Defensa'),
    ('Nueva Zelanda', 17, 'Callan Elliot', 'Defensa'),
    ('Nueva Zelanda', 18, 'Alex Rufer', 'Centrocampista'),
    ('Nueva Zelanda', 19, 'Ryan Thomas', 'Centrocampista'),
    ('Nueva Zelanda', 20, 'Lachlan Bayliss', 'Centrocampista'),
    ('Nueva Zelanda', 21, 'Kosta Barbarouses', 'Delantero'),
    ('Nueva Zelanda', 22, 'Michael Woud', 'Portero'),
    ('Nueva Zelanda', 23, 'Ben Waine', 'Delantero'),
    ('Nueva Zelanda', 24, 'Ben Old', 'Delantero'),
    ('Nueva Zelanda', 25, 'Callum McCowatt', 'Delantero'),
    ('Nueva Zelanda', 26, 'Jesse Randall', 'Delantero'),

    # Irak
    ('Irak', 1, 'Fahad Talib', 'Portero'),
    ('Irak', 2, 'Rebin Sulaka', 'Defensa'),
    ('Irak', 3, 'Hussein Ali', 'Defensa'),
    ('Irak', 4, 'Saad Natiq', 'Defensa'),
    ('Irak', 5, 'Ali Adnan', 'Defensa'),
    ('Irak', 6, 'Ali Jasim', 'Centrocampista'),
    ('Irak', 7, 'Youssef Amyn', 'Delantero'),
    ('Irak', 8, 'Ibrahim Bayesh', 'Centrocampista'),
    ('Irak', 9, 'Aymen Hussein', 'Delantero'),
    ('Irak', 10, 'Mohanad Ali', 'Delantero'),
    ('Irak', 11, 'Zidane Iqbal', 'Centrocampista'),
    ('Irak', 12, 'Jalal Hassan', 'Portero'),
    ('Irak', 13, 'Frans Putros', 'Defensa'),
    ('Irak', 14, 'Amjad Attwan', 'Centrocampista'),
    ('Irak', 15, 'Allan Mohideen', 'Defensa'),
    ('Irak', 16, 'Amir Al-Ammari', 'Centrocampista'),
    ('Irak', 17, 'Bashar Resan', 'Centrocampista'),
    ('Irak', 18, 'Ahmad Allee', 'Centrocampista'),
    ('Irak', 19, 'Merchas Doski', 'Defensa'),
    ('Irak', 20, 'Osama Rashid', 'Centrocampista'),
    ('Irak', 21, 'Zaid Tahseen', 'Defensa'),
    ('Irak', 22, 'Ahmed Basil', 'Portero'),
    ('Irak', 23, 'Montader Madjed', 'Delantero'),
    ('Irak', 24, 'Ziloan Hamad', 'Centrocampista'),
    ('Irak', 25, 'Ahmed Yahya', 'Defensa'),
    ('Irak', 26, 'Pashang Abdulla', 'Delantero'),

    # Curazao
    ('Curazao', 1, 'Eloy Room', 'Portero'),
    ('Curazao', 2, 'Cuco Martina', 'Defensa'),
    ('Curazao', 3, 'Jurien Gaari', 'Defensa'),
    ('Curazao', 4, 'Roshon van Eijma', 'Defensa'),
    ('Curazao', 5, 'Sherel Floranus', 'Defensa'),
    ('Curazao', 6, 'Vurnon Anita', 'Centrocampista'),
    ('Curazao', 7, 'Jearl Margaritha', 'Delantero'),
    ('Curazao', 8, 'Godfried Roemeratoe', 'Centrocampista'),
    ('Curazao', 9, 'Rangelo Janga', 'Delantero'),
    ('Curazao', 10, 'Leandro Bacuna', 'Centrocampista'),
    ('Curazao', 11, 'Gervane Kastaneer', 'Delantero'),
    ('Curazao', 12, 'Trevor Doornbusch', 'Portero'),
    ('Curazao', 13, 'Justin Ogenia', 'Defensa'),
    ('Curazao', 14, 'Nathangelo Markelo', 'Defensa'),
    ('Curazao', 15, 'Suriël Martina', 'Defensa'),
    ('Curazao', 16, 'Kevin Felida', 'Centrocampista'),
    ('Curazao', 17, 'Brandley Kuwas', 'Delantero'),
    ('Curazao', 18, 'Kenji Gorré', 'Delantero'),
    ('Curazao', 19, 'Rayvien Rosario', 'Delantero'),
    ('Curazao', 20, 'Juninho Bacuna', 'Centrocampista'),
    ('Curazao', 21, 'Roly Bonevacia', 'Centrocampista'),
    ('Curazao', 22, 'Tyrick Bodak', 'Portero'),
    ('Curazao', 23, 'Juriën Gaari', 'Defensa'),
    ('Curazao', 24, 'Bradley Martis', 'Defensa'),
    ('Curazao', 25, 'Jeremy Antonisse', 'Delantero'),
    ('Curazao', 26, 'Jorrit Hendrix', 'Centrocampista'),

    # Egipto
    ('Egipto', 1, 'Mohamed El-Shenawy', 'Portero'),
    ('Egipto', 2, 'Ali Gabr', 'Defensa'),
    ('Egipto', 3, 'Mohamed Hany', 'Defensa'),
    ('Egipto', 4, 'Omar Kamal', 'Defensa'),
    ('Egipto', 5, 'Ahmed Hegazi', 'Defensa'),
    ('Egipto', 6, 'Mohamed Abdelmonem', 'Defensa'),
    ('Egipto', 7, 'Trézéguet', 'Delantero'),
    ('Egipto', 8, 'Emam Ashour', 'Centrocampista'),
    ('Egipto', 9, 'Koka', 'Delantero'),
    ('Egipto', 10, 'Mohamed Salah', 'Delantero'),
    ('Egipto', 11, 'Mostafa Mohamed', 'Delantero'),
    ('Egipto', 12, 'Ahmed El-Shenawy', 'Portero'),
    ('Egipto', 13, 'Ahmed Abou El-Fotouh', 'Defensa'),
    ('Egipto', 14, 'Marwan Attia', 'Centrocampista'),
    ('Egipto', 15, 'Yasser Ibrahim', 'Defensa'),
    ('Egipto', 16, 'Mostafa Shobeir', 'Portero'),
    ('Egipto', 17, 'Mohamed Elneny', 'Centrocampista'),
    ('Egipto', 18, 'Mostafa Fathi', 'Delantero'),
    ('Egipto', 19, 'Mahmoud Hamada', 'Centrocampista'),
    ('Egipto', 20, 'Hamdi Fathi', 'Centrocampista'),
    ('Egipto', 21, 'Zizo', 'Centrocampista'),
    ('Egipto', 22, 'Omar Marmoush', 'Delantero'),
    ('Egipto', 23, 'Mohamed Sherif', 'Delantero'),
    ('Egipto', 24, 'Mohamed Hamdi', 'Defensa'),
    ('Egipto', 25, 'Ahmed Samy', 'Defensa'),
    ('Egipto', 26, 'Zizo Ahmed', 'Centrocampista'),

    # Sudáfrica
    ('Sudáfrica', 1, 'Ronwen Williams', 'Portero'),
    ('Sudáfrica', 2, 'Nyiko Mobbie', 'Defensa'),
    ('Sudáfrica', 3, 'Nkosinathi Sibisi', 'Defensa'),
    ('Sudáfrica', 4, 'Teboho Mokoena', 'Centrocampista'),
    ('Sudáfrica', 5, 'Siyanda Xulu', 'Defensa'),
    ('Sudáfrica', 6, 'Aubrey Modiba', 'Defensa'),
    ('Sudáfrica', 7, 'Percy Tau', 'Delantero'),
    ('Sudáfrica', 8, 'Sphephelo Sithole', 'Centrocampista'),
    ('Sudáfrica', 9, 'Evidence Makgopa', 'Delantero'),
    ('Sudáfrica', 10, 'Themba Zwane', 'Centrocampista'),
    ('Sudáfrica', 11, 'Mihlali Mayambela', 'Delantero'),
    ('Sudáfrica', 12, 'Veli Mothwa', 'Portero'),
    ('Sudáfrica', 13, 'Grant Kekana', 'Defensa'),
    ('Sudáfrica', 14, 'Mothobi Mvala', 'Defensa'),
    ('Sudáfrica', 15, 'Thapelo Maseko', 'Delantero'),
    ('Sudáfrica', 16, 'Ricardo Goss', 'Portero'),
    ('Sudáfrica', 17, 'Zakhele Lepasa', 'Delantero'),
    ('Sudáfrica', 18, 'Terrence Mashego', 'Defensa'),
    ('Sudáfrica', 19, 'Thapelo Morena', 'Defensa'),
    ('Sudáfrica', 20, 'Khuliso Mudau', 'Defensa'),
    ('Sudáfrica', 21, 'Jayden Adams', 'Centrocampista'),
    ('Sudáfrica', 22, 'Oswin Appollis', 'Delantero'),
    ('Sudáfrica', 23, 'Thabang Monare', 'Centrocampista'),
    ('Sudáfrica', 24, 'Siyabonga Ngezana', 'Defensa'),
    ('Sudáfrica', 25, 'Elias Mokwana', 'Delantero'),
    ('Sudáfrica', 26, 'Thariq Fielies', 'Defensa'),

    # República Democrática del Congo
    ('República Democrática del Congo', 1, 'Lionel Mpasi', 'Portero'),
    ('República Democrática del Congo', 2, 'Henock Inonga', 'Defensa'),
    ('República Democrática del Congo', 3, 'Arthur Masuaku', 'Defensa'),
    ('República Democrática del Congo', 4, 'Brian Bayeye', 'Defensa'),
    ('República Democrática del Congo', 5, 'Dylan Batubinsika', 'Defensa'),
    ('República Democrática del Congo', 6, 'Aaron Tshibola', 'Centrocampista'),
    ('República Democrática del Congo', 7, 'Grady Diangana', 'Delantero'),
    ('República Democrática del Congo', 8, 'Samuel Moutoussamy', 'Centrocampista'),
    ('República Democrática del Congo', 9, 'Cedric Bakambu', 'Delantero'),
    ('República Democrática del Congo', 10, 'Théo Bongonda', 'Delantero'),
    ('República Democrática del Congo', 11, 'Silas Katompa Mvumpa', 'Delantero'),
    ('República Democrática del Congo', 12, 'Dimitry Bertaud', 'Portero'),
    ('República Democrática del Congo', 13, 'Meschack Elia', 'Delantero'),
    ('República Democrática del Congo', 14, 'Gaël Kakuta', 'Centrocampista'),
    ('República Democrática del Congo', 15, 'Rocky Bushiri', 'Defensa'),
    ('República Democrática del Congo', 16, 'Baggio Siadi', 'Portero'),
    ('República Democrática del Congo', 17, 'Charles Pickel', 'Centrocampista'),
    ('República Democrática del Congo', 18, 'Samuel Essende', 'Delantero'),
    ('República Democrática del Congo', 19, 'Mayele Fiston', 'Delantero'),
    ('República Democrática del Congo', 20, 'Yoane Wissa', 'Delantero'),
    ('República Democrática del Congo', 21, 'Edo Kayembe', 'Centrocampista'),
    ('República Democrática del Congo', 22, 'Chancel Mbemba', 'Defensa'),
    ('República Democrática del Congo', 23, 'Simon Banza', 'Delantero'),
    ('República Democrática del Congo', 24, 'Gédéon Kalulu', 'Defensa'),
    ('República Democrática del Congo', 25, 'Joris Kayembe', 'Defensa'),
    ('República Democrática del Congo', 26, 'Noah Sadiki', 'Centrocampista'),

    # Cabo Verde
    ('Cabo Verde', 1, 'Vozinha', 'Portero'),
    ('Cabo Verde', 2, 'Stopira', 'Defensa'),
    ('Cabo Verde', 3, 'Diney Borges', 'Defensa'),
    ('Cabo Verde', 4, 'Roberto Lopes', 'Defensa'),
    ('Cabo Verde', 5, 'Logan Costa', 'Defensa'),
    ('Cabo Verde', 6, 'Patrick Andrade', 'Centrocampista'),
    ('Cabo Verde', 7, 'Garry Rodrigues', 'Delantero'),
    ('Cabo Verde', 8, 'João Paulo', 'Centrocampista'),
    ('Cabo Verde', 9, 'Gilson Tavares', 'Delantero'),
    ('Cabo Verde', 10, 'Jamiro Monteiro', 'Centrocampista'),
    ('Cabo Verde', 11, 'Garry Rodrigues', 'Delantero'),
    ('Cabo Verde', 12, 'Dylan Silva', 'Portero'),
    ('Cabo Verde', 13, 'Motta Carlos', 'Defensa'),
    ('Cabo Verde', 14, 'Steven de Sousa', 'Defensa'),
    ('Cabo Verde', 15, 'Laros Duarte', 'Centrocampista'),
    ('Cabo Verde', 16, 'Márcio Rosa', 'Portero'),
    ('Cabo Verde', 17, 'Willy Semedo', 'Delantero'),
    ('Cabo Verde', 18, 'Kenny Rocha Santos', 'Centrocampista'),
    ('Cabo Verde', 19, 'Bryan Teixeira', 'Delantero'),
    ('Cabo Verde', 20, 'Ryan Mendes', 'Delantero'),
    ('Cabo Verde', 21, 'Bebé', 'Delantero'),
    ('Cabo Verde', 22, 'Dylan Tavares', 'Defensa'),
    ('Cabo Verde', 23, 'Kevin Pina', 'Centrocampista'),
    ('Cabo Verde', 24, 'Deroy Duarte', 'Centrocampista'),
    ('Cabo Verde', 25, 'Cuca', 'Centrocampista'),
    ('Cabo Verde', 26, 'Hélio Varela', 'Delantero'),

    # Brasil
    ('Brasil', 1, 'Alisson Becker', 'Portero'),
    ('Brasil', 2, 'Danilo da Silva', 'Defensa'),
    ('Brasil', 3, 'Éder Militão', 'Defensa'),
    ('Brasil', 4, 'Marquinhos', 'Defensa'),
    ('Brasil', 5, 'Bruno Guimarães', 'Centrocampista'),
    ('Brasil', 6, 'Wendell', 'Defensa'),
    ('Brasil', 7, 'Vinícius Júnior', 'Delantero'),
    ('Brasil', 8, 'Lucas Paquetá', 'Centrocampista'),
    ('Brasil', 9, 'Endrick', 'Delantero'),
    ('Brasil', 10, 'Rodrygo Goes', 'Delantero'),
    ('Brasil', 11, 'Raphinha', 'Delantero'),
    ('Brasil', 12, 'Bento', 'Portero'),
    ('Brasil', 13, 'Yan Couto', 'Defensa'),
    ('Brasil', 14, 'Gabriel Magalhães', 'Defensa'),
    ('Brasil', 15, 'João Gomes', 'Centrocampista'),
    ('Brasil', 16, 'Guilherme Arana', 'Defensa'),
    ('Brasil', 17, 'Beraldo', 'Defensa'),
    ('Brasil', 18, 'Douglas Luiz', 'Centrocampista'),
    ('Brasil', 19, 'Andreas Pereira', 'Centrocampista'),
    ('Brasil', 20, 'Sávio', 'Delantero'),
    ('Brasil', 21, 'Evanilson', 'Delantero'),
    ('Brasil', 22, 'Gabriel Martinelli', 'Delantero'),
    ('Brasil', 23, 'Rafael', 'Portero'),
    ('Brasil', 24, 'Ederson Moraes', 'Portero'),
    ('Brasil', 25, 'Bremer', 'Defensa'),
    ('Brasil', 26, 'Pepê', 'Delantero'),

    # Haití
    ('Haití', 1, 'Johnny Placide', 'Portero'),
    ('Haití', 2, 'Carlens Arcus', 'Defensa'),
    ('Haití', 3, 'Duke Lacroix', 'Defensa'),
    ('Haití', 4, 'Ricardo Adé', 'Defensa'),
    ('Haití', 5, 'Garissone Innocent', 'Portero'),
    ('Haití', 6, 'Bryan Alceus', 'Centrocampista'),
    ('Haití', 7, 'Carnejy Antoine', 'Delantero'),
    ('Haití', 8, 'Leverton Pierre', 'Centrocampista'),
    ('Haití', 9, 'Duckens Nazon', 'Delantero'),
    ('Haití', 10, 'Frantzdy Pierrot', 'Delantero'),
    ('Haití', 11, 'Derrick Etienne Jr.', 'Delantero'),
    ('Haití', 12, 'Josué Duverger', 'Portero'),
    ('Haití', 13, 'Jeppe Simonsen', 'Defensa'),
    ('Haití', 14, 'Alex Christian', 'Defensa'),
    ('Haití', 15, 'Steven Séance', 'Defensa'),
    ('Haití', 16, 'Danley Jean Jacques', 'Centrocampista'),
    ('Haití', 17, 'Shanyder Borgelin', 'Delantero'),
    ('Haití', 18, 'Carl Sainte', 'Centrocampista'),
    ('Haití', 19, 'Steeven Saba', 'Centrocampista'),
    ('Haití', 20, 'Mondy Prunier', 'Delantero'),
    ('Haití', 21, 'Bryan Labissiere', 'Delantero'),
    ('Haití', 22, 'Jean-Kevin Duverne', 'Defensa'),
    ('Haití', 23, 'Francois Dulysse', 'Defensa'),
    ('Haití', 24, 'Louicius Don Deedson', 'Delantero'),
    ('Haití', 25, 'Fabrice Picault', 'Delantero'),
    ('Haití', 26, 'Garven Metusala', 'Defensa'),

    # Jordania
    ('Jordania', 1, 'Yazeed Abulaila', 'Portero'),
    ('Jordania', 2, 'Mohammad Abu Hasheesh', 'Defensa'),
    ('Jordania', 3, 'Abdallah Nasib', 'Defensa'),
    ('Jordania', 4, 'Bara\' Marei', 'Defensa'),
    ('Jordania', 5, 'Yazan Al-Arab', 'Defensa'),
    ('Jordania', 6, 'Ibrahim Sadeh', 'Centrocampista'),
    ('Jordania', 7, 'Mohammad Abu Zrayq', 'Delantero'),
    ('Jordania', 8, 'Noor Al-Rawabdeh', 'Centrocampista'),
    ('Jordania', 9, 'Ali Olwan', 'Delantero'),
    ('Jordania', 10, 'Musa Al-Taamari', 'Delantero'),
    ('Jordania', 11, 'Yazan Al-Naimat', 'Delantero'),
    ('Jordania', 12, 'Abdallah Al-Fakhouri', 'Portero'),
    ('Jordania', 13, 'Mahmoud Al-Mardi', 'Centrocampista'),
    ('Jordania', 14, 'Rajaei Ayed', 'Centrocampista'),
    ('Jordania', 15, 'Saed Al-Rosan', 'Defensa'),
    ('Jordania', 16, 'Feras Shelbaieh', 'Defensa'),
    ('Jordania', 17, 'Salem Al-Ajalin', 'Defensa'),
    ('Jordania', 18, 'Ahmad Juaidi', 'Portero'),
    ('Jordania', 19, 'Anas Al-Awarat', 'Delantero'),
    ('Jordania', 20, 'Hamza Al-Dardour', 'Delantero'),
    ('Jordania', 21, 'Saleh Rateb', 'Centrocampista'),
    ('Jordania', 22, 'Nizar Al-Rashdan', 'Centrocampista'),
    ('Jordania', 23, 'Ihsan Haddad', 'Defensa'),
    ('Jordania', 24, 'Youssef Abu Jalboush', 'Centrocampista'),
    ('Jordania', 25, 'Anas Bani Yaseen', 'Defensa'),
    ('Jordania', 26, 'Fadi Awad', 'Centrocampista'),

    # República Checa
    ('República Checa', 1, 'Jindřich Staněk', 'Portero'),
    ('República Checa', 2, 'David Zima', 'Defensa'),
    ('República Checa', 3, 'Tomáš Holeš', 'Defensa'),
    ('República Checa', 4, 'Robin Hranáč', 'Defensa'),
    ('República Checa', 5, 'Vladimír Coufal', 'Defensa'),
    ('República Checa', 6, 'Martin Vitík', 'Defensa'),
    ('República Checa', 7, 'Antonín Barák', 'Centrocampista'),
    ('República Checa', 8, 'Petr Ševčík', 'Centrocampista'),
    ('República Checa', 9, 'Adam Hložek', 'Delantero'),
    ('República Checa', 10, 'Patrik Schick', 'Delantero'),
    ('República Checa', 11, 'Jan Kuchta', 'Delantero'),
    ('República Checa', 12, 'Matěj Kovář', 'Portero'),
    ('República Checa', 13, 'Mojmír Chytil', 'Delantero'),
    ('República Checa', 14, 'Lukaš Provod', 'Centrocampista'),
    ('República Checa', 15, 'David Jurásek', 'Defensa'),
    ('República Checa', 16, 'Václav Černý', 'Delantero'),
    ('República Checa', 17, 'Tomáš Chorý', 'Delantero'),
    ('República Checa', 18, 'Ladislav Krejčí', 'Defensa'),
    ('República Checa', 19, 'Tomáš Souček', 'Centrocampista'),
    ('República Checa', 20, 'Ondřej Lingr', 'Centrocampista'),
    ('República Checa', 21, 'Lukaš Červ', 'Centrocampista'),
    ('República Checa', 22, 'Tomáš Vlček', 'Defensa'),
    ('República Checa', 23, 'Vítězslav Jaroš', 'Portero'),
    ('República Checa', 24, 'Pavel Šulc', 'Centrocampista'),
    ('República Checa', 25, 'Matěj Jurásek', 'Delantero'),
    ('República Checa', 26, 'Tomáš Wiesner', 'Defensa'),

    # Suecia
    ('Suecia', 1, 'Robin Olsen', 'Portero'),
    ('Suecia', 2, 'Emil Krafth', 'Defensa'),
    ('Suecia', 3, 'Victor Lindelöf', 'Defensa'),
    ('Suecia', 4, 'Isak Hien', 'Defensa'),
    ('Suecia', 5, 'Gabriel Gudmundsson', 'Defensa'),
    ('Suecia', 6, 'Ludwig Augustinsson', 'Defensa'),
    ('Suecia', 7, 'Emil Forsberg', 'Centrocampista'),
    ('Suecia', 8, 'Jens Cajuste', 'Centrocampista'),
    ('Suecia', 9, 'Alexander Isak', 'Delantero'),
    ('Suecia', 10, 'Dejan Kulusevski', 'Centrocampista'),
    ('Suecia', 11, 'Anthony Elanga', 'Delantero'),
    ('Suecia', 12, 'Viktor Johansson', 'Portero'),
    ('Suecia', 13, 'Carl Starfelt', 'Defensa'),
    ('Suecia', 14, 'Anton Salétros', 'Centrocampista'),
    ('Suecia', 15, 'Samuel Gustafson', 'Centrocampista'),
    ('Suecia', 16, 'Kristoffer Olsson', 'Centrocampista'),
    ('Suecia', 17, 'Viktor Gyökeres', 'Delantero'),
    ('Suecia', 18, 'Hjalmar Ekdal', 'Defensa'),
    ('Suecia', 19, 'Mattias Svanberg', 'Centrocampista'),
    ('Suecia', 20, 'Hugo Larsson', 'Centrocampista'),
    ('Suecia', 21, 'Linus Wahlqvist', 'Defensa'),
    ('Suecia', 22, 'Kristoffer Nordfeldt', 'Portero'),
    ('Suecia', 23, 'Gustaf Nilsson', 'Delantero'),
    ('Suecia', 24, 'Jacob Ondrejka', 'Delantero'),
    ('Suecia', 25, 'Edvin Kurtulus', 'Defensa'),
    ('Suecia', 26, 'Yasin Ayari', 'Centrocampista'),

    # Túnez
    ('Túnez', 1, 'Aymen Dahmen', 'Portero'),
    ('Túnez', 2, 'Ali Abdi', 'Defensa'),
    ('Túnez', 3, 'Montassar Talbi', 'Defensa'),
    ('Túnez', 4, 'Yassine Meriah', 'Defensa'),
    ('Túnez', 5, 'Nader Ghandri', 'Defensa'),
    ('Túnez', 6, 'Wajdi Kechrida', 'Defensa'),
    ('Túnez', 7, 'Youssef Msakni', 'Delantero'),
    ('Túnez', 8, 'Hamza Rafia', 'Centrocampista'),
    ('Túnez', 9, 'Haythem Jouini', 'Delantero'),
    ('Túnez', 10, 'Hannibal Mejbri', 'Centrocampista'),
    ('Túnez', 11, 'Taha Yassine Khenissi', 'Delantero'),
    ('Túnez', 12, 'Bechir Ben Saïd', 'Portero'),
    ('Túnez', 13, 'Hamza Jelassi', 'Defensa'),
    ('Túnez', 14, 'Aissa Laïdouni', 'Centrocampista'),
    ('Túnez', 15, 'Ben Romdhane', 'Centrocampista'),
    ('Túnez', 16, 'Mouez Hassen', 'Portero'),
    ('Túnez', 17, 'Ellyes Skhiri', 'Centrocampista'),
    ('Túnez', 18, 'Sayfallah Ltaief', 'Delantero'),
    ('Túnez', 19, 'Bassem Srarfi', 'Delantero'),
    ('Túnez', 20, 'Yan Valery', 'Defensa'),
    ('Túnez', 21, 'Wajdi Kechrida', 'Defensa'),
    ('Túnez', 22, 'Houssem Tka', 'Centrocampista'),
    ('Túnez', 23, 'Naïm Sliti', 'Delantero'),
    ('Túnez', 24, 'Seifeddine Jaziri', 'Delantero'),
    ('Túnez', 25, 'Ghaylen Chaaleli', 'Centrocampista'),
    ('Túnez', 26, 'Elias Achouri', 'Delantero'),

    # Argentina
    ('Argentina', 1, 'Franco Armani', 'Portero'),
    ('Argentina', 2, 'Lucas Martínez Quarta', 'Defensa'),
    ('Argentina', 3, 'Nicolás Tagliafico', 'Defensa'),
    ('Argentina', 4, 'Gonzalo Montiel', 'Defensa'),
    ('Argentina', 5, 'Leandro Paredes', 'Centrocampista'),
    ('Argentina', 6, 'Germán Pezzella', 'Defensa'),
    ('Argentina', 7, 'Rodrigo De Paul', 'Centrocampista'),
    ('Argentina', 8, 'Marcos Acuña', 'Defensa'),
    ('Argentina', 9, 'Julián Álvarez', 'Delantero'),
    ('Argentina', 10, 'Lionel Messi', 'Delantero'),
    ('Argentina', 11, 'Ángel Di María', 'Delantero'),
    ('Argentina', 12, 'Geronimo Rulli', 'Portero'),
    ('Argentina', 13, 'Cristian Romero', 'Defensa'),
    ('Argentina', 14, 'Ezequiel Palacios', 'Centrocampista'),
    ('Argentina', 15, 'Nicolás González', 'Delantero'),
    ('Argentina', 16, 'Giovani Lo Celso', 'Centrocampista'),
    ('Argentina', 17, 'Alejandro Garnacho', 'Delantero'),
    ('Argentina', 18, 'Guido Rodríguez', 'Centrocampista'),
    ('Argentina', 19, 'Nicolás Otamendi', 'Defensa'),
    ('Argentina', 20, 'Alexis Mac Allister', 'Centrocampista'),
    ('Argentina', 21, 'Valentin Carboni', 'Centrocampista'),
    ('Argentina', 22, 'Lautaro Martínez', 'Delantero'),
    ('Argentina', 23, 'Emiliano Martínez', 'Portero'),
    ('Argentina', 24, 'Enzo Fernández', 'Centrocampista'),
    ('Argentina', 25, 'Lisandro Martínez', 'Defensa'),
    ('Argentina', 26, 'Nahuel Molina', 'Defensa'),

    # Canadá
    ('Canadá', 1, 'Dayne St. Clair', 'Portero'),
    ('Canadá', 2, 'Alistair Johnston', 'Defensa'),
    ('Canadá', 3, 'Luc de Fougerolles', 'Defensa'),
    ('Canadá', 4, 'Kamal Miller', 'Defensa'),
    ('Canadá', 5, 'Joel Waterman', 'Defensa'),
    ('Canadá', 6, 'Samuel Piette', 'Centrocampista'),
    ('Canadá', 7, 'Stephen Eustáquio', 'Centrocampista'),
    ('Canadá', 8, 'Ismaël Koné', 'Centrocampista'),
    ('Canadá', 9, 'Cyle Larin', 'Delantero'),
    ('Canadá', 10, 'Jonathan David', 'Delantero'),
    ('Canadá', 11, 'Theo Bair', 'Delantero'),
    ('Canadá', 12, 'Jacen Russell-Rowe', 'Delantero'),
    ('Canadá', 13, 'Derek Cornelius', 'Defensa'),
    ('Canadá', 14, 'Jacob Shaffelburg', 'Delantero'),
    ('Canadá', 15, 'Moïse Bombito', 'Defensa'),
    ('Canadá', 16, 'Maxime Crépeau', 'Portero'),
    ('Canadá', 17, 'Tajon Buchanan', 'Delantero'),
    ('Canadá', 18, 'Tom McGill', 'Portero'),
    ('Canadá', 19, 'Alphonso Davies', 'Defensa'),
    ('Canadá', 20, 'Ali Ahmed', 'Centrocampista'),
    ('Canadá', 21, 'Jonathan Osorio', 'Centrocampista'),
    ('Canadá', 22, 'Richie Laryea', 'Defensa'),
    ('Canadá', 23, 'Liam Millar', 'Delantero'),
    ('Canadá', 24, 'Mathieu Choinière', 'Centrocampista'),
    ('Canadá', 25, 'Tani Oluwaseyi', 'Delantero'),
    ('Canadá', 26, 'Kyle Hiebert', 'Defensa'),

    # Estados Unidos
    ('Estados Unidos', 1, 'Matt Turner', 'Portero'),
    ('Estados Unidos', 2, 'Sergiño Dest', 'Defensa'),
    ('Estados Unidos', 3, 'Chris Richards', 'Defensa'),
    ('Estados Unidos', 4, 'Tyler Adams', 'Centrocampista'),
    ('Estados Unidos', 5, 'Antonee Robinson', 'Defensa'),
    ('Estados Unidos', 6, 'Yunus Musah', 'Centrocampista'),
    ('Estados Unidos', 7, 'Giovanni Reyna', 'Centrocampista'),
    ('Estados Unidos', 8, 'Weston McKennie', 'Centrocampista'),
    ('Estados Unidos', 9, 'Ricardo Pepi', 'Delantero'),
    ('Estados Unidos', 10, 'Christian Pulisic', 'Delantero'),
    ('Estados Unidos', 11, 'Brenden Aaronson', 'Centrocampista'),
    ('Estados Unidos', 12, 'Miles Robinson', 'Defensa'),
    ('Estados Unidos', 13, 'Tim Ream', 'Defensa'),
    ('Estados Unidos', 14, 'Luca de la Torre', 'Centrocampista'),
    ('Estados Unidos', 15, 'Johnny Cardoso', 'Centrocampista'),
    ('Estados Unidos', 16, 'Ethan Horvath', 'Portero'),
    ('Estados Unidos', 17, 'Malik Tillman', 'Centrocampista'),
    ('Estados Unidos', 18, 'Sandro Joseph', 'Delantero'),
    ('Estados Unidos', 19, 'Haji Wright', 'Delantero'),
    ('Estados Unidos', 20, 'Folarin Balogun', 'Delantero'),
    ('Estados Unidos', 21, 'Timothy Weah', 'Delantero'),
    ('Estados Unidos', 22, 'Joe Scally', 'Defensa'),
    ('Estados Unidos', 23, 'Kristoffer Lund', 'Defensa'),
    ('Estados Unidos', 24, 'Mark McKenzie', 'Defensa'),
    ('Estados Unidos', 25, 'Sean Johnson', 'Portero'),
    ('Estados Unidos', 26, 'Cameron Carter-Vickers', 'Defensa'),

    # México
    ('México', 1, 'Julio González', 'Portero'),
    ('México', 2, 'Jorge Sánchez', 'Defensa'),
    ('México', 3, 'César Montes', 'Defensa'),
    ('México', 4, 'Edson Álvarez', 'Centrocampista'),
    ('México', 5, 'Johan Vásquez', 'Defensa'),
    ('México', 6, 'Gerardo Arteaga', 'Defensa'),
    ('México', 7, 'Luis Romo', 'Centrocampista'),
    ('México', 8, 'Carlos Rodríguez', 'Centrocampista'),
    ('México', 9, 'Julian Quiñones', 'Delantero'),
    ('México', 10, 'Alexis Vega', 'Delantero'),
    ('México', 11, 'Santiago Giménez', 'Delantero'),
    ('México', 12, 'Carlos Acevedo', 'Portero'),
    ('México', 13, 'Guillermo Ochoa', 'Portero'),
    ('México', 14, 'Érick Sánchez', 'Centrocampista'),
    ('México', 15, 'Uriel Antuna', 'Delantero'),
    ('México', 16, 'Jordi Cortizo', 'Centrocampista'),
    ('México', 17, 'Orbelín Pineda', 'Centrocampista'),
    ('México', 18, 'Marcelo Flores', 'Delantero'),
    ('México', 19, 'Israel Reyes', 'Defensa'),
    ('México', 20, 'Luis Chávez', 'Centrocampista'),
    ('México', 21, 'César Huerta', 'Delantero'),
    ('México', 22, 'Guillermo Martínez', 'Delantero'),
    ('México', 23, 'Bryan González', 'Defensa'),
    ('México', 24, 'Jesús Orozco Chiquete', 'Defensa'),
    ('México', 25, 'Roberto Alvarado', 'Delantero'),
    ('México', 26, 'Brian García', 'Defensa'),
]
