# Generated by Django 5.2.12 on 2026-05-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('requiere_auth', models.BooleanField(default=True)),
                ('auth_configurado', models.BooleanField(default=False)),
                ('riesgo', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Critico', 'Critico')], default='Bajo', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoria de Acceso (A05)',
                'verbose_name_plural': 'Auditorias de Acceso (A05)',
                'db_table': 'auditoria_acceso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComponenteVulnerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('severidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Critica')], default='Baja', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Mitigado', 'Mitigado'), ('Aceptado', 'Aceptado')], default='Pendiente', max_length=20)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Componente Vulnerable (A09)',
                'verbose_name_plural': 'Componentes Vulnerables (A09)',
                'db_table': 'componente_vulnerable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor_actual', models.TextField()),
                ('valor_recomendado', models.TextField()),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('Advertencia', 'Advertencia'), ('Critico', 'Critico')], default='OK', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_verificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuracion Seguridad (A06)',
                'verbose_name_plural': 'Configuraciones Seguridad (A06)',
                'db_table': 'configuracion_seguridad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExposicionDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255)),
                ('tipo_dato', models.CharField(help_text='Ej: contraseña, token, PII, tarjeta', max_length=50)),
                ('exposicion', models.TextField(blank=True)),
                ('riesgo', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Critico', 'Critico')], default='Bajo', max_length=20)),
                ('recomendacion', models.TextField(blank=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exposicion Datos (A03)',
                'verbose_name_plural': 'Exposiciones Datos (A03)',
                'db_table': 'exposicion_datos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FallaAutenticacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=255)),
                ('severidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Critica')], default='Baja', max_length=20)),
                ('recomendacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Mitigado', 'Mitigado'), ('En revisión', 'En revisión')], default='Pendiente', max_length=20)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Falla Autenticacion (A02)',
                'verbose_name_plural': 'Fallas Autenticacion (A02)',
                'db_table': 'falla_autenticacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntentoDeserializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255)),
                ('tipo_dato', models.CharField(help_text='Ej: JSON, XML, Pickle, YAML', max_length=50)),
                ('contenido_muestra', models.TextField(blank=True)),
                ('permitido', models.BooleanField(default=True)),
                ('riesgo', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], default='Bajo', max_length=20)),
                ('recomendacion', models.TextField(blank=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento Deserializacion (A08)',
                'verbose_name_plural': 'Intentos Deserializacion (A08)',
                'db_table': 'intento_deserializacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PanelOWASP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Panel OWASP', max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panel OWASP',
                'verbose_name_plural': 'Panel OWASP',
                'db_table': 'panel_owasp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Monitoreo (A10)',
                'verbose_name_plural': 'Registros Monitoreo (A10)',
                'db_table': 'registro_monitoreo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VulnerabilidadInyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('parametro', models.CharField(blank=True, max_length=100)),
                ('tipo_inyeccion', models.CharField(choices=[('SQL', 'SQL'), ('NoSQL', 'NoSQL'), ('OS', 'OS'), ('LDAP', 'LDAP')], default='SQL', max_length=20)),
                ('payload', models.TextField(blank=True, help_text='Payload de prueba utilizado')),
                ('resultado', models.CharField(choices=[('Limpio', 'Limpio'), ('Sospechoso', 'Sospechoso'), ('Vulnerable', 'Vulnerable')], default='Limpio', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad Inyeccion (A01)',
                'verbose_name_plural': 'Vulnerabilidades Inyeccion (A01)',
                'db_table': 'vulnerabilidad_inyeccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VulnerabilidadXSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.TextField(help_text='Payload XSS probado')),
                ('endpoint', models.CharField(max_length=255)),
                ('parametros', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('Limpio', 'Limpio'), ('Sospechoso', 'Sospechoso'), ('Vulnerable', 'Vulnerable')], default='Limpio', max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_prueba', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad XSS (A07)',
                'verbose_name_plural': 'Vulnerabilidades XSS (A07)',
                'db_table': 'vulnerabilidad_xss',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VulnerabilidadXXE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('parser', models.CharField(help_text='Ej: xml.etree, lxml, DOMParser', max_length=50)),
                ('permite_dtd', models.BooleanField(default=False)),
                ('permite_entities', models.BooleanField(default=False)),
                ('resultado', models.CharField(choices=[('Seguro', 'Seguro'), ('Sospechoso', 'Sospechoso'), ('Vulnerable', 'Vulnerable')], default='Seguro', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad XXE (A04)',
                'verbose_name_plural': 'Vulnerabilidades XXE (A04)',
                'db_table': 'vulnerabilidad_xxe',
                'managed': True,
            },
        ),
    ]
